import { expect, test } from 'vitest';
require('../src/stage');
require('../src/composers/motifs');

test('getScheduledNotes picks correct notes within window and respects max', () => {
  const schedule = [
    {note:60,startTick:100,duration:30},
    {note:62,startTick:120,duration:30},
    {note:64,startTick:140,duration:30},
    {note:65,startTick:160,duration:30}
  ];
  const picks = getScheduledNotes(schedule, 110, 150, 2);
  expect(picks.length).toBe(2);
  expect(picks[0].note).toBe(62);
  expect(picks[1].note).toBe(64);
});

// Verify integration: motif schedule generated by MotifComposer sums correctly and can be filtered
test('MotifComposer schedule sums to totalTicks and filters', () => {
  const mc = new MotifComposer();
  const totalTicks = 960;
  const m = mc.generate({ length: 4, fitToTotalTicks: true, totalTicks });
  const seq = m.sequence || m.events || [];
  const sum = seq.reduce((a,b)=>a + (b.duration || 0), 0);
  expect(sum).toBe(totalTicks);
  const schedule = [];
  let cursor = 0;
  seq.forEach(evt => { schedule.push({ note: evt.note, startTick: cursor, duration: evt.duration }); cursor += evt.duration; });
  const hits = getScheduledNotes(schedule, 200, 400, 3);
  expect(hits.length).toBeLessThanOrEqual(3);
});
