export default [
  {
    ignores: ['eslint.config.mjs', 'vitest.config.mjs', 'tmp/**']
  },
  {
    files: ['eslint.config.mjs'],
    languageOptions: { sourceType: 'module', ecmaVersion: 'latest' }
  },
  {
    files: ['src/**/*.js', 'src/**', 'test/**/*.js', 'test/**'],
    ignores: [
      '**/*.mjs',
      'node_modules/**',
      'csv_maestro/**',
      'output/**',
      'tmp/**',
      '__pycache__/**'
    ]
  },
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        // Math alias
        m: 'readonly',
        // Timing globals
        numerator: 'writable',
        denominator: 'writable',
        meterRatio: 'writable',
        midiMeter: 'writable',
        midiMeterRatio: 'writable',
        syncFactor: 'writable',
        midiBPM: 'writable',
        tpSec: 'writable',
        tpMeasure: 'writable',
        spMeasure: 'writable',
        phraseStart: 'writable',
        phraseStartTime: 'writable',
        sectionStart: 'writable',
        sectionStartTime: 'writable',
        sectionEnd: 'writable',
        measureStart: 'writable',
        measureStartTime: 'writable',
        beatStart: 'writable',
        beatStartTime: 'writable',
        divStart: 'writable',
        divStartTime: 'writable',
        subdivStart: 'writable',
        subdivStartTime: 'writable',
        subsubdivStart: 'writable',
        subsubdivStartTime: 'writable',
        tpBeat: 'writable',
        spBeat: 'writable',
        tpDiv: 'writable',
        spDiv: 'writable',
        tpSubdiv: 'writable',
        spSubdiv: 'writable',
        tpSubsubdiv: 'writable',
        spSubsubdiv: 'writable',
        tpPhrase: 'writable',
        spPhrase: 'writable',
        tpSection: 'writable',
        spSection: 'writable',
        trueBPM: 'writable',
        trueBPM2: 'writable',
        bpmRatio: 'writable',
        bpmRatio2: 'writable',
        bpmRatio3: 'writable',
        divsPerBeat: 'writable',
        subdivsPerDiv: 'writable',
        subdivsPerMinute: 'writable',
        subsubsPerSub: 'writable',
        subsubsPerMinute: 'writable',
        subdivFreq: 'writable',
        measuresPerPhrase: 'writable',
        measuresPerPhrase1: 'writable',
        measuresPerPhrase2: 'writable',
        polyNumerator: 'writable',
        polyDenominator: 'writable',
        polyMeterRatio: 'writable',
        // Rhythm tracking
        beatRhythm: 'writable',
        divRhythm: 'writable',
        subdivRhythm: 'writable',
        subsubdivRhythm: 'writable',
        // Index variables
        sectionIndex: 'writable',
        phraseIndex: 'writable',
        measureIndex: 'writable',
        beatIndex: 'writable',
        divIndex: 'writable',
        subdivIndex: 'writable',
        subsubdivIndex: 'writable',
        // Structure
        totalSections: 'writable',
        phrasesPerSection: 'writable',
        // Temporary variables (used in functions)
        unit: 'writable',
        unitsPerParent: 'writable',
        startTick: 'writable',
        endTick: 'writable',
        startTime: 'writable',
        endTime: 'writable',
        composerDetails: 'writable',
        progressionSymbols: 'writable',
        actualMeter: 'writable',
        isPowerOf2: 'writable',
        // Buffer/Layer
        c: 'writable',
        c1: 'writable',
        c2: 'writable',
        CSVBuffer: 'writable',
        LM: 'writable',
        layerManager: 'writable',
        TimingContext: 'writable',
        // Configuration
        BPM: 'readonly',
        PPQ: 'readonly',
        TUNING_FREQ: 'readonly',
        LOG: 'readonly',
        BINAURAL: 'readonly',
        SILENT_OUTRO_SECONDS: 'readonly',
        SECTIONS: 'readonly',
        PHRASES_PER_SECTION: 'readonly',
        NUMERATOR: 'readonly',
        DENOMINATOR: 'readonly',
        MEASURES_PER_PHRASE: 'readonly',
        DIVISIONS: 'readonly',
        SUBDIVISIONS: 'readonly',
        SUBSUBDIVISIONS: 'readonly',
        VOICES: 'readonly',
        OCTAVES: 'readonly',
        COMPOSER_TYPES: 'readonly',
        primaryInstrument: 'readonly',
        secondaryInstrument: 'readonly',
        otherInstruments: 'readonly',
        bassInstrument: 'readonly',
        bassInstrument2: 'readonly',
        otherBassInstruments: 'readonly',
        drumSets: 'readonly',
        // Composers
        composer: 'writable',
        composers: 'writable',
        MeasureComposer: 'writable',
        ScaleComposer: 'writable',
        RandomScaleComposer: 'writable',
        ChordComposer: 'writable',
        RandomChordComposer: 'writable',
        ModeComposer: 'writable',
        RandomModeComposer: 'writable',
        TensionReleaseComposer: 'writable',
        ModalInterchangeComposer: 'writable',
        HarmonicRhythmComposer: 'writable',
        MelodicDevelopmentComposer: 'writable',
        AdvancedVoiceLeadingComposer: 'writable',
        PentatonicComposer: 'writable',
        RandomPentatonicComposer: 'writable',
        ComposerFactory: 'writable',
        ProgressionGenerator: 'writable',
        // Functions
        getMidiTiming: 'writable',
        setMidiTiming: 'writable',
        getPolyrhythm: 'writable',
        setUnitTiming: 'writable',
        formatTime: 'writable',
        setRhythm: 'writable',
        trackBeatRhythm: 'writable',
        trackDivRhythm: 'writable',
        trackSubdivRhythm: 'writable',
        trackSubsubdivRhythm: 'writable',
        logUnit: 'writable',
        p: 'writable',
        pushMultiple: 'writable',
        grandFinale: 'writable',
        fs: 'writable',
        setTuningAndInstruments: 'writable',
        // MIDI/Venue
        midiData: 'readonly',
        getMidiValue: 'writable',
        allCHs: 'readonly',
        allNotes: 'readonly',
        allScales: 'readonly',
        allChords: 'readonly',
        allModes: 'readonly',
        t: 'readonly',  // Tonal.js library
        source: 'readonly',
        bass: 'readonly',
        lCH1: 'readonly',
        lCH2: 'readonly',
        rCH1: 'readonly',
        rCH2: 'readonly',
        cCH1: 'readonly',
        cCH2: 'readonly',
        cCH3: 'readonly',
        drumCH: 'readonly',
        tuningPitchBend: 'readonly',
        // Rhythm
        drumMap: 'readonly',
        drummer: 'writable',
        patternLength: 'writable',
        makeOnsets: 'writable',
        // Stage functions
        binaural: 'writable',
        stutter: 'writable',
        note: 'writable',
        // Backstage utils - Clamping functions
        clamp: 'writable',
        modClamp: 'writable',
        lowModClamp: 'writable',
        highModClamp: 'writable',
        scaleClamp: 'writable',
        scaleBoundClamp: 'writable',
        softClamp: 'writable',
        clampSoft: 'writable',
        stepClamp: 'writable',
        clampStep: 'writable',
        logClamp: 'writable',
        clampLog: 'writable',
        expClamp: 'writable',
        clampExp: 'writable',
        // Backstage utils - Random functions
        rf: 'writable',
        randomFloat: 'writable',
        ri: 'writable',
        randomInt: 'writable',
        ra: 'writable',
        rw: 'writable',
        randomWeightedInRange: 'writable',
        randomWeightedInArray: 'writable',
        randomWeightedSelection: 'writable',
        randomInRangeOrArray: 'writable',
        rd: 'writable',
        rl: 'writable',
        rlc: 'writable',
        randomLimitedChange: 'writable',
        rv: 'writable',
        randomVariation: 'writable',
        normalizeWeights: 'writable',
        allNotesOff: 'writable',
        muteAll: 'writable',
        // Sheet.js constants
        OCTAVE: 'readonly',
        NUMERATOR: 'readonly',
        DENOMINATOR: 'readonly',
        METER_RATIO_MIN: 'readonly',
        METER_RATIO_MAX: 'readonly',
        DIVISIONS: 'readonly',
        SUBSUBDIVS: 'readonly',
        COMPOSERS: 'readonly',
        SECTIONS: 'readonly',
        // Audio channels (left/right pairs)
        lCH1: 'writable',
        rCH1: 'writable',
        lCH2: 'writable',
        rCH2: 'writable',
        lCH3: 'writable',
        rCH3: 'writable',
        lCH4: 'writable',
        rCH4: 'writable',
        lCH5: 'writable',
        rCH5: 'writable',
        lCH6: 'writable',
        rCH6: 'writable',
        // Timing state arrays
        beatsOn: 'writable',
        beatsOff: 'writable',
        divsOn: 'writable',
        divsOff: 'writable',
        subdivsOn: 'writable',
        subdivsOff: 'writable',
        subsubdivsOn: 'writable',
        subsubdivsOff: 'writable',
        // Audio FX and binaural effects
        rlFX: 'writable',
        chFX: 'writable',
        flipBin: 'writable',
        flipBinT: 'writable',
        flipBinF: 'writable',
        flipBinT3: 'writable',
        flipBinF3: 'writable',
        flipBinF2: 'writable',
        flipBinT2: 'writable',
        reflection: 'writable',
        reflectionBinaural: 'writable',
        reflect: 'writable',
        reflect2: 'writable',
        source2: 'writable',
        binauralL: 'writable',
        binauralR: 'writable',
        binauralFreqOffset: 'writable',
        binauralOffset: 'writable',
        binauralPlus: 'writable',
        binauralMinus: 'writable',
        bassBinaural: 'writable',
        stutterFadeCHs: 'writable',
        stutterPanCHs: 'writable',
        // Additional timing + globals (project naked globals)
        measureCount: 'writable',
        finalTick: 'writable',
        finalTime: 'writable',
        bestMatch: 'writable',
        tpPhrase1: 'writable',
        tpPhrase2: 'writable',
        subdivsPerBeat: 'writable',
        subsubsPerSub: 'writable',
        beatsUntilBinauralShift: 'writable',
        beatCount: 'writable',
        noteCount: 'writable',
        balOffset: 'writable',
        sideBias: 'writable',
        firstLoop: 'writable',
        lastCrossMod: 'writable',
        activeMotif: 'writable',
        currentSectionType: 'writable',
        currentSectionDynamics: 'writable',
        crossModulation: 'writable',
        lastMeter: 'writable',
        lastUsedCHs: 'writable',
        lastUsedCHs2: 'writable',
        lastUsedCHs3: 'writable',
        velocity: 'writable',
        neutralPitchBend: 'writable',
        semitone: 'writable',
        tuningPitchBend: 'writable',
        FX: 'writable',
        __POLYCHRON_TEST__: 'writable',
        // Exposed helpers / classes
        TimingCalculator: 'writable',
        VoiceLeadingScore: 'writable',
        SECTION_TYPES: 'readonly',
        csvRows: 'writable',
        // Utility and temporary globals
        _: 'writable',
        // AVOID in favor of naked global usage only!
        // global: 'readonly',
        resetIndexWithChildren: 'writable',
        LM: 'writable',
        stage: 'writable',
        fxManager: 'writable',
        refVar: 'writable',
        cBal: 'writable',
        cBal2: 'writable',
        cBal3: 'writable',
        lBal: 'writable',
        rBal: 'writable',
        bassVar: 'writable',
        // Motif helpers
        Motif: 'writable',
        clampMotifNote: 'writable',
        applyMotifToNotes: 'writable',
        // Rhythm helpers
        closestDivisor: 'writable',
        binary: 'writable',
        hex: 'writable',
        onsets: 'writable',
        random: 'writable',
        prob: 'writable',
        euclid: 'writable',
        rotate: 'writable',
        morph: 'writable',
        // Misc
        canonicalKeys: 'writable',
        beatKey: 'writable',
        divKey: 'writable',
        performance: 'writable',
        // Audio/rhythm functions
        playDrums: 'writable',
        playDrums2: 'writable',
        getRhythm: 'writable',
        rhythms: 'writable',
        // Node.js globals
        require: 'readonly',
        module: 'readonly',
        exports: 'writable',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        // Allow Node and environment global objects and some test-only temp names
        // 'global' and 'globalThis' are banned project-wide; use naked globals instead
        resolveSectionProfile: 'writable',
        selectSectionType: 'writable',
        normalizeSectionType: 'writable',
        _origRf: 'writable',
        _origRv: 'writable',
        _origRi: 'writable',
        __POLYCHRON_PREVENT_AUTO_START: 'writable',
      }
    },
    rules: {
      // Code correctness - errors that break functionality
      'no-undef': 'error',  // Catch undefined variables like activeMotif
      'no-restricted-globals': ['error', { name: 'global', message: 'global or globalThis banned project-wide, use naked globals instead' }, { name: 'globalThis', message: 'global or globalThis banned project-wide, use naked globals instead' }],
      'no-unreachable': 'error',  // Dead code after return/throw
      'no-constant-condition': 'warn',  // Conditions always true/false (can be intentional)
      'no-dupe-keys': 'error',  // Duplicate object keys
      'no-dupe-args': 'error',  // Duplicate function parameters
      'no-duplicate-case': 'error',  // Duplicate switch cases
      'no-empty': 'warn',  // Empty blocks (may be intentional)
      'no-ex-assign': 'error',  // Reassigning exception variable
      'no-func-assign': 'error',  // Reassigning function declarations
      'no-invalid-regexp': 'error',  // Invalid regex patterns
      'use-isnan': 'error',  // Require isNaN() for NaN checks
      'valid-typeof': 'error',  // Enforce valid typeof comparisons
      'no-self-assign': 'error',  // Catch x = x mistakes
      'no-cond-assign': ['error', 'except-parens'],  // No assignment in conditions (catch = vs ==)
      'no-fallthrough': 'warn',  // Require break in switch cases

      // Code quality
      'no-irregular-whitespace': 'error',
      'no-unexpected-multiline': 'error',
      'no-useless-escape': 'warn',
      'no-trailing-spaces': 'warn',
      'eol-last': ['warn', 'always'],
      'no-unused-vars': 'off'  // Too many intentional globals
    }
  },
  {
    files: ['test/**/*.js', 'test/**'],
    languageOptions: {
      sourceType: 'module',
      ecmaVersion: 'latest',
      globals: {
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly'
      }
    }
  },
  {
    files: ['scripts/**/*.js', 'scripts/**'],
    languageOptions: {
      sourceType: 'module'
    }
  }
];
