import localRules from './eslint-rules/index.js';

const restrictedGlobalsMessage = 'Global keywords banned project-wide, use naked globals instead (Example: DONT use: globalThis.variable DO use: variable)';

export default [
  {
    // Do not lint ESLint helpers and config shims
    ignores: ['eslint.config.mjs', 'vitest.config.mjs', 'tmp/**', 'eslint-rules/**']
  },
  {
    files: ['eslint.config.mjs'],
    languageOptions: { sourceType: 'module', ecmaVersion: 'latest' }
  },
  {
    files: ['src/**/*.js', 'src/**'],
    ignores: [
      '**/*.mjs',
      'node_modules/**',
      'csv_maestro/**',
      'output/**',
      'tmp/**',
      '__pycache__/**'
    ],
    // Ban any comment that begins with "global" (e.g., /* global ... */) to enforce
    // the project's requirement to use naked globals via side-effect requires only.
    // Also enforce stricter static rules and a project-specific rule to catch
    // silent early returns (must log or explicitly handle before returning).
    plugins: { local: localRules },
    rules: {
      'no-warning-comments': ['error', { terms: ['global'], location: 'start' }],
      'consistent-return': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-implicit-coercion': ['warn', { 'boolean': true, 'number': true, 'string': true, 'allow': [] }],
      'no-undef': 'error',
      'local/no-silent-early-return': ['error', { allowInTests: false }],
      'local/no-requires-outside-index': ['error']
    }
  },
  // Tests are intentionally excluded from linting to avoid enforcing project naked-global rules
  // which are not applicable to test scaffolding and helper usage.
  { ignores: ['test/**'] },

  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        // Math alias
        m: 'readonly',
        // Timing globals
        numerator: 'writable',
        denominator: 'writable',
        meterRatio: 'writable',
        midiMeter: 'writable',
        midiMeterRatio: 'writable',
        syncFactor: 'writable',
        midiBPM: 'writable',
        tpSec: 'writable',
        unitIndex: 'writable',
        unitStart: 'writable',
        tpUnit: 'writable',
        parentStart: 'writable',
        tpParent: 'writable',
        unitsPerParent: 'writable',
        // Last layer for which getMidiTiming/setMidiTiming was executed
        lastMidiLayer: 'writable',
        tpMeasure: 'writable',
        spMeasure: 'writable',
        phraseStart: 'writable',
        phraseStartTime: 'writable',
        sectionStart: 'writable',
        sectionStartTime: 'writable',
        sectionEnd: 'writable',
        measureStart: 'writable',
        measureStartTime: 'writable',
        beatStart: 'writable',
        beatStartTime: 'writable',
        divStart: 'writable',
        divStartTime: 'writable',
        subdivStart: 'writable',
        subdivStartTime: 'writable',
        subsubdivStart: 'writable',
        subsubdivStartTime: 'writable',
        tpBeat: 'writable',
        spBeat: 'writable',
        tpDiv: 'writable',
        spDiv: 'writable',
        tpSubdiv: 'writable',
        spSubdiv: 'writable',
        tpSubsubdiv: 'writable',
        spSubsubdiv: 'writable',
        tpPhrase: 'writable',
        spPhrase: 'writable',
        tpSection: 'writable',
        spSection: 'writable',
        trueBPM: 'writable',
        trueBPM2: 'writable',
        bpmRatio: 'writable',
        bpmRatio2: 'writable',
        bpmRatio3: 'writable',
        divsPerBeat: 'writable',
        subdivsPerDiv: 'writable',
        subdivsPerMinute: 'writable',
        subsubsPerSub: 'writable',
        subsubsPerMinute: 'writable',
        subdivFreq: 'writable',
        measuresPerPhrase: 'writable',
        measuresPerPhrase1: 'writable',
        measuresPerPhrase2: 'writable',
        polyNumerator: 'writable',
        polyDenominator: 'writable',
        polyMeterRatio: 'writable',
        // Rhythm tracking
        beatRhythm: 'writable',
        divRhythm: 'writable',
        subdivRhythm: 'writable',
        subsubdivRhythm: 'writable',
        // Index variables
        sectionIndex: 'writable',
        phraseIndex: 'writable',
        measureIndex: 'writable',
        beatIndex: 'writable',
        divIndex: 'writable',
        subdivIndex: 'writable',
        subsubdivIndex: 'writable',
        // Structure
        totalSections: 'writable',
        phrasesPerSection: 'writable',
        // Temporary variables (used in functions)
        unit: 'writable',
        unitsPerParent: 'writable',
        startTick: 'writable',
        endTick: 'writable',
        startTime: 'writable',
        endTime: 'writable',
        composerDetails: 'writable',
        progressionSymbols: 'writable',
        actualMeter: 'writable',
        isPowerOf2: 'writable',
        // Buffer/Layer
        c: 'writable',
        c1: 'writable',
        c2: 'writable',
        CSVBuffer: 'writable',
        LM: 'writable',
        layerManager: 'writable',
        TimingContext: 'writable',
        // Configuration
        BPM: 'readonly',
        PPQ: 'readonly',
        TUNING_FREQ: 'readonly',
        LOG: 'readonly',
        BINAURAL: 'readonly',
        SILENT_OUTRO_SECONDS: 'readonly',
        SECTIONS: 'readonly',
        PHRASES_PER_SECTION: 'readonly',
        NUMERATOR: 'readonly',
        DENOMINATOR: 'readonly',
        MEASURES_PER_PHRASE: 'readonly',
        DIVISIONS: 'readonly',
        SUBDIVS: 'readonly',
        SUBSUBDIVISIONS: 'readonly',
        VOICES: 'readonly',
        OCTAVES: 'readonly',
        COMPOSER_TYPES: 'readonly',
        primaryInstrument: 'readonly',
        secondaryInstrument: 'readonly',
        otherInstruments: 'readonly',
        bassInstrument: 'readonly',
        bassInstrument2: 'readonly',
        otherBassInstruments: 'readonly',
        drumSets: 'readonly',
        // Composers
        composer: 'writable',
        composers: 'writable',
        MeasureComposer: 'writable',
        ScaleComposer: 'writable',
        RandomScaleComposer: 'writable',
        ChordComposer: 'writable',
        RandomChordComposer: 'writable',
        ModeComposer: 'writable',
        RandomModeComposer: 'writable',
        TensionReleaseComposer: 'writable',
        ModalInterchangeComposer: 'writable',
        HarmonicRhythmComposer: 'writable',
        MelodicDevelopmentComposer: 'writable',
        VoiceLeadingComposer: 'writable',
        MotifComposer: 'writable',
        Motif: 'writable',
        PentatonicComposer: 'writable',
        RandomPentatonicComposer: 'writable',
        IntervalComposer: 'writable',
        PhraseArcManager: 'writable',
        ComposerFactory: 'writable',
        HarmonicContext: 'writable',
        MotifChain: 'writable',
        EventBus: 'writable',
        FXFeedbackListener: 'writable',
        PhaseLockedRhythmGenerator: 'writable',
        ProgressionGenerator: 'writable',
        // Debug/Test helpers
        logGate: 'writable',
        getScheduledNotes: 'writable',
        __test_playBeat: 'writable',
        // Functions
        getMidiTiming: 'writable',
        setMidiTiming: 'writable',
        getPolyrhythm: 'writable',
        setUnitTiming: 'writable',
        formatTime: 'writable',
        setRhythm: 'writable',
        trackBeatRhythm: 'writable',
        trackDivRhythm: 'writable',
        trackSubdivRhythm: 'writable',
        trackSubsubdivRhythm: 'writable',
        logUnit: 'writable',
        p: 'writable',
        pushMultiple: 'writable',
        grandFinale: 'writable',
        fs: 'writable',
        setTuningAndInstruments: 'writable',
        // MIDI/Venue
        midiData: 'readonly',
        getMidiValue: 'writable',
        allCHs: 'readonly',
        allNotes: 'readonly',
        allScales: 'readonly',
        allChords: 'readonly',
        allModes: 'readonly',
        t: 'readonly',  // Tonal.js library
        source: 'readonly',
        bass: 'readonly',
        lCH1: 'readonly',
        lCH2: 'readonly',
        rCH1: 'readonly',
        rCH2: 'readonly',
        cCH1: 'readonly',
        cCH2: 'readonly',
        cCH3: 'readonly',
        drumCH: 'readonly',
        tuningPitchBend: 'readonly',
        // Rhythm
        drumMap: 'readonly',
        drummer: 'writable',
        patternLength: 'writable',
        makeOnsets: 'writable',
        // Rhythm-pattern module helpers (naked globals assigned via require)
        _rp: 'writable',
        _binary: 'writable',
        _hex: 'writable',
        _onsets: 'writable',
        _random: 'writable',
        _probability: 'writable',
        _euclid: 'writable',
        _rotate: 'writable',
        path: 'writable',
        // Stage functions
        binaural: 'writable',
        stutter: 'writable',
        note: 'writable',
        // Backstage utils - Clamping functions
        clamp: 'writable',
        modClamp: 'writable',
        lowModClamp: 'writable',
        highModClamp: 'writable',
        scaleClamp: 'writable',
        scaleBoundClamp: 'writable',
        softClamp: 'writable',
        clampSoft: 'writable',
        stepClamp: 'writable',
        clampStep: 'writable',
        logClamp: 'writable',
        clampLog: 'writable',
        expClamp: 'writable',
        clampExp: 'writable',
        // Backstage utils - Random functions
        rf: 'writable',
        randomFloat: 'writable',
        ri: 'writable',
        randomInt: 'writable',
        ra: 'writable',
        rw: 'writable',
        randomWeightedInRange: 'writable',
        randomWeightedInArray: 'writable',
        randomWeightedSelection: 'writable',
        randomInRangeOrArray: 'writable',
        rd: 'writable',
        rl: 'writable',
        rlc: 'writable',
        randomLimitedChange: 'writable',
        rv: 'writable',
        randomVariation: 'writable',
        normalizeWeights: 'writable',
        allNotesOff: 'writable',
        muteAll: 'writable',
        // Sheet.js constants
        OCTAVE: 'readonly',
        NUMERATOR: 'readonly',
        DENOMINATOR: 'readonly',
        METER_RATIO_MIN: 'readonly',
        METER_RATIO_MAX: 'readonly',
        DIVISIONS: 'readonly',
        SUBSUBDIVS: 'readonly',
        COMPOSERS: 'readonly',
        SECTIONS: 'readonly',
        DYNAMISM: 'readonly',
        STUTTER_PROBABILITIES: 'readonly',
        STUTTER_PROFILES: 'readonly',
        STUTTER_VELOCITY_RANGES: 'readonly',
        NOISE_PROFILES: 'readonly',
        VOICE_Manager: 'readonly',
        // Audio channels (left/right pairs)
        lCH1: 'writable',
        rCH1: 'writable',
        lCH2: 'writable',
        rCH2: 'writable',
        lCH3: 'writable',
        rCH3: 'writable',
        lCH4: 'writable',
        rCH4: 'writable',
        lCH5: 'writable',
        rCH5: 'writable',
        lCH6: 'writable',
        rCH6: 'writable',
        // Timing state arrays
        beatsOn: 'writable',
        beatsOff: 'writable',
        divsOn: 'writable',
        divsOff: 'writable',
        subdivsOn: 'writable',
        subdivsOff: 'writable',
        subsubdivsOn: 'writable',
        subsubdivsOff: 'writable',
        // Audio FX and binaural effects
        rlFX: 'writable',
        chFX: 'writable',
        flipBin: 'writable',
        flipBinT: 'writable',
        flipBinF: 'writable',
        flipBinT3: 'writable',
        flipBinF3: 'writable',
        flipBinF2: 'writable',
        flipBinT2: 'writable',
        reflection: 'writable',
        reflectionBinaural: 'writable',
        reflect: 'writable',
        reflect2: 'writable',
        source2: 'writable',
        binauralL: 'writable',
        binauralR: 'writable',
        binauralFreqOffset: 'writable',
        binauralOffset: 'writable',
        binauralPlus: 'writable',
        binauralMinus: 'writable',
        bassBinaural: 'writable',
        stutterFadeCHs: 'writable',
        stutterPanCHs: 'writable',
        // Additional timing + globals (project naked globals)
        measureCount: 'writable',
        finalTick: 'writable',
        finalTime: 'writable',
        bestMatch: 'writable',
        tpPhrase1: 'writable',
        tpPhrase2: 'writable',
        subdivsPerBeat: 'writable',
        subsubsPerSub: 'writable',
        beatsUntilBinauralShift: 'writable',
        beatCount: 'writable',
        noteCount: 'writable',
        balOffset: 'writable',
        sideBias: 'writable',
        firstLoop: 'writable',
        lastCrossMod: 'writable',
        activeMotif: 'writable',
        currentSectionType: 'writable',
        currentSectionDynamics: 'writable',
        crossModulation: 'writable',
        lastMeter: 'writable',
        lastUsedCHs: 'writable',
        lastUsedCHs2: 'writable',
        lastUsedCHs3: 'writable',
        velocity: 'writable',
        neutralPitchBend: 'writable',
        semitone: 'writable',
        tuningPitchBend: 'writable',
        FX: 'writable',
        // Play-guard / script helpers
        LOCK_DIR: 'writable',
        LOCK_PATH: 'writable',
        FIN_PATH: 'writable',
        HEARTBEAT_INTERVAL_MS: 'writable',
        STALE_MS: 'writable',
        GRACE_MS: 'writable',
        isPidAlive: 'writable',
        writeLock: 'writable',
        acquireLock: 'writable',
        releaseLock: 'writable',
        main: 'writable',
        // Exposed helpers / classes
        TimingCalculator: 'writable',
        VoiceLeadingScore: 'writable',
        VoiceManager: 'writable',
        VoiceRegistry: 'writable',
        VoiceStrategyRegistry: 'writable',
        // Centralized profile globals
        VOICE_PROFILES: 'writable',
        CHORD_PROFILES: 'writable',
        MOTIF_PROFILES: 'writable',
        RHYTHM_PROFILES: 'writable',
        VoiceManager: 'writable',
        SECTION_TYPES: 'readonly',
        csvRows: 'writable',
        // Utility and temporary globals
        _: 'writable',
        // AVOID in favor of naked global usage only!
        // global: 'readonly',
        LM: 'writable',
        StutterManager: 'writable',
        StutterAsNoteSource: 'writable',
        scheduleStutterNotesFromDensity: 'writable',
        Stutter: 'writable',
        StutterConfig: 'readonly',
        StutterConfigStore: 'readonly',
        StutterMetrics: 'readonly',
        StutterRegistry: 'readonly',
        refVar: 'writable',
        cBal: 'writable',
        cBal2: 'writable',
        cBal3: 'writable',
        lBal: 'writable',
        rBal: 'writable',
        bassVar: 'writable',
        // Motif helpers
        Motif: 'writable',
        MotifSpreader: 'writable',
        clampMotifNote: 'writable',
        applyMotifToNotes: 'writable',
        // Rhythm helpers
        closestDivisor: 'writable',
        binary: 'writable',
        hex: 'writable',
        onsets: 'writable',
        random: 'writable',
        prob: 'writable',
        euclid: 'writable',
        rotate: 'writable',
        morph: 'writable',
        // Misc
        canonicalKeys: 'writable',
        beatKey: 'writable',
        divKey: 'writable',
        performance: 'writable',
        // Utility functions
        normalizeChordSymbol: 'readonly',
        writeDebugFile: 'readonly',
        playNotes: 'readonly',
        playMotifs: 'readonly',
        // Audio/rhythm functions
        playDrums: 'writable',
        playDrums2: 'writable',
        getRhythm: 'writable',
        rhythms: 'writable',
        // Play & FX helpers (project-naked globals)
        setOtherInstruments: 'writable',
        setBinaural: 'writable',
        setBalanceAndFX: 'writable',
        stutterFX: 'writable',
        stutterFade: 'writable',
        stutterPan: 'writable',
        stutterNotes: 'writable',
        // Noise functions
        SimplexNoise: 'writable',
        fbm: 'writable',
        turbulence: 'writable',
        ridged: 'writable',
        worley: 'writable',
        easeInOut: 'writable',
        easingFunctions: 'writable',
        noiseFunctions: 'writable',
        metaRecursiveEaseNoise: 'writable',
        metaRecursiveNoise: 'writable',
        metaRecursiveSimplex2D: 'writable',
        metaRecursiveFBM: 'writable',
        permutation: 'writable',
        fade: 'writable',
        lerp: 'writable',
        grad: 'writable',
        perlinNoise: 'writable',
        // Noise Manager
        defaultSimplex: 'writable',
        noiseGenerators: 'writable',
        generatorKeys: 'writable',
        getNoiseValue: 'writable',
        layeredNoise: 'writable',
        createNoiseOffset: 'writable',
        randomNoiseGenerator: 'writable',
        noiseInfluenceMap: 'writable',
        createDualAxisNoiseConfig: 'writable',
        applyDualAxisNoise: 'writable',
        safeApplyNoise: 'writable',
        clampNoiseValue: 'writable',
        getParameterModulation: 'writable',
        smoothNoiseValue: 'writable',
        getNoiseProfile: 'writable',
        applyNoiseToVelocity: 'writable',
        applyNoiseToPan: 'writable',
        applyNoiseToSustain: 'writable',
        applyNoiseToParameter: 'writable',
        getNoiseProfileOrFail: 'writable',
        registerNoiseGenerator: 'writable',
        applyComposerPitchNoise: 'writable',
        applyMelodicTranspositionNoise: 'writable',
        applyMelodicPivotNoise: 'writable',
        applyMelodicDurationNoise: 'writable',
        applyVoiceLeadingWeightNoise: 'writable',
        resetChannelTracking: 'writable',
        playSubdivNotes: 'writable',
        playSubsubdivNotes: 'writable',
        setSubdivNoteParams: 'writable',
        setSubsubdivNoteParams: 'writable',
        crossModulateRhythms: 'writable',
        // Short-lived audio helpers
        on: 'writable',
        shortSustain: 'writable',
        longSustain: 'writable',
        useShort: 'writable',
        sustain: 'writable',
        binVel: 'writable',
        Stutter: 'writable',
        balOffset: 'writable',
        sideBias: 'writable',
        // Rhythm helper globals
        trackRhythm: 'writable',
        buildGlobalContext: 'writable',
        rhythmMethods: 'writable',
        RhythmRegistry: 'writable',
        RhythmManager: 'writable',
        RhythmValues: 'writable',
        rhythmConfig: 'writable',
        rhythmModulator: 'writable',
        // Chord subsystem globals
        ChordRegistry: 'writable',
        ChordManager: 'writable',
        ChordValues: 'writable',
        chordConfig: 'writable',
        chordModulator: 'writable',
        // Motif subsystem globals
        MotifRegistry: 'writable',
        MotifManager: 'writable',
        MotifValues: 'writable',
        motifConfig: 'writable',
        motifModulator: 'writable',
        // Voice subsystem globals
        VoiceRegistry: 'writable',
        VoiceValues: 'writable',
        voiceConfig: 'writable',
        voiceModulator: 'writable',
        // Node.js globals
        require: 'readonly',
        module: 'readonly',
        exports: 'writable',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        // Allow Node and environment global objects and some test-only temp names
        // 'global' and 'globalThis' are banned project-wide; use naked globals instead(DONT use: globalThis.variable DO use: variable)
        resolveSectionProfile: 'writable',
        selectSectionType: 'writable',
        normalizeSectionType: 'writable',
        _origRf: 'writable',
        _origRv: 'writable',
        _origRi: 'writable',
      }
    },
    rules: {
      // Code correctness - errors that break functionality
      'no-undef': 'error',  // Catch undefined variables like activeMotif
      'no-restricted-globals': ['error', { name: 'global', message: 'Global keywords banned project-wide, use naked globals instead(DONT use: globalThis.variable DO use: variable)' }, { name: 'globalThis', message: 'Global keywords banned project-wide, use naked globals instead(DONT use: globalThis.variable DO use: variable)' }, { name: 'GLOBAL', message: 'Global keywords banned project-wide, use naked globals instead(DONT use: globalThis.variable DO use: variable)' }, { name: 'GLOBALTHIS', message: 'Global keywords banned project-wide, use naked globals instead(DONT use: globalThis.variable DO use: variable)' }, { name: 'GLOBALS', message: 'Global keywords banned project-wide, use naked globals instead(DONT use: globalThis.variable DO use: variable)' }, { name: 'globals', message: 'Global keywords banned project-wide, use naked globals instead(DONT use: globalThis.variable DO use: variable)' }],
      // Disallow runtime code-gen and common module-export workarounds that subvert naked global policy
      'no-new-func': 'error',
      'no-restricted-syntax': [
        'error',
        // Prevent calling Function(...) to synthesize code or create globals (covers Function(...))
        { selector: "CallExpression[callee.name='Function']", message: 'Do not call the Function constructor to generate code or create globals; use naked global assignment instead.' },
        // Prevent new Function(...)
        { selector: "NewExpression[callee.name='Function']", message: 'Do not use the Function constructor; use naked global assignment instead.' },
        // Prevent top-level assignments to `this` (e.g., `this.x = ...`) which act like module-scoped exports
        { selector: "Program > ExpressionStatement > AssignmentExpression[left.type='MemberExpression'][left.object.type='ThisExpression']", message: 'Top-level assignments to `this` are banned; define naked globals instead (e.g. `x = ...`).' },
        // Ban direct module.exports and exports usage (use naked globals instead)
        { selector: "MemberExpression[object.name='module'][property.name='exports']", message: 'module.exports is banned; use naked global assignments and side-effect requires.' },
        { selector: "MemberExpression[object.name='exports']", message: 'exports.* is banned; use naked global assignments and side-effect requires.' },
        // Ban global/globalThis property access
        { selector: "MemberExpression[object.name='globalThis']", message: 'Do not use globalThis; use naked globals instead.' },
        { selector: "MemberExpression[object.name='global']", message: 'Do not use global; use naked globals instead.' },
        // Prevent noisy conditional top-level assignments to naked globals e.g. `x = typeof Stutter.x === 'function' ? Stutter.x.bind(Stutter) : x;`
        { selector: "Program > ExpressionStatement > AssignmentExpression[left.type='Identifier'][right.type='ConditionalExpression']", message: 'Avoid conditional top-level reassignments to naked globals; bind instance methods once or provide explicit wrapper functions instead.' },
        // Ban eval-based code execution
        { selector: "CallExpression[callee.name='eval']", message: 'eval is banned; do not use string-to-code execution.' }
      ],
      'no-unreachable': 'error',  // Dead code after return/throw
      'no-constant-condition': 'error',  // Conditions always true/false (can be intentional)
      'no-dupe-keys': 'error',  // Duplicate object keys
      'no-dupe-args': 'error',  // Duplicate function parameters
      'no-duplicate-case': 'error',  // Duplicate switch cases
      'no-empty': 'error',  // Empty blocks (may be intentional)
      'no-ex-assign': 'error',  // Reassigning exception variable
      'no-func-assign': 'error',  // Reassigning function declarations
      'no-invalid-regexp': 'error',  // Invalid regex patterns
      'use-isnan': 'error',  // Require isNaN() for NaN checks
      'valid-typeof': 'error',  // Enforce valid typeof comparisons
      'no-self-assign': 'error',  // Catch x = x mistakes
      'no-cond-assign': ['error', 'except-parens'],  // No assignment in conditions (catch = vs ==)
      'no-fallthrough': 'error',  // Require break in switch cases

      // Code quality
      'no-irregular-whitespace': 'error',
      'no-unexpected-multiline': 'error',
      'no-useless-escape': 'error',
      'no-trailing-spaces': 'error',
      'eol-last': ['error', 'always'],
      'no-unused-vars': 'off'  // Too many intentional globals
    }
  },
  {
    files: ['test/**/*.js', 'test/**'],
    languageOptions: {
      sourceType: 'module',
      ecmaVersion: 'latest',
      globals: {
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly'
      }
    }
  },
  {
    files: ['scripts/**/*.js', 'scripts/**'],
    languageOptions: {
      sourceType: 'module',
      globals: {
        LOCK_DIR: 'writable',
        LOCK_PATH: 'writable',
        FIN_PATH: 'writable',
        HEARTBEAT_INTERVAL_MS: 'writable',
        STALE_MS: 'writable',
        GRACE_MS: 'writable',
        isPidAlive: 'writable',
        writeLock: 'writable',
        acquireLock: 'writable',
        releaseLock: 'writable',
        main: 'writable'
      }
    }
  }
];
