'use strict';

const REASONS = {
  STOP_WORK_DISMISSIVE:
    'STOP-WORK ANTIPATTERN: You responded with dismissive text instead of doing work. Re-read the user prompt and the conversation. There is always pending work after a user message -- find it and do it. If genuinely nothing remains, explain what was completed and why. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  STOP_WORK_TEXT_ONLY:
    'STOP-WORK ANTIPATTERN: Your last turn was a short text-only response with no tool calls. If there is remaining work, continue it now. If you genuinely completed everything, provide a substantive summary of what was done. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  EXHAUST:
    'EXHAUST PROTOCOL VIOLATION: Final text enumerated remaining items (TBD/noted/remaining tools) without fixing them. Every enumerated item must be fixed in the same turn. Resume and implement the highest-leverage items now. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  SCOPE_ESCAPE:
    'SCOPE-ESCAPE VIOLATION: Final text dismissed a problem by labeling it pre-existing / unrelated / not-introduced-here / out-of-scope-of-this-turn instead of fixing it. The rule is: if you saw it, fix it. "Pre-existing" is not a permission slip to skip work. Either (a) fix the problem in this turn, or (b) if fixing is genuinely wrong (e.g. would break an unrelated boundary), say so explicitly and explain why fixing is the wrong move -- do NOT just label-and-stop. The rescue clause "and I fixed it" / "now resolved" suppresses this gate, so the path forward is always to fix. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  SCOPE_STACKED:
    'SCOPE-STACKED ANTIPATTERN: New `- [ ]` items were added to doc/templates/TODO.md this turn but zero `[ ]` -> `[x]` transitions happened. Translation: you enumerated MORE work than you DID. TODO.md is growing faster than artifacts. Either (a) implement the highest-leverage new item right now and tick it, or (b) revert the TODO additions if they were premature scope-stacking. Naming work is not equivalent to shipping work. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  SCOPE_NOT_TRACKED:
    'SCOPE-NOT-TRACKED ANTIPATTERN: This turn made substantive Edit/Write/MultiEdit calls to non-TODO files but zero TODO items were ticked. Either (a) tick the TODO item(s) the work corresponds to, or (b) update TODO.md to reflect the new scope the work actually addressed. Work happening off declared scope is silent scope drift. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  EVASION_INTENT:
    'EVASION-INTENT ANTIPATTERN: Your thinking blocks contained explicit gate-evasion language (e.g. "avoid the structural check", "frame in prose to bypass", "stay under the threshold", "to avoid exhaust_check"). Gates exist to enforce the work. Routing around a gate IS routing around the work the gate enforces. Meet the gate intent honestly: either do the work the gate is asking for, or push back on the gate explicitly with a reason. Do NOT shape output to fall just under a threshold. Re-read the matched phrases via i/why mode=block. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  PHANTOM_CAPABILITY:
    'PHANTOM CAPABILITY: Your closing summary declared a thinking/delegation capability that is NOT in the closed enumeration at tools/HME/scripts/detectors/_capability_enum.py. Inventing generic labels ("decomposition", "tradeoff analysis", "deep reasoning") is a CRITICAL FAILURE -- it does NOT contribute to the tier floor. Either (a) replace the declaration with a verbatim name from the enumeration, (b) anchor the declaration with verification evidence (`(verified)`, code-quoted output, tool-call trace) within 240 chars after the name, or (c) drop the declaration. New capabilities are added by editing _capability_enum.py and bumping ENUMERATION_VERSION -- never by ad-hoc invention at run time. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  PHANTOM_PARAPHRASE:
    'PHANTOM PARAPHRASE (soft): Your text contained a paraphrase of a real capability (e.g. "first-principles decomposition" instead of "FirstPrinciples"). This is the shape of an agent reaching for an enumeration name without committing. Rewrite using the verbatim name from _capability_enum.py, OR drop the language if you did not actually invoke that capability. Soft flag -- does not block, but the meta-detector tracks the rate. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  ADVISOR_MISSING_PRE_BUILD:
    'ADVISOR DOCTRINE (legacy): Tier >= E2 work just hit a BUILD/commit boundary without an advisor record. The legacy advisor toolchain has been removed; either continue with the work and state the solo rationale, or escalate to the user if real external review is needed. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  ADVISOR_MISSING_POST_DELIVER:
    'ADVISOR DOCTRINE (legacy): A durable deliverable landed without an advisor record. The legacy advisor toolchain has been removed; either continue with the work and state the solo rationale, or escalate to the user if real external review is needed. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  ADVISOR_SILENTLY_SKIPPED:
    'ADVISOR DOCTRINE (legacy E4/E5 floor): Tier >= E4 work completed with no advisor record and no solo-rationale clause. The legacy advisor toolchain has been removed; continue with the work, state why solo execution is appropriate, or escalate to the user if review is truly needed. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  ADVISOR_CONFLICT_CAP:
    'ADVISOR DOCTRINE (Rule 3 -- conflict cap): The advisor was re-called more than 2 times on the same conflict_id (see tmp/hme-advisor-conflicts.jsonl). Hard cap exceeded. Escalate to the user instead of re-calling -- keep the loop bounded. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  SUMMARY_MISSING:
    'STOP-THE-LINE FORMAT VIOLATION: Tier E5 (Comprehensive) work closed without the required SUMMARY block. Append the closing block before stopping. Required fields: [ITERATION], [CONTENT], [STORY] (4 bullets: problem | what we did | how it went | what\'s next), and [VOICE] <name>: <8-16 word summary>. Either (a) emit the block now, or (b) re-classify the tier -- if no summary is needed, this work was lighter than E5 and the classifier should reflect that. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  SUMMARY_MALFORMED:
    'STOP-THE-LINE FORMAT VIOLATION: Closing summary block is present but missing required fields. Every E5 turn must include all 7 elements: SUMMARY banner, [ITERATION]:, [CONTENT]:, [STORY]: with all 4 bullets (problem, what we did, how it went, what\'s next), and [VOICE] <name>: <8-16 word closing line>. Re-emit the block with every field populated. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  PHASE_SKIPPED:
    'PHASE GATE VIOLATION: Tier >= E3 (Algorithm) work made Edit/Write/MultiEdit calls this turn without declaring a BUILD or EXECUTE phase first. The 7-phase loop (OBSERVE -> THINK -> PLAN -> BUILD -> EXECUTE -> VERIFY -> LEARN) requires explicit transition markers so the design intent is articulated before code lands. Either (a) emit "BUILD" or "phase: build" in your text before the next edit, or (b) re-classify the tier -- if no PLAN ceremony is needed, this work was lighter than E3. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  MINIMAL_FORMAT_VIOLATION:
    'MINIMAL MODE FORMAT VIOLATION: The classifier detected a MINIMAL-mode prompt (one-line acknowledgment expected) but your response was long-form OR carried an ALGORITHM-style SUMMARY block. Match the mode: terse one-liner, no boilerplate. If the work was actually substantive (warranting NATIVE/ALGORITHM), ask the classifier to re-evaluate or escalate the tier explicitly. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  PILE_ON:
    'PILE-ON ANTIPATTERN: This turn edited 2+ detector / policy / hook files. Endless rule-stacking is itself the failure mode -- each detector firing produces another rule edit, each rule edit creates new firings, the cycle accumulates ceremony without resolving the underlying issue. STOP editing detectors. The fix for a noisy detector firing is rarely another rule; usually the right move is discretion (let the imperfect rule fire, continue the actual work). If a real detector bug exists, fix THAT specific bug and stop -- do not also tighten three neighboring detectors in the same turn. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  FLABBERGASTED_BY_AUTOCOMMIT:
    'FLABBERGASTED_BY_AUTOCOMMIT: Autocommit already consumed the diff, but the transcript kept probing clean git status/diff/log output. Do not spiral on where the diff went. Trust the autocommit evidence, inspect once if needed, verify the actual artifact, then stop.',
  CLAIM_WITHOUT_EVIDENCE:
    "VERIFICATION DOCTRINE (Iron Law): Final text claimed completion (`tests pass`, `lands`, `live at`, `now works`, `verified`, etc.) WITHOUT a same-turn evidence-producing tool call. Claim without verification is dishonesty, not efficiency. Either (a) run the verification command NOW (Bash test/curl/build/probe, or Read of the claimed-modified file) and re-emit the claim WITH the evidence inline, or (b) drop the claim language and state actual status (e.g. `code change made; not yet verified`). The phrase `should pass`, `probably works`, or `looks correct` is also a violation -- evidence before claims, always. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.",
  NEXT_ACTION_DEBT:
    'NEXT-ACTION DEBT: Final text admitted remaining work with next-action / next-step language. Do not stop after naming the next action. Execute it now, or explicitly mark it impossible/blocked with evidence and ask the user. Acknowledging the gap is not repair.',
  WORK_DEBT_ADMISSION:
    'WORK-DEBT ADMISSION: Final text admitted incomplete/remaining/pending work, enumerated work to do, or dispatched work into a future step instead of executing it. This is a hard stop: do the named work now, or explicitly prove it is impossible/unsafe with evidence and ask the user. Acknowledgement and enumeration are not work.',
  UNFINISHED_TASKS:
    'UNFINISHED TASK-LIST VIOLATION: The active task list still contains pending or in_progress items. Do not end the turn with open tasks. Complete them now, or if a task is genuinely obsolete, update/delete it with an explicit task tool before stopping. Acknowledgement text is not completion evidence.',
  FIX_WITHOUT_INVESTIGATION:
    'SYSTEMATIC-DEBUGGING PHASE GATE: User reported a bug / broken behavior / failure, and your turn made Edit/Write/MultiEdit calls WITHOUT a prior investigation-shape tool call (Read/Grep/Glob/Bash with grep/cat/log/git-diff/i-status/curl-health/etc.). NO FIXES WITHOUT ROOT CAUSE INVESTIGATION FIRST. The fastest path to a real fix is: reproduce the symptom, trace the causal chain, identify the failing component, THEN edit. Skipping straight to a guessed fix produces symptom-patching (the next bug surfaces in the same area within hours). Either (a) investigate now -- read the relevant logs/code/state, then propose the fix with the causal chain stated, or (b) explicitly note this was a one-line obvious fix (typo, clear stack-trace pointer) where investigation would be ceremony. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  COMMENT_BLOAT:
    'COMMENT-BLOAT VIOLATION (doc/templates/AGENTS.md): A file you edited this turn contains a 5+ line consecutive inline-comment block. Rule: "Inline comments single-line and terse. Elaboration goes in doc/." Trim the block to <=2 lines OR move the explanation into doc/. Run `python3 tools/HME/scripts/audit-comment-bloat.py --files <path>` to see the offending blocks. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  BOYSCOUT_LOC:
    'LOC LIMIT VIOLATION (doc/templates/AGENTS.md): A file you Edited/Wrote this turn exceeds 350 LOC and is not in config/loc-ignore.txt. Rule: "Files MUST be <=350 LOC unless listed in loc-ignore.txt. Organize at logical boundaries." Either split the file, OR add to loc-ignore.txt with rationale. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  BOYSCOUT_CLEAN:
    'BOYSCOUT CLEAN-ROOM VIOLATION: A file you Edited/Wrote this turn still has audit violations. Every edited file must be left with ZERO errors (comment-bloat or char-spam). Fix the violations in the file(s) you touched this turn. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  ORPHAN_REFERENCE:
    'ORPHAN REFERENCE: A file you DELETED this turn still has live references in source/scripts/docs. Sweep them: `grep -rln <stem> tools/ scripts/ src/ doc/` then either remove the references or restore the file. Deletion-without-cleanup is the bug class that produces broken imports / dead require paths / stale doc links. If the work is actually done and there is nothing left, silence is the correct response -- do NOT write ceremony text to dodge this gate.',
  COMPL_ROUND_1:
    "AUTO-COMPLETENESS CHECK (round 1/2): If anything substantive is still unfinished from THIS TURN's work, finish it. If the work is complete, the next response may be empty or just the fp-gate marker when prompted. Do NOT write ceremony text, enumerated 'nothing missed' summaries, or rescue clauses just to satisfy this gate. Imperfect rules are OK; ceremony to dodge them is not.",
  COMPL_ROUND_2:
    "AUTO-COMPLETENESS CHECK (round 2/2 -- safety net): Last pass. If genuine substantive work remains, do it. If complete, the next response may be empty or just the fp-gate marker when prompted. No 'Nothing missed' boilerplate required.",
};

module.exports = { REASONS };
