pipelineCouplingManagerConfig = (() => {
  const NUDGEABLE = ['density', 'tension', 'flicker'];

  return {
    NUDGEABLE,
    NUDGEABLE_SET: new Set(NUDGEABLE),
    NON_NUDGEABLE_SET: new Set(['entropy-trust', 'entropy-phase', 'trust-phase']),
    PHASE_SURFACE_SET: new Set(['density-phase', 'flicker-phase', 'tension-phase']),
    ENTROPY_SURFACE_SET: new Set(['density-entropy', 'tension-entropy', 'flicker-entropy', 'entropy-trust', 'entropy-phase']),
    COMPOSITIONAL_DIMS: ['density', 'tension', 'flicker', 'entropy'],
    OBSERVABLE_DIMS: ['trust', 'phase'],
    ALL_MONITORED_DIMS: ['density', 'tension', 'flicker', 'entropy', 'trust', 'phase'],
    DEFAULT_TARGET: 0.25,
    PAIR_TARGETS: {
      'density-tension': 0.15,
      'density-flicker': 0.12,
      'density-entropy': 0.12,
      'tension-flicker': 0.15,
      'tension-entropy': 0.25,
      'flicker-entropy': 0.18,
      'flicker-phase': 0.08,
      'density-phase': 0.06,
      'tension-phase': 0.20,
      'density-trust': 0.20,
      'tension-trust': 0.15,
      'flicker-trust': 0.12,
      'entropy-phase': 0.10,
      'entropy-trust': 0.30,
      'trust-phase': 0.25,
    },
    TARGET_ADAPT_EMA: 0.02,
    TARGET_RELAX_RATE: 0.0015,
    TARGET_TIGHTEN_RATE: 0.0015,
    TARGET_MIN: -0.05,
    TARGET_MAX: 0.45,
    DENSITY_FLICKER_TARGET_MAX: 0.55,
    AXIS_COUPLING_CEILING: {
      density: 2.0,
      tension: 2.0,
      flicker: 2.0,
      entropy: 2.0,
      trust: 2.5,
      phase: 2.0,
    },
    AXIS_SMOOTH_ALPHA: 0.15,
    GAIN_INIT: 0.16,
    GAIN_MIN: 0.08,
    GAIN_MAX: 0.60,
    GAIN_ESCALATE_RATE: 0.02,
    GAIN_EMERGENCY_RATE: 0.06,
    GAIN_RELAX_RATE: 0.02,
    PAIR_GAIN_INIT: {
      'density-tension': 0.24,
    },
    COHERENT_SHARE_EMA_ALPHA: 0.015,
    AXIS_BUDGET: 0.24,
    FLICKER_PAIR_GAIN_CAP: 0.45,
    FLICKER_PAIR_GAIN_CAP_THRESHOLD: 0.88,
    DENSITY_PAIR_GAIN_CAP: 0.45,
    DENSITY_PAIR_GAIN_CAP_THRESHOLD: 0.72,
    BUDGET_PRIORITY_GAIN: {
      'density-flicker': 1.75,
      'density-entropy': 1.28,
      'density-phase': 1.35,
      'density-trust': 1.25,
      'flicker-entropy': 1.42,
      'flicker-phase': 1.45,
      'flicker-trust': 1.25,
      'tension-entropy': 1.18,
      'tension-phase': 1.15,
      'tension-flicker': 1.10,
      'tension-trust': 1.10,
    },
    BUDGET_DEPRIORITIZED_GAIN: 0.82,
    BUDGET_PRIORITY_TOP_K: 5,
    VELOCITY_EMA_ALPHA: 0.08,
    VELOCITY_TRIGGER_RATIO: 2.0,
    VELOCITY_BOOST_BEATS: 3,
    VELOCITY_GAIN_BOOST: 2.0,
    GATE_EMA_ALPHA: 0.05,
    HP_GAIN_MAX: 0.80,
    HP_ROLLING_THRESHOLD: 0.35,
    HP_MAX_BEATS: 50,
    HP_COOLDOWN_BEATS: 30,
    MONOTONE_TRIGGER: 22,
    HIGH_CORR_MONOTONE_TRIGGER: 16,
    MONOTONE_ABS_THRESHOLD: 0.50,
    MONOTONE_IMPULSE_RATE: 2.5,
    P95_WINDOW: 16,
    TELEMETRY_WINDOW: 96,
  };
})();
