#!/usr/bin/env python3
"""CheckpointPerISC auto-commit hook -- PAI v6.3.0 import #6.

Fires when an ISC transitions [ ]->[x]. For each opted-in ISA, every
verified-criterion transition triggers an atomic git commit so a
multi-criterion task lays down one commit per criterion rather than one
turn-grained commit at the end.

Sidecar state lives at `<isa_dir>/.checkpoint-state.json` and records
each ISC's last-known status + the commit SHA created at transition
time. Idempotent: if the state already records `[x]` for an ISC, no
new commit fires.

Allowlist: ISA frontmatter must contain `checkpoint: enabled` for the
hook to act on it. Default opt-out -- this is a deliberate gate so old
ISAs don't suddenly start auto-committing.

Fail-closed: any unexpected error (no git, no ISA, parse failure,
allowlist mismatch) returns 0 without committing. The point is to fire
extra commits when conditions are clean, NEVER to interfere with the
agent's own commit cadence on borderline state.

Usage:
    checkpoint_hook.py <isa_path>
    checkpoint_hook.py --scan       # walk tmp/isa/*/ISA.md
    checkpoint_hook.py --dry-run <isa_path>
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from isa_lib import parse_isa, ParsedISA  # noqa: E402

_HERE = Path(__file__).resolve().parent
_PROJECT = Path(os.environ.get("PROJECT_ROOT") or _HERE.parent.parent.parent.parent)


def _utc_now() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _is_opted_in(isa: ParsedISA) -> bool:
    """ISA frontmatter `checkpoint: enabled` is the opt-in. Any other
    value (or missing key) means the hook leaves this ISA alone."""
    return isa.frontmatter.get("checkpoint", "").lower() == "enabled"


def _load_state(state_file: Path) -> dict:
    if not state_file.is_file():
        return {}
    try:
        return json.loads(state_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _save_state(state_file: Path, state: dict) -> None:
    state_file.parent.mkdir(parents=True, exist_ok=True)
    tmp = state_file.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")
    tmp.replace(state_file)


def _has_uncommitted_changes(repo: Path) -> bool:
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), "status", "--porcelain"],
            capture_output=True, text=True, timeout=5, check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return bool(out.stdout.strip())


def _create_checkpoint_commit(repo: Path, slug: str, isc_ids: list[str],
                              dry_run: bool = False) -> str | None:
    """Stage all working-tree changes and create one checkpoint commit
    referencing the ISC ids that just transitioned. Returns the new
    commit SHA, or None on failure / dry-run."""
    msg_lines = [
        f"checkpoint: {slug}",
        "",
        f"Auto-commit triggered by [ ]->[x] transition on:",
    ]
    for isc_id in isc_ids:
        msg_lines.append(f"  - {isc_id}")
    msg_lines += ["", "Generated by tools/HME/scripts/isa/checkpoint_hook.py."]
    msg = "\n".join(msg_lines)

    if dry_run:
        print(f"[dry-run] would commit in {repo} with message:")
        print(msg)
        return None
    try:
        subprocess.run(
            ["git", "-C", str(repo), "add", "-A"],
            check=True, capture_output=True, timeout=10,
        )
        subprocess.run(
            ["git", "-C", str(repo), "commit", "-m", msg, "--no-verify"],
            check=True, capture_output=True, timeout=15,
        )
        # --no-verify is intentional here: pre-commit hooks live elsewhere
        sha = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
            check=True, capture_output=True, text=True, timeout=5,
        ).stdout.strip()
        return sha
    except (OSError, subprocess.SubprocessError):
        return None


def process_isa(isa_path: Path, dry_run: bool = False) -> dict:
    """Inspect one ISA, find new [ ]->[x] transitions vs. saved state,
    create a checkpoint commit if any. Returns a result dict for
    reporting."""
    result = {"path": str(isa_path), "skipped": None, "transitions": [],
              "committed": None}
    try:
        isa = parse_isa(isa_path)
    except FileNotFoundError as e:
        result["skipped"] = f"parse failed: {e}"
        return result

    if not _is_opted_in(isa):
        result["skipped"] = "not opted in (frontmatter checkpoint != enabled)"
        return result

    state_file = isa_path.parent / ".checkpoint-state.json"
    state = _load_state(state_file)

    new_transitions: list[str] = []
    for isc in isa.iscs:
        prev = state.get(isc.id, {})
        prev_status = prev.get("status", "[ ]")
        if prev_status == "[ ]" and isc.status == "[x]" and not isc.is_tombstone:
            new_transitions.append(isc.id)

    if not new_transitions:
        result["skipped"] = "no new [ ]->[x] transitions"
        return result

    result["transitions"] = new_transitions

    if not _has_uncommitted_changes(_PROJECT):
        result["skipped"] = "no uncommitted changes to checkpoint"
        # Still update state to record verified status so we don't
        # repeatedly try to commit nothing.
        for isc_id in new_transitions:
            state[isc_id] = {"status": "[x]", "sha": None, "ts": _utc_now()}
        if not dry_run:
            _save_state(state_file, state)
        return result

    slug = isa.frontmatter.get("name", isa_path.parent.name)
    sha = _create_checkpoint_commit(_PROJECT, slug, new_transitions, dry_run)
    if sha is None and not dry_run:
        result["skipped"] = "commit failed (see git stderr)"
        return result

    result["committed"] = sha
    for isc_id in new_transitions:
        state[isc_id] = {"status": "[x]", "sha": sha, "ts": _utc_now()}
    if not dry_run:
        _save_state(state_file, state)
    return result


def main(argv: list) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("isa", nargs="?", help="path to ISA.md (omit with --scan)")
    p.add_argument("--scan", action="store_true",
                   help="walk tmp/isa/*/ISA.md instead of taking a single path")
    p.add_argument("--dry-run", action="store_true",
                   help="report transitions but do not commit / write state")
    args = p.parse_args(argv)

    paths: list[Path] = []
    if args.scan:
        scan_root = _PROJECT / "tmp" / "isa"
        if scan_root.is_dir():
            paths = sorted(scan_root.glob("*/ISA.md"))
    elif args.isa:
        paths = [Path(args.isa)]
    else:
        sys.stderr.write("checkpoint_hook: pass an ISA path or --scan\n")
        return 2

    if not paths:
        return 0

    for path in paths:
        r = process_isa(path, dry_run=args.dry_run)
        if r["transitions"]:
            ids = ", ".join(r["transitions"])
            if r["committed"]:
                print(f"checkpoint {path}: committed {r['committed']} for {ids}")
            elif r["skipped"]:
                print(f"checkpoint {path}: {r['skipped']} ({ids})")
        elif r["skipped"] and r["skipped"] != "not opted in (frontmatter checkpoint != enabled)":
            # Skipped opt-out is silent (frequent, no signal). Other skips
            # surface so opt-in misconfigurations are visible.
            print(f"checkpoint {path}: {r['skipped']}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
