// Aggregated entry point for the src/time modules.

// @ts-ignore: side-effect module load
require('./LayerManager');
// @ts-ignore: side-effect module load
require('./midiTiming');
// @ts-ignore: side-effect module load
require('./setUnitTiming');
// @ts-ignore: pre-computed polyrhythm alignment table (generated by scripts/generatePolyrhythmTable.js)
require('./polyrhythmPairs');
// @ts-ignore: legacy meter picker (still declared in globals.d.ts for compatibility)
require('./getPolyrhythm');
// @ts-ignore: table-driven meter pair picker (replaces getMeter + getPolyrhythm)
require('./getMeterPair');
// @ts-ignore: side-effect module load
require('./timeGridHelpers');
// @ts-ignore: side-effect module load
require('./absoluteTimeWindow');
// @ts-ignore: side-effect module load
require('./absoluteTimeGrid');
// @ts-ignore: side-effect module load
require('./tempoFeelEngine');
// @ts-ignore: side-effect module load
require('./timeStream');
// @ts-ignore: fractal arc generator (multi-scale arc embedding)
require('./fractalArcGenerator');
