// Canonical L0 channel name registry.
// All L0.post/getLast/query/count/getBounds/findClosest calls must use
// L0_CHANNELS.xxx instead of bare string literals (ESLint-enforced).

L0_CHANNELS = Object.freeze({
  articulation: 'articulation',
  binaural: 'binaural',
  cadenceAlignment: 'cadenceAlignment',
  channelCoherence: 'channel-coherence',
  chord: 'chord',
  climaxPressure: 'climax-pressure',
  coherence: 'coherence',
  convergenceDensity: 'convergence-density',
  density: 'density',
  densityRhythm: 'density-rhythm',
  emergentDownbeat: 'emergentDownbeat',
  emergentMelody: 'emergentMelody',
  emergentRhythm: 'emergentRhythm',
  emissionDelta: 'emissionDelta',
  entropy: 'entropy',
  feedbackLoop: 'feedbackLoop',
  feedbackPitch: 'feedbackPitch',
  grooveTransfer: 'grooveTransfer',
  interactionHeat: 'interactionHeat',
  harmonic: 'harmonic',
  harmonicFunction: 'harmonicFunction',
  harmonicJourneyEval: 'harmonic-journey-eval',
  instrument: 'instrument',
  motifEcho: 'motifEcho',
  motifIdentity: 'motifIdentity',
  note: 'note',
  onset: 'onset',
  perceptualCrowding: 'perceptual-crowding',
  phaseConvergence: 'phaseConvergence',
  registerCollision: 'registerCollision',
  regimeTransition: 'regimeTransition',
  restSync: 'rest-sync',
  rhythm: 'rhythm',
  sectionQuality: 'section-quality',
  selfNarration: 'self-narration',
  spectral: 'spectral',
  swapDecision: 'swapDecision',
  stutterContagion: 'stutterContagion',
  tension: 'tension',
  tickDuration: 'tickDuration',
  underusedPitchClasses: 'underusedPitchClasses',
  velocity: 'velocity',
  verticalCollision: 'verticalCollision',
});
