// fullBootstrap.js - AUTO-GENERATED from src/types/globals.d.ts by scripts/generate-globals-dts.js (runs automatically at the start of `npm run main`).
// To add a new validated global: edit globals.d.ts only.

moduleLifecycle.declare({
  name: 'fullBootstrap',
  subsystem: 'play',
  deps: [],
  provides: ['fullBootstrap'],
  init: () => {
  /**
   * AUTO-GENERATED from src/types/globals.d.ts - do not edit by hand.
   * Every name in this set is proven-defined by mainBootstrap.assertBootstrapGlobals()
   * before any composition code runs. Typeof-probing these downstream is redundant
   * and banned by the `local/no-typeof-validated-global` ESLint rule.
   */
  const VALIDATED_GLOBALS = Object.freeze([
    // -- Abbreviation Glossary --

    // -- Core Interface Types --

    // -- Explainability / Trust / Coherence --

    // -- Conductor subsystem objects --

    // -- System Dynamics Profiler (phase --

    // -- Time subsystem --

    // -- Lifecycle / caching utilities --

    // -- eventCatalog --

    // -- trustSystems --

    // -- metaControllerRegistry --

    // -- crossLayerEmissionGateway --

    // -- Cross --

    // -- Rhythm / Time / Composer Interfaces --

    // -- Conductor / Composer / FX Class Interfaces --

    // -- Profile record shapes --

    // -- Config accessor APIs --

    // -- Feedback infrastructure --

    // -- Conductor intelligence module APIs --

    // -- utils --
    'm',
    'rf',
    'ri',
    'rw',
    'ra',
    'rv',
    'rl',
    'clamp',
    'modClamp',
    'lowModClamp',
    'highModClamp',
    'scaleClamp',
    'scaleBoundClamp',
    'fuzzyClamp',
    'stepClamp',
    'logClamp',
    'expClamp',
    'randomWeightedInArray',
    'randomWeightedSelection',
    'normalizeWeights',
    'MIDI_MAX_VALUE',
    'midiData',
    'getMidiValue',
    'allCHs',
    'allNotes',
    'allScales',
    'allChords',
    'allModes',
    'cCH1',
    'source',
    'source2',
    'reflection',
    'bass',
    'rlFX',
    'setTuningAndInstruments',
    'stutterFadeCHs',
    'stutterPanCHs',
    'chFX',
    'flipBinT',
    'flipBinF',
    'flipBinT3',
    'flipBinF3',
    'flipBinF2',
    'flipBinT2',
    'reflectionBinaural',
    'reflect',
    'reflect2',
    'binauralL',
    'binauralR',
    'binauralOffset',
    'bassBinaural',
    'crossModulation',
    'lastMeter',
    'lastUsedCHs',
    'lastUsedCHs2',
    'lastUsedCHs3',
    'remainingVoiceSlotsByLayer',
    'lastVoiceBudgetKeyByLayer',
    'neutralPitchBend',
    'semitone',
    'tuningPitchBend',
    'FX',
    'COMPOSER_TYPE_PROFILE_SOURCES',
    'allNotesOff',
    'muteAll',
    'setOtherInstruments',
    'validator',
    'systemSnapshot',
    'modeQualityMap',
    'priorsHelpers',

    // -- conductor --
    'BPM',
    'PPQ',
    'currentDensity',
    'TUNING_FREQ',
    'LOG',
    'BINAURAL',
    'SILENT_OUTRO_SECONDS',
    'SECTIONS',
    'PHRASES_PER_SECTION',
    'NUMERATOR',
    'DENOMINATOR',
    'DIVISIONS',
    'SUBDIVS',
    'VOICES',
    'BEAT_VOICES',
    'DIV_VOICES',
    'SUBDIV_VOICES',
    'SUBSUBDIV_VOICES',
    'BEAT_SIBLING_VOICES',
    'DIV_SIBLING_VOICES',
    'SUBDIV_SIBLING_VOICES',
    'SUBSUBDIV_SIBLING_VOICES',
    'OCTAVE',
    'primaryInstrument',
    'secondaryInstrument',
    'otherInstruments',
    'bassInstrument',
    'bassInstrument2',
    'otherBassInstruments',
    'drumSets',
    'PhraseArcManager',
    'VOICE_PROFILES',
    'CHORD_PROFILES',
    'MOTIF_PROFILES',
    'RHYTHM_PROFILES',
    'RHYTHM_PATTERNS',
    'RHYTHM_PATTERN_POOLS',
    'DRUM_MAP',
    'FX_CC_DEFAULTS',
    'NOISE_GENERATOR_REGISTRY',
    'PHRASES_ARC_CURVES',
    'MODAL_BORROWING',
    'NOISE_PROFILES',
    'COMPOSER_FAMILIES',
    'VOICE_MANAGER',
    'SECTION_TYPES',
    'SUBSUBDIVS',
    'DYNAMISM',
    'STUTTER_PROFILES',
    'STUTTER_VELOCITY_RANGES',
    'STUTTER_CROSSMOD_RULES',
    'STUTTER_CROSSMOD_RULES_FALLBACK',
    'STUTTER_PRESETS',
    'STUTTER_DIRECTIVE_DEFAULTS',
    'MOTIF_UNIT_PROFILES',
    'CONDUCTOR_DYNAMICS_CONTROLS',
    'MAIN_LOOP_CONTROLS',
    'CONDUCTOR_NOISE_PROFILE_BY_PHASE',
    'CONDUCTOR_PROFILE_SOURCES',
    'conductorProfileDefault',
    'conductorProfileRestrained',
    'conductorProfileExplosive',
    'conductorProfileAtmospheric',
    'conductorProfileRhythmicDrive',
    'conductorProfileMinimal',
    'conductorConfigTuningDefaults',
    'conductorConfigTuningOverrides',
    'conductorConfigMergeProfileTuning',
    'conductorConfigValidateProfile',
    'conductorConfigDynamics',
    'conductorConfigResolvers',
    'conductorConfigAccessors',
    'ACTIVE_META_PROFILE',
    'propertyExtractors',
    'moduleLifecycle',
    'feedbackRegistry',
    'closedLoopController',
    'beatCache',

    // -- rhythm --
    'rhythmRegistry',
    'RhythmManager',
    'rhythmValues',
    'rhythmConfig',
    'rhythmModulator',
    'RHYTHM_PRIOR_TABLES',
    'rhythmPriors',
    'setRhythm',
    '_rp',
    '_binary',
    '_random',
    'rotate',
    'lastCrossMod',
    'playDrums',
    'playDrums2',
    'binary',
    'hex',
    'onsets',
    'random',
    'prob',
    'euclid',
    'morph',
    'closestDivisor',
    'rhythmMethods',
    'makeOnsets',
    'patternLength',
    'drumMap',
    'drummer',
    'getRhythm',
    'rhythms',
    'trackRhythm',
    'crossModulateRhythms',

    // -- time --
    'bpmRatio',
    'bpmRatio2',
    'bpmRatio3',
    'numerator',
    'denominator',
    'meterRatio',
    'beatRhythm',
    'divRhythm',
    'subdivRhythm',
    'subsubdivRhythm',
    'measuresPerPhrase1',
    'measuresPerPhrase2',
    'measureStartTime',
    'beatStartTime',
    'divStartTime',
    'subdivStartTime',
    'subsubdivStartTime',
    'c',
    'LM',
    'setBpm',
    'setMeter',
    'deepFreeze',
    'regimeDispatch',
    'POLYRHYTHM_PAIRS',
    'getPolyrhythm',
    'setUnitTiming',
    'bestMatch',
    'subsubsPerSub',
    'spUnit',
    'unitIndex',
    'unitStartTime',
    'spParent',
    'unitsPerParent',
    'spPhrase',
    'phraseStartTime',
    'spSection',
    'sectionStartTime',
    'spMeasure',
    'spBeat',
    'subdivsPerMinute',
    'subsubsPerMinute',
    'subdivFreq',
    'divsPerBeat',
    'subdivsPerDiv',
    'spDiv',
    'spSubdiv',
    'spSubsubdiv',
    'trueBPM',
    'trueBPM2',
    'polyMeterRatio',
    'midiMeter',
    'midiMeterRatio',
    'midiBPM',
    'syncFactor',
    'timeGridSearchStart',
    'L0_CHANNELS',

    // -- composers --
    'normalizeChordSymbol',
    'MeasureComposer',
    'ScaleComposer',
    'RandomScaleComposer',
    'ChordComposer',
    'RandomChordComposer',
    'ModeComposer',
    'RandomModeComposer',
    'TensionReleaseComposer',
    'ModalInterchangeComposer',
    'HarmonicRhythmComposer',
    'melodicDevelopmentVoicingIntent',
    'MelodicDevelopmentComposer',
    'VoiceLeadingComposer',
    'MotifComposer',
    'Motif',
    'motifTransforms',
    'measureNotePool',
    'motifValidators',
    'registerBiasing',
    'candidateExpansion',
    'playMotifs',
    'playMotifsResolveBucket',
    'playMotifsBuildCandidateNotes',
    'playMotifsApplyCycleTransforms',
    'PentatonicComposer',
    'RandomPentatonicComposer',
    'BluesComposer',
    'RandomBluesComposer',
    'ChromaticComposer',
    'RandomChromaticComposer',
    'QuartalComposer',
    'RandomQuartalComposer',
    'intervalComposer',
    'factoryProfiles',
    'factoryProgression',
    'factoryPoolResolver',
    'factoryFamilies',
    'factoryConstructors',
    'ProgressionGenerator',
    'HARMONIC_PRIOR_TABLES',
    'harmonicPriors',
    'chordRegistry',
    'ChordManager',
    'chordValues',
    'chordConfig',
    'chordModulator',
    'motifRegistry',
    'motifManager',
    'motifValues',
    'motifConfig',
    'motifModulator',
    'voiceRegistry',
    'voiceValues',
    'voiceConfig',
    'voiceModulator',
    'voiceLeadingScorers',
    'voiceLeadingCore',
    'VOICE_LEADING_PRIOR_TABLES',
    'voiceLeadingPriors',
    'MELODIC_PRIOR_TABLES',
    'melodicPriors',
    'voiceLeadingSelectNextNote',
    'voiceLeadingAnalyzeQuality',
    'VoiceManager',
    'getScheduledNotes',
    'p',
    'note',
    'applyComposerPitchNoise',
    'applyMelodicTranspositionNoise',
    'assertComposerCapabilities',
    'resolveScalePC',
    'midiToDegree',
    'degreeToMidi',
    'transposeByDegree',
    'scaleNormalization',
    'scaleDegreeTranspose',
    'applyMelodicPivotNoise',
    'applyMelodicDurationNoise',
    'applyVoiceLeadingWeightNoise',
    'activeMotif',
    'main',
    'composerProfileUtils',
    'composerProfileValidation',
    'COMPOSER_TYPES',
    'composerRuntimeProfileAdapter',
    'COMPOSER_PROFILE_POOLS',
    'COMPOSER_POOL_SELECTION_STRATEGY',
    'COMPOSER_TYPE_PROFILES',
    'selectComposerPoolOrFail',
    'getComposerPoolOrFail',
    'getDefaultComposerPoolOrFail',
    'getComposerTypeProfilesOrFail',
    'getComposerTypeProfileOrFail',
    'motifSpreader',
    'applyMotifToNotes',

    // -- fx --
    'lBal',
    'rBal',
    'cBal',
    'refVar',
    'bassVar',
    'balOffset',
    'stutterFade',
    'stutterPan',
    'stutterFX',
    'stutterExecutePlan',
    'stutterNotes',
    'pickStutterChannels',
    'selectMirrorChannels',
    'stutterRegistry',
    'stutterMetrics',
    'stutterConfig',
    'StutterManager',
    'setBalanceAndFX',
    'setBinaural',
    'flipBinCrossfadeWindow',
    'fbm',
    'turbulence',
    'ridged',
    'worley',
    'easeInOut',
    'easingFunctions',
    'noiseFunctions',
    'metaRecursiveEaseNoise',
    'metaRecursiveNoise',
    'metaRecursiveSimplex2D',
    'metaRecursiveFBM',
    'permutation',
    'fade',
    'lerp',
    'grad',
    'perlinNoise',
    'defaultSimplex',
    'noiseGenerators',
    'generatorKeys',
    'getNoiseValue',
    'layeredNoise',
    'createNoiseOffset',
    'randomNoiseGenerator',
    'noiseInfluenceMap',
    'createDualAxisNoiseConfig',
    'applyDualAxisNoise',
    'safeApplyNoise',
    'clampNoiseValue',
    'getParameterModulation',
    'smoothNoiseValue',
    'getNoiseProfile',
    'registerNoiseGenerator',
    'applyNoiseToVelocity',
    'applyNoiseToPan',
    'applyNoiseToSustain',
    'applyNoiseToParameter',
    'getNoiseProfileOrFail',
    'flipBin',
    'binauralFreqOffset',
    'beatCount',
    'sideBias',

    // -- crossLayer --
    't',
    'musicalTimeWindows',

    // -- writer --
    'formatTime',
    'logUnit',
    'pushMultiple',
    'grandFinale',

    // -- typed constructors (canonical declarations --
    'VoiceLeadingScore',
    'SimplexNoise',
    'FactoryManager',

    // -- node / timing --
    'fs',
    'path',
    'METRICS_DIR',
    'minMidi',
    'maxMidi',
    'channelStateField',
    'endTime',

    // -- play --
    'eventCatalog',
    'trustSystems',
    'safePreBoot',
    'traceSummaryData',
    'telemetryHealthData',
    'totalSections',
    'phrasesPerSection',
    'measuresPerPhrase',
    'getChannelCoherence',
    'playNotesComputeUnit',
    'playNotes',
    'composer',
    'remainingVoiceSlots',
    'lastVoiceBudgetKey',
    'velocity',
    'crossLayerBeatRecord',
    'processBeat',
    'playNotesEmitPick',
    'setFeedbackPitchBias',
    'setFeedbackStutterEnergy',
    'setClimaxMods',
    'emitPickCrossLayerRecord',
    'emitPickSourceTextures',
    'emitPickReflectionTextures',

    // -- other --
    'randomFloat',
    'randomInt',
    'randomWeightedInRange',
    'randomInRangeOrArray',
    'randomLimitedChange',
    'randomVariation',
    'sectionIndex',
    'phraseIndex',
    'measureIndex',
    'beatIndex',
    'divIndex',
    'subdivIndex',
    'subsubdivIndex',
    'measureCount',
    'c1',
    'c2',
    'layerManager',
    'cCH2',
    'cCH3',
    'lCH1',
    'lCH2',
    'lCH3',
    'lCH4',
    'lCH5',
    'lCH6',
    'rCH1',
    'rCH2',
    'rCH3',
    'rCH4',
    'rCH5',
    'rCH6',
    'drumCH',
    'cBal2',
    'cBal3',
    '_hex',
    '_onsets',
    '_probability',
    '_euclid',
    '_rotate',
    'binauralPlus',
    'binauralMinus',
    'beatsOn',
    'beatsOff',
    'divsOn',
    'divsOff',
    'subdivsOn',
    'subdivsOff',
    'subsubdivsOn',
    'subsubdivsOff',
    'finalTime',
    'subdivsPerBeat',
    'noteCount',
    'firstLoop',
    'currentSectionType',
    'currentSectionDynamics',
    'sectionBpmScale',
    'fxEventTemplate',
    'sectionEnd',
    'polyNumerator',
    'polyDenominator',
    'FXFeedbackListener',
    'L0',
    'accentPatternTracker',
    'adaptiveTrustScores',
    'adaptiveTrustScoresCaching',
    'adaptiveTrustScoresHelpers',
    'adaptiveTrustScoresVelocityNourishment',
    'ambitusMigrationTracker',
    'analysisHelpers',
    'articulationComplement',
    'articulationProfiler',
    'attackDensityProfiler',
    'axisEnergyEquilibrator',
    'axisEnergyEquilibratorAxisAdjustments',
    'axisEnergyEquilibratorHelpers',
    'axisEnergyEquilibratorPairAdjustments',
    'axisEnergyEquilibratorRefreshContext',
    'beatGridHelpers',
    'beatInterleavedProcessor',
    'beatPipelineDescriptor',
    'cadenceAdvisor',
    'cadenceAlignment',
    'cadentialPreparationAdvisor',
    'chromaticSaturationMonitor',
    'climaxProximityPredictor',
    'coherenceMonitor',
    'coherenceVerdicts',
    'composerFeedbackAdvisor',
    'conductorConfig',
    'conductorDampening',
    'conductorDiagnostics',
    'conductorIntelligence',
    'conductorMetaWatchdog',
    'conductorRecorderRegistry',
    'conductorRegulationListener',
    'conductorSignalBridge',
    'conductorState',
    'conductorStateProviderRegistry',
    'consonanceDissonanceTracker',
    'contextualTrust',
    'controllerConfig',
    'convergenceDetector',
    'convergenceHarmonicTrigger',
    'convergenceMemory',
    'convergenceVelocitySurge',
    'coordinationIndependenceManager',
    'correlationShuffler',
    'counterpointMotionTracker',
    'couplingBiasAccumulator',
    'couplingBudgetScoring',
    'couplingConstants',
    'couplingEffectiveGain',
    'couplingGainEscalation',
    'couplingHomeostasis',
    'couplingHomeostasisSnapshot',
    'couplingRefreshSetup',
    'couplingState',
    'criticalityEngine',
    'crossLayerClimaxEngine',
    'crossLayerDensityBalancer',
    'crossLayerDynamicEnvelope',
    'crossLayerEmissionGateway',
    'crossLayerHelpers',
    'crossLayerLifecycleManager',
    'crossLayerRegistry',
    'crossLayerSilhouette',
    'densityWaveAnalyzer',
    'dimensionalityExpander',
    'drumTextureCoupler',
    'durationalContourTracker',
    'dynamicArchitectPlanner',
    'dynamicPeakMemory',
    'dynamicRangeTracker',
    'dynamicRoleSwap',
    'dynamismEngine',
    'dynamismPulse',
    'emergentDownbeat',
    'emergentMelodicEngine',
    'emergentRhythmEngine',
    'emissionFeedbackListener',
    'energyMomentumTracker',
    'entropyAmplificationController',
    'entropyMetrics',
    'entropyRegulator',
    'eventBus',
    'explainabilityBus',
    'feedbackAccumulator',
    'feedbackGraphContract',
    'feedbackOscillator',
    'fractalArcGenerator',
    'fragmentHelpers',
    'fullBootstrap',
    'getMeterPair',
    'globalConductor',
    'grooveTemplateAdvisor',
    'grooveTransfer',
    'harmonicContext',
    'harmonicDensityOscillator',
    'harmonicFieldDensityTracker',
    'harmonicFunctionGraph',
    'harmonicIntervalGuard',
    'harmonicJourney',
    'harmonicJourneyHelpers',
    'harmonicJourneyPlanner',
    'harmonicJourneyPlannerStepBuilder',
    'harmonicPedalFieldTracker',
    'harmonicRhythmDensityRatio',
    'harmonicRhythmTracker',
    'harmonicSurpriseIndex',
    'harmonicVelocityMonitor',
    'homeostasisConstants',
    'homeostasisFloor',
    'homeostasisRefresh',
    'homeostasisState',
    'homeostasisTick',
    'hyperMetaManager',
    'hyperMetaManagerContradictions',
    'hyperMetaManagerEvolutions',
    'hyperMetaManagerHealth',
    'hyperMetaManagerState',
    'hyperMetaManagerTelemetry',
    'hyperMetaManagerTopology',
    'interLayerRhythmAnalyzer',
    'interLayerRhythmHelpers',
    'interactionHeatMap',
    'intervalBalanceTracker',
    'intervalDirectionMemory',
    'intervalExpansionContractor',
    'journeyRhythmCoupler',
    'layerCoherenceScorer',
    'layerEntryExitTracker',
    'layerIndependenceScorer',
    'layerPass',
    'mainBootstrap',
    'melodicContourTracker',
    'metaControllerRegistry',
    'metaProfileDefinitions',
    'metaProfiles',
    'microUnitAttenuator',
    'minimumNoteDuration',
    'modalColorTracker',
    'motifChain',
    'motifEcho',
    'motifIdentityMemory',
    'motifTransformAdvisor',
    'motivicDensityTracker',
    'narrativeTrajectory',
    'negotiationEngine',
    'octaveHelpers',
    'octaveSpreadMonitor',
    'onsetDensityProfiler',
    'onsetRegularityMonitor',
    'orchestrationWeightTracker',
    'outputAnalyzer',
    'pairGainCeilingController',
    'pedalPointDetector',
    'perceptualTensionBias',
    'phaseAwareCadenceWindow',
    'phaseFloorController',
    'phaseLockedRhythmGenerator',
    'phaseSpaceMath',
    'phraseArcProfiler',
    'phraseContourArchetypeDetector',
    'phraseLengthMomentumTracker',
    'pipelineBalancer',
    'pipelineCouplingManager',
    'pipelineCouplingManagerSnapshot',
    'pipelineNormalizer',
    'pitchClassGravityMap',
    'pitchClassHelpers',
    'pitchGravityCenter',
    'pitchMemoryRecall',
    'pivotChordBridge',
    'polyrhythmicPhasePredictor',
    'profileAdaptation',
    'reconvergenceAccelerator',
    'regimeClassifier',
    'regimeClassifierClassification',
    'regimeClassifierHelpers',
    'regimeClassifierResolution',
    'regimeFade',
    'regimeFx',
    'regimePan',
    'regimeReactiveDamping',
    'regimeReactiveDampingCore',
    'regimeReactiveDampingEquilibrator',
    'regimeVelocity',
    'registerCollisionAvoider',
    'registerMigrationTracker',
    'registerPressureMonitor',
    'registralVelocityCorrelator',
    'repetitionFatigueMonitor',
    'restDensityTracker',
    'restSynchronizer',
    'rhythmHistoryTracker',
    'rhythmicComplementEngine',
    'rhythmicComplexityGradient',
    'rhythmicDensityContrastTracker',
    'rhythmicGroupingAnalyzer',
    'rhythmicInertiaTracker',
    'rhythmicPhaseLock',
    'rhythmicSymmetryDetector',
    'sectionIntentCurves',
    'sectionIntentCurvesHelpers',
    'sectionLengthAdvisor',
    'sectionMemory',
    'signalHealthAnalyzer',
    'signalReader',
    'signalTelemetry',
    'silenceDistributionTracker',
    'spectralComplementarity',
    'structuralFormTracker',
    'structuralNarrativeAdvisor',
    'stutterContagion',
    'stutterFailFast',
    'stutterFeedbackListener',
    'stutterPlanScheduler',
    'stutterShift',
    'stutterSteps',
    'stutterTempoFeel',
    'stutterVariants',
    'syncopationDensityTracker',
    'systemDynamicsProfiler',
    'systemDynamicsProfilerAnalysis',
    'systemDynamicsProfilerHelpers',
    'systemManifest',
    'systemManifestMarkdown',
    'tempoFeelEngine',
    'temporalGravity',
    'temporalProportionTracker',
    'tensionResolutionTracker',
    'tessituraPressureMonitor',
    'texturalGradientTracker',
    'texturalMemoryAdvisor',
    'texturalMirror',
    'textureBlender',
    'thematicRecallDetector',
    'timbreBalanceTracker',
    'timeStream',
    'tonalAnchorDistanceTracker',
    'traceDrain',
    'trustEcologyCharacter',
    'trustTimbreMapping',
    'velocityInterference',
    'velocityShapeAnalyzer',
    'verticalIntervalMonitor',
    'voiceDensityBalancer',
    'voiceLeadingEfficiencyTracker',
    'warmupRampController',
  ]);

  /** @type {readonly string[]} Advisory globals: warn if missing, do not throw. */
  const ADVISORY_GLOBALS = Object.freeze([
  ]);

  /** @type {ReadonlySet<string>} */
  const validatedSet = Object.freeze(new Set(VALIDATED_GLOBALS));

  /** @type {ReadonlySet<string>} */
  const advisorySet = Object.freeze(new Set(typeof ADVISORY_GLOBALS !== 'undefined' ? ADVISORY_GLOBALS : []));

  return {
    /** @returns {ReadonlySet<string>} The set of global names proven at boot. */
    getValidatedGlobals() { return validatedSet; },

    /** @returns {readonly string[]} The ordered list for iteration. */
    getValidatedGlobalsList() { return VALIDATED_GLOBALS; },

    /** @returns {readonly string[]} Advisory globals (warn-only if missing). */
    getAdvisoryGlobalsList() { return typeof ADVISORY_GLOBALS !== 'undefined' ? ADVISORY_GLOBALS : []; },

    /** @returns {ReadonlySet<string>} Advisory globals set. */
    getAdvisoryGlobals() { return advisorySet; },

    /**
     * Assert that a global name is in the validated set.
     * Used by mainBootstrap to self-verify completeness.
     * @param {string} name
     * @returns {boolean}
     */
    isValidated(name) { return validatedSet.has(name); },
  };
  },
});
