// globals.d.ts - Centralized ambient declarations for global variables and interfaces.
// exempt from target file length limits due to its role as a centralized declaration repository.
// Managed globals - single source of truth for:
// 1) TypeScript ambient declarations (`src/types/**/*.d.ts` include)
// 2) ESLint global map (parsed directly by `eslint.config.mjs`)
// 3) Boot validation array in `fullBootstrap.js` (auto-generated by `scripts/generate-globals-dts.js`)
//
// Keep one declaration per line: `declare var NAME: Type;`
// The name is extracted by regex - type annotations and comments are safe to add.
//
// -- Abbreviation Glossary --
// m   = Math                   rf  = randomFloat          ri  = randomInt
// rw  = randomWeightedInRange  ra  = randomInRangeOrArray rv  = randomVariation
// rl  = randomLimitedChange    t   = Tonal.js     c   = polyrhythm calculator
// p   = pitch bend util        LM  = LayerManager         V   = validator instance (per-module)

// -- Core Interface Types --
// These type the 7 nervous-system globals. Every other module touches at least one.

interface BiasRegistration {
  name: string;
  getter: () => number;
  lo: number;
  hi: number;
}

interface BiasAttribution {
  product: number;
  rawProduct?: number;
  floored?: boolean;
  capped?: boolean;
  contributions: Array<{ name: string; raw: number; clamped: number }>;
}

interface RecorderContext {
  absTime: number;
  compositeIntensity: number;
  currentDensity: number;
  harmonicRhythm: number;
}

interface SignalSnapshot {
  densityProduct: number;
  tensionProduct: number;
  flickerProduct: number;
  stateFields: Record<string, unknown>;
  counts: Record<string, number>;
}

interface ConductorIntelligenceAPI {
  registerModule(name: string, mod: { reset: Function }, scopes: Array<'all' | 'section' | 'phrase'>): void;
  initialize(): void;
  resetSection(): void;
  resetPhrase(): void;
  getModuleNames(): string[];
  getModuleCount(): number;
  registerDensityBias(name: string, getter: () => number, lo: number, hi: number): void;
  collectDensityBias(): number;
  collectDensityBiasWithAttribution(): BiasAttribution;
  registerTensionBias(name: string, getter: () => number, lo: number, hi: number): void;
  collectTensionBias(): number;
  collectTensionBiasWithAttribution(): BiasAttribution;
  registerFlickerModifier(name: string, getter: () => number, lo: number, hi: number): void;
  collectFlickerModifier(): number;
  collectFlickerModifierWithAttribution(): BiasAttribution;
  registerRecorder(name: string, fn: (ctx: RecorderContext) => void): void;
  runRecorders(ctx: RecorderContext): void;
  registerStateProvider(name: string, getter: () => Record<string, unknown>): void;
  collectStateFields(): Record<string, unknown>;
  getContributorNames(): string[];
  getCounts(): { density: number; tension: number; flicker: number; recorders: number; stateProviders: number };
  getRegistryNames(): { density: string[]; tension: string[]; flicker: string[]; recorders: string[]; stateProviders: string[] };
  getSignalSnapshot(): Readonly<SignalSnapshot>;
}

interface SignalReaderAPI {
  density(): number;
  tension(): number;
  flicker(): number;
  state(field: string): any;
  snapshot(): Readonly<SignalSnapshot>;
  densityAttribution(): BiasAttribution;
  tensionAttribution(): BiasAttribution;
  flickerAttribution(): BiasAttribution;
  recentEvents(type: string, limit?: number): Array<{ type: string; layer: string; payload: unknown; absoluteSeconds: number }>;
}

interface CrossLayerRegistryAPI {
  register(name: string, module: { reset: Function }, scopes: Array<'all' | 'section' | 'phrase'>): void;
  resetAll(): void;
  resetSection(): void;
  resetPhrase(): void;
  getRegisteredNames(): string[];
  getCount(): number;
}

interface EventBusAPI {
  on(name: string, handler: (data: any) => void): void;
  off(name: string, handler: (data: any) => void): void;
  emit(name: string, data: any): void;
  listeners(name: string): number;
  clear(name: string): void;
  clearAll(): void;
}

interface VoiceLeadingScoreAPI {
  weights: Record<string, number>;
  commonToneWeight: number;
  contraryMotionPreference: number;
  dynamism: number;
  registers: Record<string, number[]>;
  maxLeapSize: Record<string, number>;
  maxHistoryDepth: number;
  history: Array<{ note: number; register: string; interval: number }>;
  selectNextNote(lastNotes: number[], availableNotes: number[], config?: any): number;
  analyzeQuality(noteSequence: number[]): { smoothness: number; avgRange: number; leapRecoveries: number };
  updateConfig(cfg?: any): void;
  reset(): void;
  // Required by voiceRegistry for multi-voice scoring.  Caller-side
  // validation often checks for this property to guard against invalid
  // objects.  The constructor now installs a bound alias so it is always
  // present on real instances.
  voiceRegistryScoreCandidate(
    candidate: number,
    lastNotes: number[],
    registerRange: number[],
    constraints: string[],
    opts?: any
  ): number;
}

interface SimplexNoiseAPI {
  p: Uint8Array;
  perm: Uint8Array;
  dot(g: number[], x: number, y: number): number;
  noise1D(xin: number): number;
  noise(xin: number, yin: number): number;
}

interface ValidatorInstance {
  requireFinite(value: unknown, label: string): number;
  optionalFinite(value: unknown): number | undefined;
  optionalFinite(value: unknown, fallback: number): number;
  optionalType(value: unknown, type: 'number'): number | undefined;
  optionalType(value: unknown, type: 'string'): string | undefined;
  optionalType(value: unknown, type: 'boolean'): boolean | undefined;
  optionalType(value: unknown, type: 'object'): object | undefined;
  optionalType(value: unknown, type: 'function'): (...args: any[]) => any | undefined;
  optionalType(value: unknown, type: string): unknown | undefined;
  optionalType<T>(value: unknown, type: string, fallback: T): T;
  requireDefined(value: unknown, label: string): unknown;
  requireType(value: unknown, type: string, label: string): unknown;
  requireEnum(value: unknown, allowed: unknown[], label: string): unknown;
  assertRange(value: unknown, lo: number, hi: number, label: string): number;
  assertObject(value: unknown, label: string): object;
  assertPlainObject(value: unknown, label: string): Record<string, unknown>;
  assertArray(value: unknown, label: string, checkNonEmpty?: boolean): any[];
  assertNonEmptyString(value: unknown, label: string): string;
  assertKeysPresent(obj: object, keys: string[], label: string): void;
  assertAllowedKeys(obj: object, keys: string[], label: string): void;
  assertBoolean(value: unknown, label: string): boolean;
  assertFinite(value: unknown, label: string): number;
  assertIntegerRange(value: unknown, lo: number, hi: number, label: string): number;
  assertString(value: unknown, label: string): string;
  assertInSet(value: unknown, allowedSet: Set<any>, label: string): any;
  assertArrayLength(value: unknown, length: number, label: string): any[];
  assertManagerShape(mgr: unknown, label: string, methods: string[]): any;
  getEventsOrThrow(): Record<string, string>;
}

interface ValidatorFactory {
  create(moduleName: string): ValidatorInstance;
}

interface ConductorStateSnapshot {
  key: string; mode: string; quality: string;
  scale: any[]; chords: any[];
  tension: number; harmonicRhythm: number; harmonicMutationCount: number;
  excursion: number; sectionPhase: string;
  phrasePosition: number; phrasePhase: string; phraseDynamism: number;
  registerBias: number; densityMultiplier: number; voiceIndependence: number;
  compositeIntensity: number; playProb: number; stutterProb: number; flicker: number;
  textureMode: string; textureFatigue: number; densityBias: number;
  crossModBias: number; emissionRatio: number; activeProfile: string;
  extraDensityCorrection: number; extraCoherenceDensityBias: number;
  journeyMove: string; journeyDistance: number; journeyKey: string; journeyMode: string;
  tick: number; updatedAt: number;
}

interface ConductorStateAPI {
  initialize(): boolean;
  updateFromConductor(data: Record<string, unknown>): void;
  getSnapshot(): ConductorStateSnapshot;
  getField<K extends keyof ConductorStateSnapshot>(field: K): ConductorStateSnapshot[K];
  get<K extends keyof ConductorStateSnapshot>(field: K): ConductorStateSnapshot[K];
  reset(): void;
}

interface ConductorConfigAPI {
  applyPhaseProfile(): void;
  tickCrossfade(): void;
  regulationTick(): void;
  getActiveProfile(): Record<string, any>;
  getPhaseMultiplier(phase: string): number;
  getGlobalIntensityBlend(): { arc: number; tension: number };
  getHarmonicRhythmParams(): { blendWeight: number; feedbackWeight: number };
  getTargetDensity(compositeIntensity: number): number;
  getDensitySmoothing(): number;
  getDensityBounds(): { floor: number; ceiling: number };
  getStutterParams(compositeIntensity: number): { rate: number; rateCurve: string; coherenceMode: string };
  getClimaxBoost(): { playScale: number; stutterScale: number };
  getRegulationDensityBias(): number;
  getRegulationCrossModBias(): number;
  getActiveProfileName(): string;
  getFamilyWeights(): Record<string, number>;
  getMotifMutationParams(): Record<string, any>;
  getMotifTextureClampParams(): Record<string, any>;
  getNoiseProfileForSection(sectionPhaseOverride?: string): string;
  getVoiceSpreadScaling(): Record<string, any>;
  getFeedbackMixWeights(): { fx: number; stutter: number; journey: number };
  getHintBlendedEnergyWeights(): { phrase: number; journey: number; feedback: number; pulse: number };
  getEmissionGateParams(): Record<string, any>;
  getFlickerParams(): { depthScale: number; crossModWeight: number };
  getJourneyBoldness(): number;
  getArcMapping(sectionPhase?: string): any;
  getPhraseBreathParams(): Record<string, any>;
  getTextureScaling(): Record<string, any>;
  getNoiseCanvasParams(): Record<string, any>;
  getSpatialCanvasParams(): Record<string, any>;
  getJourneyFxModulation(stopOverride?: { distance?: number; move?: string }): { reverbScale: number; filterScale: number; portamentoScale: number };
  getFxMixScaling(): Record<string, any>;
  getStutterGrainParams(): Record<string, any>;
  getEmissionScaling(): Record<string, any>;
  getAttenuationScaling(): Record<string, any>;
  getCrossModScaling(): Record<string, any>;
  getRhythmDriftParams(): Record<string, any>;
  getEnergyWeights(): Record<string, number>;
}

interface ATGEntry {
  timeInSeconds: number;
  layer: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;
}

interface AbsoluteTimeGridAPI {
  post(channel: string, layer: string, timeInSeconds: number, data?: Record<string, unknown>): void;
  query(channel: string, aroundMs: number, toleranceMs: number, opts?: { excludeLayer?: string; onlyLayer?: string }): ATGEntry[];
  findClosest(channel: string, aroundMs: number, toleranceMs: number, excludeLayer?: string): ATGEntry | null;
  getChannels(): string[];
  reset(channel?: string): void;
  now(): number;
}

// -- Explainability / Trust / Coherence --

interface ExplainabilityEntry {
  type: string;
  layer: string;
  payload: any;
  absoluteSeconds: number;
}

interface ExplainabilityBusAPI {
  emit(type: string, layer: string, payload: any, absoluteSeconds?: number, cause?: string): ExplainabilityEntry;
  getRecent(limit?: number): ExplainabilityEntry[];
  querySince(sinceSec: number): ExplainabilityEntry[];
  queryByType(type: string, limit?: number): ExplainabilityEntry[];
  reset(): void;
}

interface AdaptiveTrustScoresAPI {
  registerOutcome(systemName: string, payoff: number): number;
  getBaseWeight(systemName: string): number;
  getWeight(systemName: string): number;
  getWeightBatch(systemNames: string[]): Record<string, number>;
  decayAll(rate?: number): void;
  getSnapshot(): Record<string, any>;
  getJournal(): { section: number; beat: number; systemName: string; payoff: number; scoreBefore: number; scoreAfter: number; ms: number }[];
  reset(): void;
}

interface ContextualTrustAPI {
  record(moduleName: string, payoff: number): void;
  getScore(moduleName: string): number | null;
  getContextualWeight(moduleName: string): number | null;
  getWeight(moduleName: string): number;
  getScoreCount(): number;
  reset(): void;
}

interface CoherenceMonitorAPI {
  initialize(): void;
  getDensityBias(): number;
  getEntropySignal(): number;
  getMetrics(): { bias: number; entropy: number; windowSize: number; cumActual: number; cumIntended: number };
  reset(): void;
}

// -- Conductor subsystem objects --

interface ConductorSignalBridgeAPI {
  refresh(ctx: RecorderContext): void;
  getSignals(): Readonly<{ density: number; tension: number; flicker: number; compositeIntensity: number; sectionPhase: string; coherenceEntropy: number }>;
  reset(): void;
}

interface ProfileAdaptationAPI {
  update(): void;
  getHints(): { restrainedHint: number; explosiveHint: number; atmosphericHint: number };
  reset(): void;
}

interface SignalTelemetryAPI {
  record(ctx: RecorderContext): void;
  getHistory(n?: number): Array<{ tick: number; density: number; tension: number; flicker: number; compositeIntensity: number }>;
  isAnomalyDetected(): boolean;
  getTrend(): string;
  reset(): void;
}

interface SignalHealthPipeline {
  grade: string;
  product: number;
  pinnedModules: string[];
  crushFactor: number;
  saturated?: boolean;
}

interface SignalHealthTrust {
  grade: string;
  starvingSystems: string[];
  thrivingSystems: string[];
}

interface SignalHealthSnapshot {
  density: SignalHealthPipeline;
  tension: SignalHealthPipeline;
  flicker: SignalHealthPipeline;
  trust: SignalHealthTrust;
  overall: string;
}

interface SignalHealthSummary {
  beatsAnalyzed: number;
  pinnedRate: { density: number; tension: number; flicker: number };
  saturationRate: { density: number; tension: number };
  lastHealth: SignalHealthSnapshot;
}

interface SignalHealthAnalyzerAPI {
  analyze(): void;
  getHealth(): SignalHealthSnapshot;
  getSummary(): SignalHealthSummary;
  reset(): void;
}

// -- System Dynamics Profiler (phase-space trajectory analysis) --

interface SystemDynamicsSnapshot {
  velocity: number;
  curvature: number;
  effectiveDimensionality: number;
  couplingStrength: number;
  regime: string;
  grade: string;
  couplingMatrix: Record<string, number>;
  compositionalVariance: number[];
  entropyAmplification: number;
  entropySampleErrors: number;
  entropyRhythmErrors: number;
  lastEntropyError: string;
  phaseValue: number;
  phaseDelta: number;
  phaseChanged: boolean;
  phaseStaleBeats: number;
  phaseSignalValid: boolean;
  phaseCouplingCoverage: number;
  phaseCouplingAvailablePairs: number;
  phaseCouplingMissingPairs: number;
  phasePairStates: Record<string, string>;
  profilerTick: number;
  regimeTick: number;
  trajectorySamples: number;
  telemetryBeatSpan: number;
  warmupTicksRemaining: number;
  profilerCadence: string;
  cadenceEscalated: boolean;
  analysisSource: string;
}

interface SystemDynamicsSummary {
  beatsAnalyzed: number;
  snapshot: SystemDynamicsSnapshot;
  dimensionNames: string[];
}

interface SystemDynamicsProfilerAPI {
  analyze(source?: string): SystemDynamicsSnapshot;
  ensureBeatAnalysis(force?: boolean): SystemDynamicsSnapshot;
  getSnapshot(): SystemDynamicsSnapshot;
  getSummary(): SystemDynamicsSummary;
  reset(): void;
}

interface ForcedTransitionEvent {
  eventId: number;
  from: string;
  to: string;
  reason: string;
  triggerStreak: number;
  triggerTick: number;
  runTickCount: number;
  runTransitionCount: number;
  runCoherentBeats: number;
  runCoherentShare: number;
  forcedBeatsRemaining: number;
}

interface JourneyStop {
  key: string;
  mode: string;
  move: string;
  distance: number;
}

interface HarmonicContextAPI {
  set(updates: { key?: string; mode?: string; quality?: string; scale?: any[]; chords?: any[]; tension?: number; excursion?: number; sectionPhase?: string }): void;
  get(): { key: string; mode: string; quality: string; scale: any[]; chords: any[]; tension: number; excursion: number; sectionPhase: string; mutationCount: number; modifiedAt: number };
  getField(field: string): any;
  updateScaleFromMode(key: string, mode: string): void;
  isNoteInScale(noteInput: string | number): boolean;
  reset(): void;
  toJSON(): object;
}

interface HarmonicJourneyAPI {
  planJourney(totalSections: number, opts?: { startKey?: string; startMode?: string }): JourneyStop[];
  getStop(sectionIndex: number): JourneyStop;
  applyToContext(sectionIndex: number): void;
  getL2Complement(sectionIndex: number): { key: string; mode: string; relationship: string };
  applyL2ToContext(sectionIndex: number): void;
  getPlan(): JourneyStop[];
  getCurrentIndex(): number;
  getOrigin(): { key: string; mode: string };
  reset(): void;
}

// -- Time subsystem --

type TimeStreamLevel = 'section' | 'phrase' | 'measure' | 'beat' | 'div' | 'subdiv' | 'subsubdiv';

interface TimeStreamAPI {
  setPosition(level: TimeStreamLevel, index: number): void;
  setBounds(level: TimeStreamLevel, count: number): void;
  getPosition(level: TimeStreamLevel): number;
  getBounds(level: TimeStreamLevel): number;
  progress(level: TimeStreamLevel): number;
  normalizedProgress(level: TimeStreamLevel): number;
  globalProgress(): number;
  remaining(level: TimeStreamLevel): number;
  isFirst(level: TimeStreamLevel): boolean;
  isLast(level: TimeStreamLevel): boolean;
  lookAhead(level: TimeStreamLevel, n: number): number;
  lookBehind(level: TimeStreamLevel, n: number): number;
  depth(level: TimeStreamLevel): number;
  snapshot(): Readonly<{ pos: Record<TimeStreamLevel, number>; bounds: Record<TimeStreamLevel, number>; globalProgress: number }>;
  range(start: number, end: number): Generator<number>;
  getLevels(): readonly string[];
  resetPositions(): void;
  compoundProgress(level: TimeStreamLevel): number;
  resetSubLevels(level: TimeStreamLevel): void;
  positionString(): string;
}

interface LayerManagerAPI {
  layers: Record<string, any>;
  layerComposers: Record<string, any>;
  phraseFamily: string | null;
  activeLayer: string | null;
  register(name: string, buffer: any[] | string, initialState?: object, setupFn?: Function): { layer: any; buffer: any[] };
  activate(name: string, isPoly?: boolean): any;
  advance(name: string, advancementType?: 'phrase' | 'section'): void;
  setSectionStartFor(name: string): void;
  setSectionStartAll(): void;
  setPhraseFamily(familyName: string): string;
  getPhraseFamily(): string;
  setComposerFor(name: string, nextComposer: object): any;
  setComposerForAll(nextComposer: object): any;
  getComposerFor(name: string): any;
  saveActive(): void;
  getLayer(name: string): any;
  getLayerNames(): string[];
  resetAll(): void;
}

// -- Lifecycle / caching utilities --

interface ModuleLifecycleInstance {
  register(name: string, mod: { reset: Function }, scopes: Array<'all' | 'section' | 'phrase'>): void;
  resetByScope(scope: string): void;
  resetAll(): void;
  resetSection(): void;
  resetPhrase(): void;
  getNames(): string[];
  getCount(): number;
}

interface ModuleLifecycleFactory {
  create(ownerName: string): ModuleLifecycleInstance;
  registerInitializer(name: string, initFn: () => void, dependencies?: string[]): void;
  initializeAll(): void;
}

interface BeatCacheInstance {
  get(): any;
}

interface BeatCacheFactory {
  create(fn: () => any): BeatCacheInstance;
}

interface ClosedLoopControllerInstance {
  getBias(): number;
  getError(): number;
  getAmplitude(): number;
  getPhase(): number;
  getMetrics(): { bias: number; error: number; observed: number; target: number; amplitude: number; phase: number };
  reset(): void;
  refresh(): void;
  name: string;
}

interface ClosedLoopControllerFactory {
  create(config: {
    name: string;
    observe: () => number;
    target: () => number;
    gain?: number | (() => number);
    smoothing?: number;
    clampRange?: [number, number];
    sourceDomain: string;
    targetDomain: string;
    invert?: boolean;
    deadband?: number;
  }): ClosedLoopControllerInstance;
  getNames(): string[];
  getCount(): number;
  getSnapshot(): Record<string, { bias: number; error: number; amplitude: number; phase: number }>;
}

// -- eventCatalog --

interface EventCatalogAPI {
  names: Readonly<{
    SECTION_BOUNDARY: 'section-boundary';
    JOURNEY_MOVE: 'journey-move';
    TEXTURE_CONTRAST: 'texture-contrast';
    BEAT_FX_APPLIED: 'beat-fx-applied';
    STUTTER_APPLIED: 'stutter-applied';
    CONDUCTOR_REGULATION: 'conductor-regulation';
    HARMONIC_CHANGE: 'harmonic-change';
    NOTES_EMITTED: 'notes-emitted';
    MOTIF_CHAIN_APPLIED: 'motif-chain-applied';
    CROSS_LAYER_EXPLAIN: 'cross-layer-explain';
    CONVERGENCE_HARMONIC_TRIGGER: 'convergence-harmonic-trigger';
    CROSS_LAYER_CONVERGENCE: 'cross-layer-convergence';
    CROSS_LAYER_CADENCE_ALIGN: 'cross-layer-cadence-align';
    PHRASE_BOUNDARY: 'phrase-boundary';
    MEASURE_BOUNDARY: 'measure-boundary';
  }>;
  assertEventPayload(name: string, data: object): boolean;
  validateEmit(name: string, data: object): boolean;
}

// -- trustSystems --

interface TrustSystemsAPI {
  names: Readonly<{
    STUTTER_CONTAGION: 'stutterContagion';
    PHASE_LOCK: 'phaseLock';
    CADENCE_ALIGNMENT: 'cadenceAlignment';
    CONVERGENCE: 'convergence';
    FEEDBACK_OSCILLATOR: 'feedbackOscillator';
    COHERENCE_MONITOR: 'coherenceMonitor';
    ENTROPY_REGULATOR: 'entropyRegulator';
    REST_SYNCHRONIZER: 'restSynchronizer';
    ROLE_SWAP: 'roleSwap';
    GROOVE_TRANSFER: 'grooveTransfer';
    VELOCITY_INTERFERENCE: 'velocityInterference';
    HARMONIC_INTERVAL_GUARD: 'harmonicIntervalGuard';
    EMERGENT_DOWNBEAT: 'emergentDownbeat';
    ARTICULATION_COMPLEMENT: 'articulationComplement';
    TEXTURAL_MIRROR: 'texturalMirror';
    SPECTRAL_COMPLEMENTARITY: 'spectralComplementarity';
    MOTIF_ECHO: 'motifEcho';
    CLIMAX_ENGINE: 'climaxEngine';
    DYNAMIC_ENVELOPE: 'dynamicEnvelope';
    TEMPORAL_GRAVITY: 'temporalGravity';
    RHYTHMIC_COMPLEMENT: 'rhythmicComplement';
  }>;
  heatMapSystems: Readonly<{
    STUTTER_CONTAGION: 'stutterContagion';
    CONVERGENCE: 'convergence';
    TEMPORAL_GRAVITY: 'temporalGravity';
    VELOCITY_INTERFERENCE: 'velocityInterference';
    FEEDBACK_OSCILLATOR: 'feedbackOscillator';
    CADENCE_ALIGNMENT: 'cadenceAlignment';
    PHASE_LOCK: 'phaseLock';
    SPECTRAL_COMPLEMENT: 'spectralComplement';
    ROLE_SWAP: 'roleSwap';
    MOTIF_ECHO: 'motifEcho';
    EMERGENT_DOWNBEAT: 'emergentDownbeat';
    CLIMAX_ENGINE: 'climaxEngine';
    REST_SYNC: 'restSync';
  }>;
  assertKnownTrustSystem(name: string, caller: string): void;
  assertKnownHeatMapSystem(name: string, caller: string): void;
}

// -- metaControllerRegistry --

interface MetaControllerEntry {
  id: number;
  name: string;
  file: string;
  axes: string[];
  mechanism: string;
  gain: string;
  interactsWith: number[];
  interactionNotes: string;
}

interface MetaControllerRegistryAPI {
  getAll(): ReadonlyArray<MetaControllerEntry>;
  getById(id: number): MetaControllerEntry | undefined;
  getByAxis(axis: string): MetaControllerEntry[];
  getInteractors(id: number): MetaControllerEntry[];
  getSnapshot(): { count: number; axes: string[]; controllers: ReadonlyArray<MetaControllerEntry> };
}

// -- crossLayerEmissionGateway --

interface CrossLayerEmissionGatewayAPI {
  emit(sourceModule: string, buffer: any[], event: object): void;
  emitMultiple(sourceModule: string, buffer: any[], ...events: object[]): void;
  getCounts(): Readonly<Record<string, number>>;
  getTotal(): number;
  getSnapshot(): { counts: Record<string, number>; total: number };
  reset(): void;
}

interface CrossLayerHelpersAPI {
  createLayerPair<T>(l1Value: T, l2Value?: T): { L1: T; L2: T };
  getOtherLayer(layer: string): string;
  scaleVelocity(velocity: number, factor: number): number;
  syncOffset(timeInSeconds: number): number;
  getOctaveBounds(options?: { lowOffset?: number; clipToMidi?: boolean; anchorMidi?: number; radius?: number }): { lo: number; hi: number };
}

// -- Cross-Layer Module Interfaces --

interface SectionIntentCurvesAPI {
  getIntent(): { densityTarget: number; dissonanceTarget: number; interactionTarget: number; entropyTarget: number; convergenceTarget: number };
  getLastIntent(): { densityTarget: number; dissonanceTarget: number; interactionTarget: number; entropyTarget: number; convergenceTarget: number };
  setManualIntent(intent: { densityTarget?: number; dissonanceTarget?: number; interactionTarget?: number; entropyTarget?: number }): { densityTarget: number; dissonanceTarget: number; interactionTarget: number; entropyTarget: number; convergenceTarget: number };
  reset(): void;
}

interface NegotiationEngineAPI {
  apply(layer: string, context: { playProb: number; stutterProb: number; cadenceSuggested: boolean; phaseConfidence: number; intent?: { densityTarget: number; dissonanceTarget: number; interactionTarget: number; entropyTarget: number; convergenceTarget: number }; entropyScale?: number }): { playProb: number; stutterProb: number; allowCadence: boolean; conflict: number; phaseConfidence: number };
  gateConvergence(layer: string): { allowHarmonicTrigger: boolean; allowDownbeat: boolean };
  reset(): void;
}

interface InteractionHeatMapAPI {
  record(systemName: string, intensity: number): void;
  flushBeat(absoluteSeconds: number): void;
  deferBeat(beatKey: string): void;
  flushBeatPair(absoluteSeconds: number, beatKey: string): void;
  flushDeferredOrphans(absoluteSeconds: number): void;
  getDensity(): number;
  getSystemHeat(): Record<string, number>;
  getBreathingRecommendation(): { recommendation: 'increase' | 'maintain' | 'decrease'; density: number; beatsTracked: number };
  getTrend(): { trend: 'rising' | 'falling' | 'stable'; slope: number };
  reset(): void;
}

interface EntropyRegulatorAPI {
  recordSample(midi: number, velocity: number, layer: string): void;
  measureEntropy(): number;
  measureRawEntropy(): number;
  setTarget(target: number, arcTarget?: number): void;
  getArcTarget(sectionProgress: number): number;
  getRegulation(): { scale: number; currentEntropy: number; targetEntropy: number; error: number };
  regulate(prob: number): number;
  setRegulationStrength(strength: number): void;
  reset(): void;
  getRhythmErrors(): number;
}

interface EntropyMetricsAPI {
  pitchEntropy(notes: number[]): number;
  velocityVariance(velocities: number[]): number;
  rhythmicIrregularity(layer: string): number;
}

interface CrossLayerSilhouetteAPI {
  tick(absoluteSeconds: number, activeLayer?: string): void;
  getCorrections(): { densityBias: number; registerBias: number; dynamicBias: number; entropyBias: number };
  getSilhouette(): { density: number; register: number; dynamic: number; entropy: number };
  getSilhouetteArc(): Array<{ density: number; register: number; dynamic: number; entropy: number; timeInSeconds: number }>;
  reset(): void;
}

interface CrossLayerClimaxEngineAPI {
  tick(absoluteSeconds: number): void;
  getModifiers(layer?: string): { playProbScale: number; velocityScale: number; registerBias: number; entropyTarget: number };
  isApproaching(): boolean;
  isPeak(): boolean;
  getClimaxLevel(): number;
  getClimaxCount(): number;
  reset(): void;
}

interface ConvergenceDetectorAPI {
  postOnset(absoluteSeconds: number, layer: string, midi: number, velocity: number): void;
  detect(absoluteSeconds: number, activeLayer: string): { rarity: number; otherMidi: number; otherVelocity: number } | null;
  applyIfConverged(absoluteSeconds: number, activeLayer: string, currentMidi: number, currentVelocity: number): { convergence: boolean; rarity: number; burstNotes: number[]; totalConvergences: number } | null;
  wasRecent(absoluteSeconds: number, layer: string, windowMs?: number): boolean;
  getLastConvergenceMs(layer: string): number;
  getConvergenceCount(): number;
  reset(): void;
}

interface GrooveTransferAPI {
  recordTiming(layer: string, timeSec: number, unit: string): void;
  applyOffset(layer: string, timeSec: number, unit: string): number;
  reset(): void;
}

interface TemporalGravityAPI {
  postDensity(absoluteSeconds: number, layer: string, density: number): void;
  measureDensity(layer: string, absTimeSec: number): number;
  applyGravity(absoluteSeconds: number, activeLayer: string, originalTime: number): number;
  reset(): void;
}

interface StutterContagionAPI {
  postStutter(absoluteSeconds: number, layer: string, intensity: number, channels: number[], type: string): void;
  checkContagion(absoluteSeconds: number, activeLayer: string): { syncOffset: number; intensity: number; channels: number[]; type: string } | null;
  apply(absoluteSeconds: number, activeLayer: string): void;
  reset(): void;
}

interface RhythmicPhaseLockAPI {
  postBeat(absoluteSeconds: number, layer: string, spBeatVal: number): void;
  measurePhase(absoluteSeconds: number, activeLayer: string): { phaseDiff: number; mode: 'lock' | 'drift' | 'repel'; otherBeatSec: number } | null;
  applyPhaseLock(absoluteSeconds: number, activeLayer: string, originalTime: number): { time: number; mode: 'lock' | 'drift' | 'repel'; phaseDiff: number };
  getMode(): 'lock' | 'drift' | 'repel';
  getLockCount(): number;
  reset(): void;
}

interface RhythmicComplementEngineAPI {
  analyzeOtherLayer(activeLayer: string, absoluteSeconds: number): { gaps: number[]; density: number; avgIOI: number };
  suggestComplement(layer: string, onTime: number, absoluteSeconds: number): { time: number; velocityScale: number; modified: boolean };
  getMode(): 'hocket' | 'antiphony' | 'canon' | 'free';
  setMode(newMode: 'hocket' | 'antiphony' | 'canon' | 'free'): void;
  autoSelectMode(absoluteSeconds?: number): void;
  reset(): void;
}

interface FeedbackOscillatorAPI {
  inject(absoluteSeconds: number, layer: string, energy: number, impulseType?: string, pitchClass?: number): void;
  react(absoluteSeconds: number, activeLayer: string): { energy: number; roundTrip: number; impulseType: string; syncOffset: number; pitchBias: number } | null;
  applyFeedback(absoluteSeconds: number, activeLayer: string): { applied: boolean; energy: number; roundTrip: number; pitchBias: number };
  reset(): void;
}

interface EmergentDownbeatAPI {
  detect(absoluteSeconds: number, signals: { convergence: boolean; cadenceAlign: boolean; velReinforce: boolean; phaseLock: boolean }): { isDownbeat: boolean; strength: number; signalCount: number } | null;
  accentVelocity(velocity: number, strength: number): number;
  reinforceBass(midi: number, velocity: number, strength: number): void;
  widenStereo(layer: string, strength: number): void;
  applyIfDownbeat(absoluteSeconds: number, layer: string, signals: { convergence: boolean; cadenceAlign: boolean; velReinforce: boolean; phaseLock: boolean }, midi: number, velocity: number): { isDownbeat: boolean; accentedVelocity: number; strength: number } | null;
  getDownbeatCount(): number;
  reset(): void;
}

interface ConvergenceHarmonicTriggerAPI {
  onConvergence(event: { rarity?: number; absoluteSeconds?: number; layer?: string; alignment?: { tonicBias: number; dominantBias: number; shouldResolve: boolean } | null }): void;
  shouldTriggerChange(absoluteSeconds: number): boolean;
  getTriggeredChanges(): Array<{ type: string; bias: number; absoluteSeconds: number }>;
  getTriggerCount(): number;
  reset(): void;
}

interface MotifEchoAPI {
  recordNote(midi: number, layer: string, absoluteSeconds: number): void;
  captureMotif(layer: string, absoluteSeconds: number): void;
  applyTransform(intervals: number[], transform: string): number[];
  deliverEcho(absoluteSeconds: number, activeLayer: string, currentMidi: number): { notes: number[]; transform: string; echoIndex: number } | null;
  getPendingCount(): number;
  reset(): void;
}

interface PitchMemoryRecallAPI {
  memorize(intervalDna: number[], pitchClasses: number[], strengthSignals: { convergence?: boolean; cadence?: boolean; downbeat?: boolean }, sectionIdx: number): void;
  recall(activeLayer: string, currentMidi: number, absoluteSeconds: number): { notes: number[]; transform: string; memoryIdx: number } | null;
  getMemoryCount(): number;
  getRecallCount(): number;
  reset(): void;
}

interface PhaseAwareCadenceWindowAPI {
  update(absoluteSeconds: number, layer: string): { phaseDiff: number; mode: 'lock' | 'drift' | 'repel'; confidence: number };
  getLatest(layer: string): { timeInSeconds: number; phaseDiff: number; mode: 'lock' | 'drift' | 'repel'; confidence: number } | null;
  getConfidence(layer: string): number;
  shouldAllowCadence(absoluteSeconds: number, layer: string, cadenceSuggested: boolean, snapshot?: { timeInSeconds: number; phaseDiff: number; mode: string; confidence: number } | null): boolean;
  reset(): void;
}

interface MotifIdentityMemoryAPI {
  recordNote(layer: string, midi: number, absoluteSeconds: number): { intervalDna: string; contour: string; confidence: number; absoluteSeconds: number } | null;
  getActiveIdentity(layer: string): { intervalDna: string; contour: string; confidence: number; absoluteSeconds: number } | null;
  chooseEchoTransform(layer: string): { transform: 'retrograde' | 'inversion' | 'augmentation' | 'retrograde-inversion'; bias: number } | null;
  reset(): void;
}

interface HarmonicIntervalGuardAPI {
  recordCrossInterval(midiA: number, midiB: number, absoluteSeconds: number): void;
  getDissonanceLevel(): number;
  nudgePitch(midi: number, activeLayer: string, absoluteSeconds: number, externalPitchBias?: number): { midi: number; nudged: boolean; interval: number; otherMidi: number };
  reset(): void;
}

interface CadenceAlignmentAPI {
  postTension(absoluteSeconds: number, layer: string, tension: number, cadenceSuggested: boolean): void;
  checkAlignment(absoluteSeconds: number, activeLayer: string, ourTension: number, ourCadenceSuggested?: boolean): { aligned: boolean; syncOffset: number; combinedTension: number; otherCadenceSuggested: boolean; sharedCadenceIntent: boolean; consensus: boolean } | null;
  applyAlignment(absoluteSeconds: number, activeLayer: string, ourTension: number, ourCadenceSuggested?: boolean): { shouldResolve: boolean; tonicBias: number; dominantBias: number; syncOffset: number; consensus: boolean; sharedCadenceIntent: boolean } | null;
  reset(): void;
}

interface RegisterCollisionAvoiderAPI {
  recordNote(layer: string, midi: number, absoluteSeconds: number): void;
  avoid(activeLayer: string, midi: number, absoluteSeconds: number): { midi: number; adjusted: boolean };
  reset(): void;
}

interface SpectralComplementarityAPI {
  recordNote(midi: number, layer: string): void;
  getHistogram(layer: string): number[];
  analyzeComplement(activeLayer: string): { gaps: number[]; dominant: number[]; gapWeight: number };
  nudgeToFillGap(midi: number, activeLayer: string): { midi: number; nudged: boolean; targetBin: number };
  postSpectralState(absoluteSeconds: number, layer: string): void;
  reset(): void;
}

interface VelocityInterferenceAPI {
  postVelocity(absoluteSeconds: number, layer: string, velocity: number, delta: number): void;
  measureDelta(layer: string, absTimeSec: number): number;
  applyInterference(absoluteSeconds: number, activeLayer: string, baseVelocity: number): { velocity: number; mode: 'reinforce' | 'separate' | 'neutral' };
  reset(): void;
}

interface TexturalMirrorAPI {
  recordTexture(layer: string, mode: string, absoluteSeconds: number): void;
  suggestTexture(activeLayer: string, absoluteSeconds: number): { preferredMode: string; weight: number };
  getTextureDistance(): number;
  reset(): void;
}

interface RestSynchronizerAPI {
  evaluateSharedRest(absoluteSeconds: number, layer: string, signals?: { heatLevel?: number; densityTarget?: number; phaseMode?: string }): { shouldRest: boolean; duration: number };
  evaluateComplementaryRest(absoluteSeconds: number, activeLayer: string): { shouldFill: boolean; fillUrgency: number };
  postRest(absoluteSeconds: number, layer: string): void;
  getSharedRestCount(): number;
  isLayerResting(layer: string): boolean;
  reset(): void;
}

interface DynamicRoleSwapAPI {
  evaluateSwap(absoluteSeconds: number, currentTension: number): { swapped: boolean; swapCount: number };
  getProfileModifiers(layer: string): { densityScale: number; chordalBias: number; melodicBias: number; isSwapped: boolean };
  modifyPlayProb(layer: string, playProb: number): number;
  modifyVelocity(layer: string, vel: number): number;
  getIsSwapped(): boolean;
  getSwapCount(): number;
  reset(): void;
}

interface CrossLayerDynamicEnvelopeAPI {
  tick(absoluteSeconds: number, layer: string): void;
  getVelocityScale(layer: string): number;
  setArcType(type: 'parallel' | 'complementary' | 'independent'): void;
  getArcType(): 'parallel' | 'complementary' | 'independent';
  autoSelectArcType(): void;
  reset(): void;
}

interface ArticulationComplementAPI {
  recordSustain(layer: string, sustainSec: number, absoluteSeconds: number): void;
  getArticulationProfile(layer: string): { avgSustain: number; isLegato: boolean; isStaccato: boolean };
  getSustainModifier(activeLayer: string): { sustainScale: number; preferredStutterType: string };
  reset(): void;
}

interface CrossLayerLifecycleManagerAPI {
  resetAll(): void;
  resetSection(): void;
  resetPhrase(): void;
}

// -- Rhythm / Time / Composer Interfaces --

interface RhythmRegistryAPI {
  register(name: string, fn: (...args: any[]) => any[]): (...args: any[]) => any[];
  registerMany(obj: Record<string, (...args: any[]) => any[]>): void;
  get(name: string): (...args: any[]) => any[];
  execute(name: string, ...args: any[]): any[];
  list(): string[];
  getAll(): Record<string, (...args: any[]) => any[]>;
}

interface RhythmManagerAPI {
  listGenerators(): string[];
  getGenerator(name: string): (...args: any[]) => any;
  getPattern(level: number, length: number, pattern: any, method?: string, ...args: any[]): any[];
  applyToNote(note: any, hit: any, profileName?: string, options?: Record<string, any>): any;
  quantizeTime(time: number, resolution: number): number;
  swingOffset(beatIndex: number, amount: number): number;
  accentWeight(beatIndex: number, pattern: Array<0 | 1>): 0 | 1;
}

interface RhythmValuesAPI {
  quantizeTime(time: number, resolution: number): number;
  swingOffset(beatIndex: number, amount: number): number;
  accentWeight(beatIndex: number, pattern: Array<0 | 1>): 0 | 1;
}

interface PhaseLockedRhythmGeneratorAPI {
  generate(length: number, patternName: string, phaseOffset?: number): any[];
  lock(patternName: string, length: number, phase: number): void;
  getPhase(patternName: string, length: number): number;
  advancePhase(patternName: string, length: number, delta: number, modulo?: number): void;
  getPhaseRelationship(patternA: string, lengthA: number, patternB: string, lengthB: number): number;
  reset(): void;
  getHistory(limit?: number): Array<{ patternName: string; length: number; offset: number }>;
  setActiveLayer(layerName: string): void;
  initializePolyrhythmCoupling(layer1: string, layer2: string, ratio1: number, ratio2: number): void;
}

interface MotifChainAPI {
  setActive(motif: any): void;
  getActive(): any | null;
  addTransform(type: 'transpose' | 'rotate' | 'invert' | 'augment' | 'diminish' | 'reverse' | 'develop', ...args: any[]): void;
  apply(): any;
  applyToNotes(notes: Array<{ note: number }>, options?: Record<string, any>): Array<{ note: number }>;
  mutate(options?: { transposeRange?: [number, number]; rotateRange?: [number, number] | null; allowInvert?: boolean; allowReverse?: boolean; allowAugment?: boolean; augmentRange?: [number, number] }): void;
  clearTransforms(): void;
  reset(): void;
  getTransforms(): Array<{ type: string; args: any[] }>;
  getHistory(limit?: number): Array<{ baseMotif: any; transforms: Array<{ type: string; args: any[] }>; resultLength: number }>;
}

interface MotifManagerAPI {
  listGenerators(): string[];
  getGenerator(name: string): (...args: any[]) => any;
  generate(name: string, ...args: any[]): any;
  applyToNotes(notes: any[], motifPattern: any, profileName?: string, options?: Record<string, any>): any[];
  repeatPattern(pattern: any[], times: number): any[];
  offsetPattern(pattern: any[], offsetSteps: number): any[];
  scaleDurations(pattern: any[], scale: number): any[];
  planMeasure(layer: any, composer: any): void;
  planDivs(layer: any, dpb: number, beats: number, composer: any): void;
  planSubdivs(layer: any, absDivIdx: number, sPerDiv: number): void;
  planSubsubdivs(layer: any, absSubdivIdx: number, ssPerSub: number): void;
  _resetChildVM(layer: any, childUnit: string): void;
}

interface TempoFeelEngineAPI {
  getTimeOffset(): number;
  getFeelState(): { feel: number; phase: string; position: number };
}

interface DynamismEngineAPI {
  resolve(unit: 'beat' | 'div' | 'subdiv' | 'subsubdiv', opts?: { playProb?: number; stutterProb?: number }): { playProb: number; stutterProb: number; composite: number };
}

interface ComposerFeedbackAdvisorAPI {
  getFamilyWeightAdjustments(availableFamilies: string[]): Record<string, number>;
  scoreCandidateAdjustment(candidateConfig: { type: string; [k: string]: any }): number;
  getQualitySnapshot(): {
    fatigueSignal: number;
    varietyPressure: number;
    thematicStatus: string;
    profileHints: { restrainedHint: number; explosiveHint: number; atmosphericHint: number };
  };
  reset(): void;
}

interface TextureBlenderAPI {
  resolve(unit: 'beat' | 'div' | 'subdiv' | 'subsubdiv', composite: number): { mode: 'single' | 'chordBurst' | 'flurry'; velocityScale: number; sustainScale: number };
  getRecentDensity(): number;
}

interface GlobalConductorAPI {
  update(): { playProb: number; stutterProb: number };
}

interface HarmonicRhythmTrackerAPI {
  initialize(): void;
  getHarmonicRhythm(): number;
  getMetrics(): { harmonicRhythm: number; changesInSection: number; lastTick: number | null };
  reset(): void;
}

// -- Conductor / Composer / FX Class Interfaces --

interface PhraseArcManagerAPI {
  arcType: string;
  registerRange: number;
  densityRange: { min: number; max: number };
  getPhraseContext(): { position: number; phase: string; measureInPhrase: number; phraseNumber: number; registerBias: number; densityMultiplier: number; voiceIndependence: number; dynamism: number; spectralDensity: number; atBoundary: boolean; atStart: boolean; atEnd: boolean };
  getPosition(): number;
  getPhase(): string;
  isAtBoundary(): boolean;
  isAtEnd(): boolean;
  isAtStart(): boolean;
  reset(): boolean;
}

interface ComposerFactoryAPI {
  sharedPhraseArcManager: PhraseArcManagerAPI;
  sharedComposerCtx: any | null;
  activeFamily: string | null;
  capabilityProfiles: any;
  runtimeProfilePrecedence: any;
  constructors: any;
  setComposerContext(ctx: any): void;
  getPhraseArcManager(opts?: Record<string, any>): PhraseArcManagerAPI;
  resetPhraseArcManager(): void;
  getCommonProfileConfigKeys(): string[];
  getConstructorOptionKeysByType(): Record<string, string[]>;
  validateCapabilityProfiles(): any;
  validateProfileSchemaFactoryCompatibility(): any;
  resolveRuntimeProfiles(config?: Record<string, any>): any;
  applyRuntimeProfileConfig(composer: any, config?: Record<string, any>): any;
  applyCapabilityContract(composer: any, type: string, config?: Record<string, any>): any;
  normalizeProgressionKeyOrFail(key: string, label?: string): string;
  getRomanQualityOrFail(quality: string, label?: string): string;
  hasDiatonicKeyData(key: string, quality?: string): boolean;
  getProgressionKeyPoolOrFail(quality?: string): string[];
  resolveProgressionKeyOrFail(key: string, label?: string, quality?: string): string;
  create(config?: Record<string, any>, ctx?: any): any;
  resolveComposerPoolName(extraConfig?: Record<string, any>, composerCtx?: any): string;
  getComposerFamiliesOrFail(): Record<string, any>;
  resolvePhraseFamilyOrFail(extraConfig?: Record<string, any>, composerCtx?: any): string;
  getActiveFamily(): string;
  inferComposerType(composerInstance: any): string;
  scoreFamilyCandidateConfig(candidateConfig: any, opts?: any): number;
  pickWeightedFamilyCandidateOrFail(candidateConfigs: any[], opts?: any): any;
  createRandomForLayer(opts?: { familyName?: string; layerName?: string; extraConfig?: Object; previousComposer?: Object; peerComposer?: Object }, ctx?: any): any;
}

interface VoiceManagerAPI {
  voiceHistoryByLayer: Map<string, number[][]>;
  getVoiceCount(unit?: string): number;
  pickNotesForBeat(layer: any, candidateNotes: any[], voiceCount: number, scorer: any, opts?: Record<string, any>): number[];
  resetLayer(layer: any): void;
  resetAll(): void;
}

interface StutterManagerAPI {
  shared: { shifts: Map<any, any>; global: any };
  beatContext: any;
  plans: Map<any, any>;
  scheduledPlans: Map<any, any>;
  config: any;
  defaultDirective: any;
  setDefaultDirective(directive: Record<string, any>): any;
  stutterFade(...args: any[]): any;
  stutterPan(...args: any[]): any;
  stutterFX(...args: any[]): any;
  createPlan(planCfg?: Record<string, any>): any;
  schedulePlan(planOrCfg?: Record<string, any>): any;
  runPlan(planIdOrCfg?: Record<string, any>): any;
  cancelPlan(planId: any): any;
  runDuePlans(absoluteSeconds: number): any;
  scheduleStutterForUnit(opts?: Record<string, any>): any;
  prepareBeat(beatStartTime?: number): any;
  resetChannelTracking(channels?: number[] | null): { cleared: number; lastUsedCHs?: number; lastUsedCHs2?: number; lastUsedCHs3?: number };
}

//
// Gradient typing: config shapes, profile records, accessor APIs, conductor
// intelligence module surfaces, and feedback infrastructure
//

/** Config-level range used by SECTIONS, DIVISIONS, VOICES, etc. */
interface WeightedRange {
  min: number;
  max: number;
  weights?: number[];
}

// -- Profile record shapes --

interface VoiceProfile {
  baseVelocity: number;
  useCorpusVoiceLeadingPriors?: boolean;
  corpusVoiceLeadingStrength?: number;
  useCorpusMelodicPriors?: boolean;
  corpusMelodicStrength?: number;
}

interface ChordProfile {
  voices: number;
  velocityScale: number;
  inversion: number;
  baseVelocity: number;
  useCorpusHarmonicPriors?: boolean;
  corpusHarmonicStrength?: number;
}

interface MotifProfile {
  velocityScale: number;
  timingOffset: number;
}

interface RhythmProfile {
  swing: number;
  velocityScale: number;
  useCorpusRhythmPriors?: boolean;
  corpusRhythmStrength?: number;
}

interface MotifUnitProfile {
  density: number;
  style: string;
  intervalDensity: number;
  velocityScale: number;
}

// -- Config accessor APIs --

interface RhythmConfigAPI {
  getProfile(name: string): RhythmProfile;
}

interface VoiceConfigAPI {
  getProfile(name: string): VoiceProfile;
}

interface MotifConfigAPI {
  getProfile(name: string): MotifProfile;
  getUnitProfile(unit: string): MotifUnitProfile;
  setUnitProfileOverride(unit: string, props: Partial<MotifUnitProfile>): void;
}

interface ChordConfigAPI {
  getProfile(name: string): ChordProfile;
}

// -- Feedback infrastructure --

interface FeedbackRegistryAPI {
  registerLoop(name: string, sourceDomain: string, targetDomain: string, getAmplitude: () => number, getPhase: () => number): void;
  getResonanceDampening(name: string): number;
  getSnapshot(): { [name: string]: { source: string; target: string; amplitude: number; phase: number; dampening: number } };
}

// -- Conductor intelligence module APIs --

interface MelodicContourTrackerAPI {
  update(): void;
  getContour(): { shape: string; direction: number; range: number; avgPitch: number };
  getContrastingSuggestion(): { preferredDirection: number; bias: string };
  getLayerContour(layer: string): { shape: string; direction: number; range: number; avgPitch: number };
  getDirectionalitySignal(): { direction: string; ascendRatio: number; descendRatio: number; densityBias: number };
  getDirectionalityDensityBias(): number;
  getDirectionalityFlickerBias(): number;
  getDirectionalityTensionBias(): number;
  reset(): void;
}

interface RegisterPressureMonitorAPI {
  getRegisterPressure(opts?: { layer?: string; windowSeconds?: number }): number[];
  getCrossLayerOverlap(windowSeconds?: number): number;
  getRegisterBias(layer: string): { octaveBias: number; crowdedBands: number[]; emptyBands: number[] };
  getPressureSignal(opts?: { windowSeconds?: number }): { highPressure: boolean; lowPressure: boolean };
}

interface LayerCoherenceScorerAPI {
  computeCoherence(windowSeconds?: number): number;
  getCoherence(): number;
  isInTension(threshold?: number): boolean;
  getDensityBias(): number;
  reset(): void;
}

interface CadenceAdvisorAPI {
  initialize(): void;
  shouldCadence(): { suggest: boolean; type: string; confidence: number };
  getCadenceBias(): { dominantBias: number; tonicBias: number; phase: string };
  getHarmonicDensity(): number;
  reset(): void;
}

// -- utils --
declare var m: typeof Math;
declare var rf: (min1?: number, max1?: number, min2?: number, max2?: number) => number;
declare var ri: (min1?: number, max1?: number, min2?: number, max2?: number) => number;
declare var rw: (min: number, max: number, weights?: number[]) => number;
declare var ra: (v: number | any[] | (() => any)) => any;
declare var rv: (value: number, boostRange?: number[], frequency?: number, deboostRange?: number[]) => number;
declare var rl: (currentValue: number, minChange: number, maxChange: number, minValue: number, maxValue: number, type?: string) => number;
declare var clamp: (value: number, min: number, max: number) => number;
declare var modClamp: (value: number, min: number, max: number) => number;
declare var lowModClamp: (value: number, min: number, max: number) => number;
declare var highModClamp: (value: number, min: number, max: number) => number;
declare var scaleClamp: (value: number, min: number, max: number, factor: number, maxFactor?: number, base?: number) => number;
declare var scaleBoundClamp: (value: number, base: number, lowerScale: number, upperScale: number, minBound?: number, maxBound?: number) => number;
declare var softClamp: (value: number, min: number, max: number, softness?: number) => number;
declare var stepClamp: (value: number, min: number, max: number, step: number) => number;
declare var logClamp: (value: number, min: number, max: number, base?: number) => number;
declare var expClamp: (value: number, min: number, max: number, base?: number) => number;
declare var randomWeightedInArray: (weights: number[]) => number;
declare var randomWeightedSelection: (options: Record<string, { weights: number[] }>) => string;
declare var normalizeWeights: (weights: number[], min: number, max: number, variationLow?: number, variationHigh?: number) => number[];
declare var MIDI_MAX_VALUE: number;
declare var midiData: any;
declare var getMidiValue: any;
declare var allCHs: number[];
declare var allNotes: string[];
declare var allScales: string[];
declare var allChords: string[];
declare var allModes: string[];
declare var cCH1: number;
declare var source: any;
declare var source2: any;
declare var reflection: any;
declare var bass: any;
declare var rlFX: any;
declare var setTuningAndInstruments: any;
declare var stutterFadeCHs: any;
declare var stutterPanCHs: any;
declare var chFX: any;
declare var flipBinT: any;
declare var flipBinF: any;
declare var flipBinT3: any;
declare var flipBinF3: any;
declare var flipBinF2: any;
declare var flipBinT2: any;
declare var reflectionBinaural: any;
declare var reflect: any;
declare var reflect2: any;
declare var binauralL: any;
declare var binauralR: any;
declare var binauralOffset: any;
declare var bassBinaural: any;
declare var crossModulation: any;
declare var lastMeter: any;
declare var lastUsedCHs: any;
declare var lastUsedCHs2: any;
declare var lastUsedCHs3: any;
declare var remainingVoiceSlotsByLayer: any;
declare var lastVoiceBudgetKeyByLayer: any;
declare var neutralPitchBend: any;
declare var semitone: any;
declare var tuningPitchBend: any;
declare var FX: any;
declare var COMPOSER_TYPE_PROFILE_SOURCES: any;
declare var allNotesOff: any;
declare var muteAll: any;
declare var setOtherInstruments: any;
declare var validator: ValidatorFactory;
declare var systemSnapshot: any;
declare var modeQualityMap: any;
declare var priorsHelpers: any;

// -- conductor --
declare var BPM: number;
declare var PPQ: number;
declare var currentDensity: number;
declare var TUNING_FREQ: number;
declare var LOG: any;
declare var BINAURAL: WeightedRange;
declare var SILENT_OUTRO_SECONDS: number;
declare var SECTIONS: WeightedRange;
declare var PHRASES_PER_SECTION: WeightedRange;
declare var NUMERATOR: WeightedRange;
declare var DENOMINATOR: WeightedRange;
declare var DIVISIONS: WeightedRange;
declare var SUBDIVS: WeightedRange;
declare var VOICES: WeightedRange;
declare var BEAT_VOICES: WeightedRange;
declare var DIV_VOICES: WeightedRange;
declare var SUBDIV_VOICES: WeightedRange;
declare var SUBSUBDIV_VOICES: WeightedRange;
declare var BEAT_SIBLING_VOICES: any;
declare var DIV_SIBLING_VOICES: any;
declare var SUBDIV_SIBLING_VOICES: any;
declare var SUBSUBDIV_SIBLING_VOICES: any;
declare var OCTAVE: WeightedRange;
declare var primaryInstrument: any;
declare var secondaryInstrument: any;
declare var otherInstruments: any;
declare var bassInstrument: any;
declare var bassInstrument2: any;
declare var otherBassInstruments: any;
declare var drumSets: any;
declare var PhraseArcManager: { new(opts?: Record<string, any>): PhraseArcManagerAPI };
declare var phraseArcProfiler: any;
declare var harmonicContext: HarmonicContextAPI;
declare var harmonicJourney: HarmonicJourneyAPI;
declare var harmonicRhythmTracker: HarmonicRhythmTrackerAPI;
declare var harmonicJourneyHelpers: any;
declare var harmonicJourneyPlanner: any;
declare var dynamismEngine: DynamismEngineAPI;
declare var dynamismPulse: any;
declare var textureBlender: TextureBlenderAPI;
declare var conductorState: ConductorStateAPI;
declare var VOICE_PROFILES: Record<string, VoiceProfile>;
declare var CHORD_PROFILES: Record<string, ChordProfile>;
declare var MOTIF_PROFILES: Record<string, MotifProfile>;
declare var RHYTHM_PROFILES: Record<string, RhythmProfile>;
declare var RHYTHM_PATTERNS: any;
declare var RHYTHM_PATTERN_POOLS: any;
declare var DRUM_MAP: any;
declare var FX_CC_DEFAULTS: any;
declare var NOISE_GENERATOR_REGISTRY: any;
declare var PHRASES_ARC_CURVES: any;
declare var MODAL_BORROWING: any;
declare var NOISE_PROFILES: any;
declare var COMPOSER_FAMILIES: any;
declare var VOICE_MANAGER: any;
declare var SECTION_TYPES: any;
declare var SUBSUBDIVS: WeightedRange;
declare var DYNAMISM: any;
declare var STUTTER_PROFILES: any;
declare var STUTTER_VELOCITY_RANGES: any;
declare var STUTTER_CROSSMOD_RULES: any;
declare var STUTTER_CROSSMOD_RULES_FALLBACK: any;
declare var STUTTER_PRESETS: any;
declare var STUTTER_DIRECTIVE_DEFAULTS: any;
declare var MOTIF_UNIT_PROFILES: any;
declare var CONDUCTOR_DYNAMICS_CONTROLS: any;
declare var MAIN_LOOP_CONTROLS: any;
declare var CONDUCTOR_NOISE_PROFILE_BY_PHASE: any;
declare var CONDUCTOR_PROFILE_SOURCES: any;
declare var conductorProfileDefault: any;
declare var conductorProfileRestrained: any;
declare var conductorProfileExplosive: any;
declare var conductorProfileAtmospheric: any;
declare var conductorProfileRhythmicDrive: any;
declare var conductorProfileMinimal: any;
declare var conductorConfigTuningDefaults: any;
declare var conductorConfigTuningOverrides: any;
declare var conductorConfigMergeProfileTuning: any;
declare var conductorConfigValidateProfile: any;
declare var conductorConfigDynamics: any;
declare var conductorConfigResolvers: any;
declare var conductorConfigAccessors: any;
declare var conductorConfig: ConductorConfigAPI;
declare var globalConductor: GlobalConductorAPI;
declare var melodicContourTracker: MelodicContourTrackerAPI;
declare var registerPressureMonitor: RegisterPressureMonitorAPI;
declare var layerCoherenceScorer: LayerCoherenceScorerAPI;
declare var cadenceAdvisor: CadenceAdvisorAPI;
declare var sectionLengthAdvisor: any;
declare var dynamicRangeTracker: any;
declare var restDensityTracker: any;
declare var intervalBalanceTracker: any;
declare var interLayerRhythmAnalyzer: any;
declare var harmonicVelocityMonitor: any;
declare var texturalMemoryAdvisor: any;
declare var composerFeedbackAdvisor: ComposerFeedbackAdvisorAPI;
declare var pitchGravityCenter: any;
declare var onsetDensityProfiler: any;
declare var syncopationDensityTracker: any;
declare var grooveTemplateAdvisor: any;
declare var structuralFormTracker: any;
declare var voiceDensityBalancer: any;
declare var accentPatternTracker: any;
declare var modalColorTracker: any;
declare var repetitionFatigueMonitor: any;
declare var energyMomentumTracker: any;
declare var articulationProfiler: any;
declare var registerMigrationTracker: any;
declare var rhythmicComplexityGradient: any;
declare var climaxProximityPredictor: any;
declare var onsetRegularityMonitor: any;
declare var durationalContourTracker: any;
declare var harmonicSurpriseIndex: any;
declare var counterpointMotionTracker: any;
declare var consonanceDissonanceTracker: any;
declare var velocityShapeAnalyzer: any;
declare var pitchClassHelpers: any;
declare var octaveSpreadMonitor: any;
declare var motivicDensityTracker: any;
declare var pedalPointDetector: any;
declare var phraseLengthMomentumTracker: any;
declare var tensionResolutionTracker: any;
declare var octaveHelpers: any;
declare var densityWaveAnalyzer: any;
declare var timbreBalanceTracker: any;
declare var harmonicRhythmDensityRatio: any;
declare var thematicRecallDetector: any;
declare var beatGridHelpers: any;
declare var interLayerRhythmHelpers: any;
declare var layerIndependenceScorer: any;
declare var temporalProportionTracker: any;
declare var chromaticSaturationMonitor: any;
declare var fragmentHelpers: any;
declare var analysisHelpers: any;
declare var propertyExtractors: any;
declare var rhythmicSymmetryDetector: any;
declare var texturalGradientTracker: any;
declare var cadentialPreparationAdvisor: any;
declare var ambitusMigrationTracker: any;
declare var silenceDistributionTracker: any;
declare var voiceLeadingEfficiencyTracker: any;
declare var rhythmicGroupingAnalyzer: any;
declare var dynamicArchitectPlanner: any;
declare var tessituraPressureMonitor: any;
declare var harmonicFieldDensityTracker: any;
declare var orchestrationWeightTracker: any;
declare var rhythmicInertiaTracker: any;
declare var pitchClassGravityMap: any;
declare var intervalDirectionMemory: any;
declare var crossLayerDensityBalancer: any;
declare var harmonicPedalFieldTracker: any;
declare var registralVelocityCorrelator: any;
declare var phraseContourArchetypeDetector: any;
declare var harmonicDensityOscillator: any;
declare var attackDensityProfiler: any;
declare var layerEntryExitTracker: any;
declare var intervalExpansionContractor: any;
declare var dynamicPeakMemory: any;
declare var rhythmicDensityContrastTracker: any;
declare var tonalAnchorDistanceTracker: any;
declare var conductorIntelligence: ConductorIntelligenceAPI;
declare var conductorRecorderRegistry: {
  registerRecorder(name: string, fn: (ctx: RecorderContext) => void): void;
  runRecorders(ctx: RecorderContext): void;
  getNames(): string[];
  getCount(): number;
};
declare var conductorStateProviderRegistry: {
  registerStateProvider(name: string, getter: () => Record<string, unknown>): void;
  collectStateFields(): Record<string, unknown>;
  getNames(): string[];
  getCount(): number;
};
declare var conductorDiagnostics: {
  create(
    biasArrays: { density: Array<{name:string}>; tension: Array<{name:string}>; flicker: Array<{name:string}> },
    collectors: { collectDensityBias: () => number; collectTensionBias: () => number; collectFlickerModifier: () => number }
  ): {
    getContributorNames(): string[];
    getCounts(): { density: number; tension: number; flicker: number; recorders: number; stateProviders: number };
    getRegistryNames(): { density: string[]; tension: string[]; flicker: string[]; recorders: string[]; stateProviders: string[] };
    getSignalSnapshot(): Readonly<SignalSnapshot>;
  };
};
declare var conductorDampening: {
  scaledDamping(registryLength: number, pipelineName?: string): number;
  progressiveDampen(clamped: number, baseDamping: number, runningProduct: number): number;
  collectDampened(registry: Array<{ name: string; getter: () => number; lo: number; hi: number }>, pipelineName?: string): number;
  collectDampenedWithAttribution(registry: Array<{ name: string; getter: () => number; lo: number; hi: number }>, pipelineName?: string): { product: number; contributions: Array<{ name: string; raw: number; clamped: number }> };
  setFlickerTargetRange(target: number): void;
};
declare var sectionMemory: {
  snapshot(): void;
  seed(): void;
  getPrevious(): { energy: number; tension: number; density: number; flicker: number; trend: string; regime?: string } | null;
  reset(): void;
};
declare var coherenceMonitor: CoherenceMonitorAPI;
declare var signalReader: SignalReaderAPI;
declare var profileAdaptation: ProfileAdaptationAPI;
declare var signalTelemetry: SignalTelemetryAPI;
declare var signalHealthAnalyzer: SignalHealthAnalyzerAPI;
declare var phaseSpaceMath: {
  magnitude(v: number[]): number;
  cosine(a: number[], b: number[]): number;
  stats(data: number[][], nDims: number): { mean: number[]; variance: number[] };
  coupling(data: number[][], mean: number[], dimNames: string[], nDims: number, nCompositional: number, varianceGateThreshold?: number): { matrix: Record<string, number>; strength: number };
  jacobiEigenvalues(A: number[][], K: number): number[];
  effectiveDimensionality(data: number[][], mean: number[], nCompositional: number): number;
};
declare var entropyAmplificationController: {
  adapt(currentShare: number): void;
  getAmp(): number;
  reset(): void;
};
declare var regimeClassifierHelpers: any;
declare var regimeClassifierClassification: any;
declare var regimeClassifierResolution: any;
declare var regimeClassifier: {
  classify(avgVelocity: number, avgCurvature: number, effectiveDim: number, couplingStrength: number): string;
  resolve(rawRegime: string, tickId?: number): string;
  grade(regime: string): string;
  setOscillatingThreshold(threshold: number): void;
  getOscillatingThreshold(): number;
  setCoherentThresholdScale(scale: number): void;
  setCoherentShareAlphaMin(alphaMin: number): void;
  setEvolvingMinDwell(minDwell: number): void;
  getExploringBeats(): number;
  getLastRegime(): string;
  getTransitionReadiness(): { gap: number; couplingStrength: number; coherentThreshold: number; velocity: number; velThreshold: number; thresholdScale: number; velocityBlocked: boolean; exploringBlock: string; coherentBlock: string; evolvingBeats: number; coherentBeats: number; runCoherentBeats: number; maxCoherentBeats: number; runBeatCount: number; runTickCount: number; runCoherentShare: number; runTransitionCount: number; forcedBreakCount: number; forcedRegime: string; forcedRegimeBeatsRemaining: number; forcedOverrideActive: boolean; forcedOverrideBeats: number; lastForcedReason: string; lastForcedTriggerStreak: number; lastForcedTriggerBeat: number; lastForcedTriggerTick: number; postForcedRecoveryBeats: number; tickSource: string; rawRegimeCounts: Record<string, number>; runRawRegimeCounts: Record<string, number>; rawRegimeMaxStreak: Record<string, number>; runResolvedRegimeCounts: Record<string, number>; effectiveDim: number; cadenceMonopolyPressure: number; cadenceMonopolyActive: boolean; cadenceMonopolyReason: string; rawExploringShare: number; rawEvolvingShare: number; rawNonCoherentOpportunityShare: number; resolvedNonCoherentShare: number; opportunityGap: number };
  consumeForcedTransitionEvent(): ForcedTransitionEvent | null;
  reset(): void;
};
declare var systemDynamicsProfilerHelpers: any;
declare var systemDynamicsProfilerAnalysis: any;
declare var systemDynamicsProfiler: SystemDynamicsProfilerAPI;
declare var regimeReactiveDampingEquilibrator: any;
declare var regimeReactiveDamping: { densityBias(): number; tensionBias(): number; flickerMod(): number; reset(): void };
declare var pipelineBalancer: { densityBias(): number; reset(): void };
declare var pipelineNormalizer: { normalize(pipeline: string, rawProduct: number): number; reset(): void; getSnapshot(): Record<string, object> };
declare var pipelineCouplingManagerSnapshot: any;
declare var couplingConstants: any;
declare var couplingState: any;
declare var couplingRefreshSetup: any;
declare var couplingBudgetScoring: any;
declare var couplingGainEscalation: any;
declare var pairGainCeilingController: { updatePair(pair: string, p95: number, hotspotRate: number, severeRate: number): void; getCeiling(pair: string): number; getInstantCeiling(pair: string, p95: number, severeRate: number, hotspotRate: number): number; getSnapshot(): Record<string, any>; reset(): void };
declare var warmupRampController: { recordS0Exceedance(pair: string): void; getWarmupBeats(pair: string): number; getWarmupCeiling(pair: string, sectionBeat: number): number; getSnapshot(): any; reset(): void };
declare var couplingEffectiveGain: any;
declare var couplingBiasAccumulator: any;
declare var pipelineCouplingManager: { densityBias(): number; tensionBias(): number; flickerBias(): number; setDensityFlickerGainScale(scale: number): void; setGlobalGainMultiplier(scale: number): void; setPairBaseline(pairKey: string, newBaseline: number): void; getPairBaselines(): Record<string, number>; getAdaptiveTargetSnapshot(): Record<string, { baseline: number; current: number; rollingAbsCorr: number; rawRollingAbsCorr: number; p95AbsCorr: number; hotspotRate: number; severeRate: number; recentP95AbsCorr: number; recentHotspotRate: number; recentSevereRate: number; telemetryWindowBeats: number; residualPressure: number; gain: number; effectiveGain: number; nudgeable: boolean; budgetScore: number; budgetBoost: number; budgetRank: number | null; heatPenalty: number; effectivenessEma: number; effMin: number; effMax: number; effActiveBeats: number; hpPromoted: boolean }>; getAxisCouplingTotals(): Record<string, number>; getAxisEnergyShare(): { shares: Record<string, number>; axisGini: number }; getCouplingGates(): { gateD: number; gateT: number; gateF: number; floorDampen: number; bypassD: number; bypassT: number; bypassF: number; gateMinD: number; gateMinT: number; gateMinF: number; gateEmaD: number; gateEmaT: number; gateEmaF: number; gateBeatCount: number }; reset(): void };
declare var couplingHomeostasisSnapshot: any;
declare var homeostasisConstants: any;
declare var homeostasisState: any;
declare var homeostasisFloor: any;
declare var homeostasisTick: any;
declare var homeostasisRefresh: any;
declare var couplingHomeostasis: { getState(): { totalEnergyEma: number; energyBudget: number; peakEnergyEma: number; redistributionScore: number; nudgeableRedistributionScore: number; budgetConstraintActive: boolean; budgetConstraintPressure: number; globalGainMultiplier: number; giniCoefficient: number; energyDeltaEma: number; pairTurbulenceEma: number; beatCount: number; invokeCount: number; tickCount: number; emptyMatrixBeats: number; multiplierMin: number; multiplierMax: number; multiplierStdDev: number; floorContactBeats: number; ceilingContactBeats: number; avgRecoveryDuration: number; totalEnergyFloor: number; floorDampen: number; floorRecoveryActive: boolean; floorRecoveryTicksRemaining: number; densityFlickerTailPressure: number; densityFlickerOverridePressure: number; recoveryAxisHandOffPressure: number; shortRunRecoveryBias: number; nonNudgeableTailPressure: number; nonNudgeableTailPair: string; recoveryDominantAxes: string[]; stickyTailPressure: number; tailRecoveryDrive: number; tailRecoveryTrigger: number; tailRecoveryHandshake: number; tailRecoveryCap: number; tailRecoveryCeilingPressure: number; densityFlickerClampPressure: number; dominantTailPair: string; tailHotspotCount: number; tailPressureByPair: Record<string, number> }; reset(): void; tick(): void; getFloorDampen(): number };
declare var phaseFloorController: { getCollapseThreshold(): number; getLowShareThreshold(): number; getFloorActivationStreak(): number; getExtremeCollapseStreak(): number; computeBoosts(share: number, phaseLowShareStreak: number, phaseCollapseStreak: number): { phaseCollapseBoost: number; phaseFloorBoost: number }; isFloorActive(phaseLowShareStreak: number): boolean; isExtremeCollapse(share: number, phaseLowShareStreak: number): boolean; recordBoostApplied(boost: number): void; getSnapshot(): any };
declare var axisEnergyEquilibratorHelpers: any;
declare var axisEnergyEquilibratorRefreshContext: any;
declare var axisEnergyEquilibratorPairAdjustments: any;
declare var axisEnergyEquilibratorAxisAdjustments: any;
declare var axisEnergyEquilibrator: { getSnapshot(): { beatCount: number; pairAdjustments: number; axisAdjustments: number; smoothedShares: Record<string, number>; perAxisAdj: Record<string, number>; perPairAdj: Record<string, number>; lastBaselines: Record<string, number>; regimeBeats: Record<string, number>; regimePairAdj: Record<string, number>; regimeAxisAdj: Record<string, number>; regimeTightenBudget: Record<string, number>; coherentFreezeBeats: number; skippedColdspotRelaxations: number; phaseSurfaceHotBeats: number; trustSurfaceHotBeats: number; entropySurfaceHotBeats: number; coherentHotspotActuationBeats: number; coherentHotspotPairAdj: number; coherentHotspotAxisAdj: number; warmupTicks: number; warmupRemaining: number; coldspotSkipReasons: { coherentFreeze: number; phaseHot: number; trustHot: number; residual: number } }; reset(): void };
declare var narrativeTrajectory: { getTrajectory(): { point: { t: number; n: number; d: number }; velocity: number; curvature: number; length: number }; tensionBias(): number; reset(): void };
declare var structuralNarrativeAdvisor: { recordFamily(family: string): void; getHistory(): string[]; getVarietyPressure(): number; densityBias(): number; reset(): void };
declare var criticalityEngine: { densityBias(): number; tensionBias(): number; flickerMod(): number; getState(): { threshold: number; avalancheCount: number; totalBeats: number; rate: number; inAvalanche: boolean; recentEnergy: number }; reset(): void };
declare var moduleLifecycle: ModuleLifecycleFactory;
declare var feedbackRegistry: FeedbackRegistryAPI;
declare var closedLoopController: ClosedLoopControllerFactory;
declare var beatCache: BeatCacheFactory;

// -- rhythm --
declare var rhythmRegistry: RhythmRegistryAPI;
declare var RhythmManager: RhythmManagerAPI;
declare var rhythmValues: RhythmValuesAPI;
declare var rhythmConfig: RhythmConfigAPI;
declare var rhythmModulator: any;
declare var RHYTHM_PRIOR_TABLES: any;
declare var rhythmPriors: any;
declare var phaseLockedRhythmGenerator: PhaseLockedRhythmGeneratorAPI;
declare var FXFeedbackListener: any;
declare var stutterFeedbackListener: any;
declare var journeyRhythmCoupler: any;
declare var emissionFeedbackListener: any;
declare var feedbackAccumulator: any;
declare var drumTextureCoupler: any;
declare var conductorRegulationListener: any;
declare var setRhythm: any;
declare var _rp: any;
declare var _binary: any;
declare var _random: any;
declare var rotate: any;
declare var lastCrossMod: number;
declare var playDrums: any;
declare var playDrums2: any;
declare var binary: any;
declare var hex: any;
declare var onsets: any;
declare var random: any;
declare var prob: any;
declare var euclid: any;
declare var morph: any;
declare var closestDivisor: any;
declare var rhythmMethods: any;
declare var makeOnsets: any;
declare var patternLength: any;
declare var drumMap: any;
declare var drummer: any;
declare var getRhythm: any;
declare var rhythms: any;
declare var trackRhythm: any;
declare var crossModulateRhythms: any;
declare var rhythmHistoryTracker: any;

// -- time --
declare var bpmRatio: number;
declare var bpmRatio2: any;
declare var bpmRatio3: any;
declare var numerator: number;
declare var denominator: number;
declare var meterRatio: number;
declare var beatRhythm: number;
declare var divRhythm: number;
declare var subdivRhythm: number;
declare var subsubdivRhythm: number;
declare var measuresPerPhrase1: number;
declare var measuresPerPhrase2: number;
declare var measureStartTime: number;
declare var beatStartTime: number;
declare var divStartTime: number;
declare var subdivStartTime: number;
declare var subsubdivStartTime: number;
declare var c: any;
declare var LM: LayerManagerAPI;
declare var getMidiTiming: any;
declare var setMidiTiming: any;
declare var POLYRHYTHM_PAIRS: any;
declare var getMeterPair: { pick: () => void; reset: () => void };
declare var getPolyrhythm: any;
declare var setUnitTiming: any;
declare var bestMatch: number;
declare var subsubsPerSub: number;
declare var spUnit: number;
declare var unitIndex: number;
declare var unitStartTime: number;
declare var spParent: number;
declare var unitsPerParent: number;
declare var spPhrase: number;
declare var phraseStartTime: number;
declare var spSection: number;
declare var sectionStartTime: number;
declare var spMeasure: number;
declare var spBeat: any;
declare var subdivsPerMinute: number;
declare var subsubsPerMinute: number;
declare var subdivFreq: any;
declare var divsPerBeat: number;
declare var subdivsPerDiv: number;
declare var spDiv: any;
declare var spSubdiv: any;
declare var spSubsubdiv: any;
declare var trueBPM: any;
declare var trueBPM2: any;
declare var polyMeterRatio: number;
declare var midiMeter: any;
declare var midiMeterRatio: any;
declare var midiBPM: any;
declare var syncFactor: any;
declare var timeGridPrune: any;
declare var timeGridSearchStart: any;
declare var L0: {
  post(channel: string, layer: string, timeInSeconds: number, data?: Record<string, unknown>): void;
  query(channel: string, opts?: { layer?: string; since?: number; windowSeconds?: number; aroundSeconds?: number; toleranceSec?: number }): any[];
  findClosest(channel: string, timeInSeconds: number, toleranceSec: number, excludeLayer?: string): any | null;
  count(channel: string, opts?: { layer?: string; since?: number; windowSeconds?: number }): number;
  getLast(channel: string, opts?: { layer?: string; since?: number; windowSeconds?: number }): any | null;
  getBounds(channel: string, opts?: { layer?: string; since?: number; windowSeconds?: number }): { count: number; first: any | null; last: any | null };
  reset(channel?: string): void;
  getBuffer(): any[];
  channels: Record<string, any[]>;
};
declare var tempoFeelEngine: TempoFeelEngineAPI;
declare var timeStream: TimeStreamAPI;
declare var fractalArcGenerator: { intensity(levelIdx: number): number; composite(): number; arcShape(progress: number): number; reset(): void };

// -- composers --
declare var normalizeChordSymbol: any;
declare var MeasureComposer: any;
declare var ScaleComposer: any;
declare var RandomScaleComposer: any;
declare var ChordComposer: any;
declare var RandomChordComposer: any;
declare var ModeComposer: any;
declare var RandomModeComposer: any;
declare var TensionReleaseComposer: any;
declare var ModalInterchangeComposer: any;
declare var HarmonicRhythmComposer: any;
declare var melodicDevelopmentVoicingIntent: (candidateNotes: any[], lastBaseNotes: any[], lastDevelopedNotes: any[], developmentBias: number, intensity: number, currentPhase: number) => { candidateWeights: { [note: number]: number } } | null;
declare var MelodicDevelopmentComposer: any;
declare var VoiceLeadingComposer: any;
declare var MotifComposer: any;
declare var Motif: any;
declare var motifTransforms: any;
declare var measureNotePool: any;
declare var motifValidators: any;
declare var registerBiasing: any;
declare var candidateExpansion: any;
declare var playMotifs: any;
declare var playMotifsResolveBucket: any;
declare var playMotifsBuildCandidateNotes: any;
declare var playMotifsApplyCycleTransforms: any;
declare var PentatonicComposer: any;
declare var RandomPentatonicComposer: any;
declare var BluesComposer: any;
declare var RandomBluesComposer: any;
declare var ChromaticComposer: any;
declare var RandomChromaticComposer: any;
declare var QuartalComposer: any;
declare var RandomQuartalComposer: any;
declare var intervalComposer: any;
declare var factoryProfiles: any;
declare var factoryProgression: any;
declare var factoryPoolResolver: any;
declare var factoryFamilies: any;
declare var factoryConstructors: any;
declare var motifChain: MotifChainAPI;
declare var ProgressionGenerator: any;
declare var pivotChordBridge: any;
declare var HARMONIC_PRIOR_TABLES: any;
declare var harmonicPriors: any;
declare var chordRegistry: any;
declare var ChordManager: any;
declare var chordValues: any;
declare var chordConfig: ChordConfigAPI;
declare var chordModulator: any;
declare var motifRegistry: any;
declare var motifManager: MotifManagerAPI;
declare var motifValues: any;
declare var motifConfig: MotifConfigAPI;
declare var motifModulator: any;
declare var voiceRegistry: any;
declare var voiceValues: any;
declare var voiceConfig: VoiceConfigAPI;
declare var voiceModulator: any;
declare var voiceLeadingScorers: any;
declare var voiceLeadingCore: any;
declare var VOICE_LEADING_PRIOR_TABLES: any;
declare var voiceLeadingPriors: any;
declare var MELODIC_PRIOR_TABLES: any;
declare var melodicPriors: any;
declare var voiceLeadingSelectNextNote: any;
declare var voiceLeadingAnalyzeQuality: any;
declare var VoiceManager: { new(): VoiceManagerAPI };
declare var getScheduledNotes: any;
declare var p: any;
declare var note: any;
declare var applyComposerPitchNoise: any;
declare var applyMelodicTranspositionNoise: any;
declare var assertComposerCapabilities: any;
declare var resolveScalePC: any;
declare var midiToDegree: any;
declare var degreeToMidi: any;
declare var transposeByDegree: any;
declare var scaleNormalization: any;
declare var scaleDegreeTranspose: any;
declare var applyMelodicPivotNoise: any;
declare var applyMelodicDurationNoise: any;
declare var applyVoiceLeadingWeightNoise: any;
declare var activeMotif: any;
declare var main: any;
declare var composerProfileUtils: any;
declare var composerProfileValidation: any;
declare var COMPOSER_TYPES: any;
declare var composerRuntimeProfileAdapter: any;
declare var COMPOSER_PROFILE_POOLS: any;
declare var COMPOSER_POOL_SELECTION_STRATEGY: any;
declare var COMPOSER_TYPE_PROFILES: any;
declare var selectComposerPoolOrFail: any;
declare var getComposerPoolOrFail: any;
declare var getDefaultComposerPoolOrFail: any;
declare var getComposerTypeProfilesOrFail: any;
declare var getComposerTypeProfileOrFail: any;
declare var motifSpreader: any;
declare var applyMotifToNotes: any;
declare var motifTransformAdvisor: any;

// -- fx --
declare var lBal: number;
declare var rBal: number;
declare var cBal: number;
declare var refVar: any;
declare var bassVar: any;
declare var balOffset: number;
declare var stutterFade: any;
declare var stutterPan: any;
declare var stutterFX: any;
declare var stutterExecutePlan: any;
declare var stutterNotes: any;
declare var pickStutterChannels: any;
declare var stutterRegistry: any;
declare var stutterMetrics: any;
declare var stutterConfig: any;
declare var stutterPlanScheduler: any;
declare var StutterManager: StutterManagerAPI;
declare var setBalanceAndFX: any;
declare var setBinaural: any;
declare var fbm: any;
declare var turbulence: any;
declare var ridged: any;
declare var worley: any;
declare var easeInOut: any;
declare var easingFunctions: any;
declare var noiseFunctions: any;
declare var metaRecursiveEaseNoise: any;
declare var metaRecursiveNoise: any;
declare var metaRecursiveSimplex2D: any;
declare var metaRecursiveFBM: any;
declare var permutation: any;
declare var fade: any;
declare var lerp: any;
declare var grad: any;
declare var perlinNoise: any;
declare var defaultSimplex: any;
declare var noiseGenerators: any;
declare var generatorKeys: any;
declare var getNoiseValue: any;
declare var layeredNoise: any;
declare var createNoiseOffset: any;
declare var randomNoiseGenerator: any;
declare var noiseInfluenceMap: any;
declare var createDualAxisNoiseConfig: any;
declare var applyDualAxisNoise: any;
declare var safeApplyNoise: any;
declare var clampNoiseValue: any;
declare var getParameterModulation: any;
declare var smoothNoiseValue: any;
declare var getNoiseProfile: any;
declare var registerNoiseGenerator: any;
declare var applyNoiseToVelocity: any;
declare var applyNoiseToPan: any;
declare var applyNoiseToSustain: any;
declare var applyNoiseToParameter: any;
declare var getNoiseProfileOrFail: any;
declare var flipBin: any;
declare var binauralFreqOffset: any;
declare var beatCount: number;
declare var sideBias: number;
declare var stutterFailFast: any;

// -- crossLayer --
declare var t: any;
declare var stutterContagion: StutterContagionAPI;
declare var convergenceDetector: ConvergenceDetectorAPI;
declare var temporalGravity: TemporalGravityAPI;
declare var velocityInterference: VelocityInterferenceAPI;
declare var feedbackOscillator: FeedbackOscillatorAPI;
declare var cadenceAlignment: CadenceAlignmentAPI;
declare var rhythmicPhaseLock: RhythmicPhaseLockAPI;
declare var spectralComplementarity: SpectralComplementarityAPI;
declare var dynamicRoleSwap: DynamicRoleSwapAPI;
declare var motifEcho: MotifEchoAPI;
declare var interactionHeatMap: InteractionHeatMapAPI;
declare var entropyMetrics: EntropyMetricsAPI;
declare var entropyRegulator: EntropyRegulatorAPI;
declare var emergentDownbeat: EmergentDownbeatAPI;
declare var explainabilityBus: ExplainabilityBusAPI;
declare var crossLayerHelpers: CrossLayerHelpersAPI;
declare var crossLayerEmissionGateway: CrossLayerEmissionGatewayAPI;
declare var adaptiveTrustScoresHelpers: any;
declare var adaptiveTrustScores: AdaptiveTrustScoresAPI;
declare var sectionIntentCurves: SectionIntentCurvesAPI;
declare var phaseAwareCadenceWindow: PhaseAwareCadenceWindowAPI;
declare var negotiationEngine: NegotiationEngineAPI;
declare var grooveTransfer: GrooveTransferAPI;
declare var registerCollisionAvoider: RegisterCollisionAvoiderAPI;
declare var motifIdentityMemory: MotifIdentityMemoryAPI;
declare var crossLayerRegistry: CrossLayerRegistryAPI;
declare var crossLayerLifecycleManager: CrossLayerLifecycleManagerAPI;
declare var harmonicIntervalGuard: HarmonicIntervalGuardAPI;
declare var restSynchronizer: RestSynchronizerAPI;
declare var crossLayerClimaxEngine: CrossLayerClimaxEngineAPI;
declare var rhythmicComplementEngine: RhythmicComplementEngineAPI;
declare var pitchMemoryRecall: PitchMemoryRecallAPI;
declare var articulationComplement: ArticulationComplementAPI;
declare var crossLayerDynamicEnvelope: CrossLayerDynamicEnvelopeAPI;
declare var convergenceHarmonicTrigger: ConvergenceHarmonicTriggerAPI;
declare var texturalMirror: TexturalMirrorAPI;
declare var crossLayerSilhouette: CrossLayerSilhouetteAPI;
declare var dimensionalityExpander: { densityBias(): number; tensionBias(): number; flickerBias(): number; getSnapshot(): { urgency: number; densityBias: number; tensionBias: number; flickerBias: number }; reset(): void };
declare var conductorMetaWatchdog: { recordCorrection(pipeline: string, controllerName: string, correctionSign: number): void; getAttenuation(pipeline: string, controllerName: string): number; getSnapshot(): Record<string, Record<string, number>>; reset(): void };
declare var metaControllerRegistry: MetaControllerRegistryAPI;
declare var hyperMetaManagerState: { ORCHESTRATE_INTERVAL: number; HEALTH_EMA_ALPHA: number; EFFECTIVENESS_EMA_ALPHA: number; INTERVENTION_BUDGET: number; TRUST_VELOCITY_DAMPING: number; PHASE_STALE_THRESHOLD: number; MAX_CONTRADICTIONS: number; HEALTH_GATE_E5_ACCUM: number; HEALTH_GATE_TOPOLOGY: number; PHASE_FATIGUE_MAX: number; TRAJECTORY_MAX: number; FAST_EMA_ALPHA: number; FAST_EMA_THRESHOLD: number; FAST_EMA_SPAN: number; FAST_EMA_WEIGHT: number; E18_HEALTH_NOMINAL: number; E18_HEALTH_FLOOR: number; E18_EXCEED_ONSET: number; E18_EXCEED_SLOPE: number; E18_EXCEED_FLOOR: number; S: any; controllerStats: Record<string, any>; rateMultipliers: Record<string, number>; contradictions: any[]; axisExceedanceCounts: Record<string, number>; pairExceedanceCounts: Record<string, number>; prevCorrSign: Record<string, number>; trajectory: any[]; prevFingerprint: Record<string, number>; reconciliationGaps: Record<string, any>; trustVelocityHistory: Record<string, number[]> };
declare var hyperMetaManagerHealth: { gatherControllerState(): any; computeSystemHealth(state: any): number; classifySystemPhase(): 'converging' | 'oscillating' | 'stabilized'; updateEffectiveness(healthBefore: number, healthAfter: number, state: any): void; detectCorrelationFlips(state: any): number; recordExceedance(pair: string): void; getAxisConcentration(): { axisExceedance: Record<string, number>; concentration: number; dominantAxis: string }; getPairMonopoly(): { pair: string; share: number } | null };
declare var hyperMetaManagerContradictions: { updateRateMultipliers(state: any): void; detectContradictions(state: any): void };
declare var hyperMetaManagerTopology: { update(state: any): void };
declare var hyperMetaManagerTelemetry: { updateReconciliation(state: any): void; applyTrustVelocityDamping(state: any): void; checkPhaseTelemetryIntegrity(state: any): void };
declare var hyperMetaManager: { getRateMultiplier(key: string): number; getPhaseBoostCeiling(): number; getP95AlphaMultiplier(): number; getS0TighteningMultiplier(): number; getSystemPhase(): 'converging' | 'oscillating' | 'stabilized'; getVarianceGateRelaxMultiplier(): number; getTopologyCreativityMultiplier(): number; getTopologyPhase(): 'crystallized' | 'resonant' | 'fluid'; getCrossState(): 'emergence' | 'locked' | 'seeking' | 'dampened'; recordExceedance(pair: string): void; getAxisConcentration(): { axisExceedance: Record<string, number>; concentration: number; dominantAxis: string }; getSnapshot(): any; reset(): void };
declare var conductorSignalBridge: ConductorSignalBridgeAPI;
declare var verticalIntervalMonitor: { process(ctx: any): number; getCollisionCount(): number; reset(): void };
declare var polyrhythmicPhasePredictor: { process(ctx: any): number; predictConvergences(): void; reset(): void };
declare var contextualTrust: ContextualTrustAPI;
declare var beatInterleavedProcessor: { recordLayerBeat(layer: number, outcome: any): void; getOtherLayerOutcome(myLayer: number): any; getBeatSnapshot(): { layer1: any; layer2: any }; reset(): void };
declare var harmonicFunctionGraph: { classify(chordRoot: number, keyRoot: number): string; getFunction(): string; tensionBias(): number; reset(): void };

// -- writer --
declare var formatTime: any;
declare var logUnit: any;
declare var pushMultiple: any;
declare var grandFinale: any;
/** @boot-advisory - trace is diagnostic, composition runs without it */
declare var traceDrain: {
  init(): void;
  isEnabled(): boolean;
  record(layer: string, data: { beatKey: string; timeMs: number; conductorSnap: any; negotiation: any; trustScores: any; regime: any; couplingMatrix: any; couplingLabels?: any; [key: string]: any }): void;
  recordNote(pitch: number, velocity: number, channel: number): void;
  recordSnapshot(data: { beatKey: string; timeMs: number; trigger?: string; effectiveDim: number; trustScores?: any; trustVelocity?: Record<string,number>; activeProfile?: string; couplingMeans?: Record<string,number>; globalGainMultiplier?: number; regime: string; couplingStrength: number; phaseIntegrity: string; axisEnergyShare?: any; sectionKey?: string; sectionMode?: string }): void;
  recordRuntimeMetric(name: string, durationMs: number): void;
  recordFamilyVelocity(family: string, velocity: number): void;
  recordBinauralShift(data: { layer: string; absTimeMs: number; syncMs: number; usedCrossLayerShift: boolean; syncDeltaMs: number; freqOffset: number; toleranceMs: number; flip: boolean }): void;
  flush(): void;
  shutdown(): void;
};
/** @boot-advisory */
declare var coherenceVerdicts: {
  compute(manifest: any, attribution: { density: any; tension: any; flicker: any }): Array<{ severity: string; area: string; finding: string }>;
};
/** @boot-advisory */
declare var systemManifestMarkdown: {
  build(manifest: any, attribution: { density: any; tension: any; flicker: any }): string;
};
/** @boot-advisory */
declare var systemManifest: { emit(): void };
/** @boot-advisory */
declare var outputAnalyzer: { analyse(notes: { pitch: number; startMs: number; durationMs: number; velocity: number }[]): any; reset(): void };

// -- typed constructors (canonical declarations - keep only these) --
declare var VoiceLeadingScore: { new(config?: any): VoiceLeadingScoreAPI };
declare var SimplexNoise: { new(seed?: number): SimplexNoiseAPI };
declare var FactoryManager: ComposerFactoryAPI;

// -- node / timing --
declare var fs: any;
declare var path: any;
declare var endTime: number;

// -- play --
declare var eventBus: EventBusAPI;
declare var eventCatalog: EventCatalogAPI;
declare var trustSystems: TrustSystemsAPI;
declare var safePreBoot: {
  call<T>(fn: () => T, fallback?: T): T | undefined;
};
declare var traceSummaryData: any;
declare var telemetryHealthData: any;
declare var totalSections: number;
declare var phrasesPerSection: number;
declare var measuresPerPhrase: number;
declare var getChannelCoherence: any;
declare var playNotesComputeUnit: (unit: string, emissionAdjustments: any, emissionCfg: any, layer: any) => { on: number; sustain: number; binVel: number; noiseInfluence: number; currentTime: number; voiceIdSeed: number };
declare var playNotes: any;
declare var microUnitAttenuator: any;
declare var composer: any;
declare var remainingVoiceSlots: any;
declare var lastVoiceBudgetKey: any;
declare var velocity: any;
declare var fullBootstrap: any;
declare var feedbackGraphContract: {
  assert(): void;
};
declare var mainBootstrap: any;
declare var crossLayerBeatRecord: (opts: { layer: string; absoluteSeconds: number; clIntent: any; clPhase: any; clNegotiation: any; clBreathing: any; clTension: number; clCadence: any; clPhaseSnapshot: any; clRest: any; clEntropy: any; stutterProb: number; isL1: boolean; outputLoadGuard?: any; stageTiming?: Record<string, number> | null }) => void;
/** @boot-advisory */
declare var beatPipelineDescriptor: {
  getStages(): ReadonlyArray<{ name: string; after: string[]; produces: string[] }>;
  getStageNames(): string[];
  assertTopologicalOrder(): void;
};
declare var processBeat: any;
declare var layerPass: any;
declare var minimumNoteDuration: {
  floorSeconds(kind: string, unitSecs?: number): number;
  resolveOffTime(onTime: number, desiredOffTime: number, kind: string, unitSecs?: number, label?: string): number;
};
declare var playNotesEmitPick: any;
declare var setFeedbackPitchBias: (bias: number) => void;
declare var setClimaxMods: (mods: { playProbScale: number, velocityScale: number, registerBias: number, entropyTarget: number }) => void;
declare var emitPickCrossLayerRecord: any;
declare var emitPickSourceTextures: any;
declare var emitPickReflectionTextures: any;

// -- other --
declare var randomFloat: (min1?: number, max1?: number, min2?: number, max2?: number) => number;
declare var randomInt: (min1?: number, max1?: number, min2?: number, max2?: number) => number;
declare var randomWeightedInRange: (min: number, max: number, weights: number[]) => number;
declare var randomInRangeOrArray: (v: number | any[] | (() => any)) => any;
declare var randomLimitedChange: (currentValue: number, minChange: number, maxChange: number, minValue: number, maxValue: number, type?: string) => number;
declare var randomVariation: (value: number, boostRange?: number[], frequency?: number, deboostRange?: number[]) => number;
declare var sectionIndex: number;
declare var phraseIndex: number;
declare var measureIndex: number;
declare var beatIndex: number;
declare var divIndex: number;
declare var subdivIndex: number;
declare var subsubdivIndex: number;
declare var measureCount: number;
declare var c1: any;
declare var c2: any;
declare var layerManager: LayerManagerAPI;
declare var cCH2: number;
declare var cCH3: number;
declare var lCH1: number;
declare var lCH2: number;
declare var lCH3: number;
declare var lCH4: number;
declare var lCH5: number;
declare var lCH6: number;
declare var rCH1: number;
declare var rCH2: number;
declare var rCH3: number;
declare var rCH4: number;
declare var rCH5: number;
declare var rCH6: number;
declare var drumCH: number;
declare var cBal2: number;
declare var cBal3: number;
declare var _hex: any;
declare var _onsets: any;
declare var _probability: any;
declare var _euclid: any;
declare var _rotate: any;
declare var binauralPlus: any;
declare var binauralMinus: any;
declare var beatsOn: number;
declare var beatsOff: number;
declare var divsOn: number;
declare var divsOff: number;
declare var subdivsOn: number;
declare var subdivsOff: number;
declare var subsubdivsOn: number;
declare var subsubdivsOff: number;
declare var finalTime: number;
declare var subdivsPerBeat: any;
declare var noteCount: number;
declare var firstLoop: number;
declare var currentSectionType: any;
declare var currentSectionDynamics: any;
declare var fxEventTemplate: any;
declare var sectionEnd: number;
declare var polyNumerator: number;
declare var polyDenominator: number;
