// Managed globals — single source of truth for:
// 1) TypeScript ambient declarations (`src/types/**/*.d.ts` include)
// 2) ESLint global map (parsed directly by `eslint.config.mjs`)
// 3) Boot validation array in `fullBootstrap.js` (auto-generated by `scripts/generate-globals-dts.js`)
//
// Keep one declaration per line: `declare var NAME: Type;`
// The name is extracted by regex — type annotations and comments are safe to add.
//
// ── Abbreviation Glossary ──
// m   = Math                   rf  = randomFloat          ri  = randomInt
// rw  = randomWeightedInRange  ra  = randomInRangeOrArray rv  = randomVariation
// rl  = randomLimitedChange    t   = AbsoluteTimeGrid     c   = polyrhythm calculator
// p   = pitch bend util        LM  = LayerManager         V   = Validator instance (per-module)

// ── Core Interface Types ──
// These type the 7 nervous-system globals. Every other module touches at least one.

interface BiasRegistration {
  name: string;
  getter: () => number;
  lo: number;
  hi: number;
}

interface BiasAttribution {
  product: number;
  contributions: Array<{ name: string; raw: number; clamped: number }>;
}

interface RecorderContext {
  absTime: number;
  compositeIntensity: number;
  currentDensity: number;
  harmonicRhythm: number;
}

interface SignalSnapshot {
  densityProduct: number;
  tensionProduct: number;
  flickerProduct: number;
  stateFields: Record<string, unknown>;
  counts: Record<string, number>;
}

interface ConductorIntelligenceAPI {
  registerModule(name: string, mod: { reset: Function }, scopes: Array<'all' | 'section' | 'phrase'>): void;
  initialize(): void;
  resetSection(): void;
  resetPhrase(): void;
  getModuleNames(): string[];
  getModuleCount(): number;
  registerDensityBias(name: string, getter: () => number, lo: number, hi: number): void;
  collectDensityBias(): number;
  collectDensityBiasWithAttribution(): BiasAttribution;
  registerTensionBias(name: string, getter: () => number, lo: number, hi: number): void;
  collectTensionBias(): number;
  collectTensionBiasWithAttribution(): BiasAttribution;
  registerFlickerModifier(name: string, getter: () => number, lo: number, hi: number): void;
  collectFlickerModifier(): number;
  collectFlickerModifierWithAttribution(): BiasAttribution;
  registerRecorder(name: string, fn: (ctx: RecorderContext) => void): void;
  runRecorders(ctx: RecorderContext): void;
  registerStateProvider(name: string, getter: () => Record<string, unknown>): void;
  collectStateFields(): Record<string, unknown>;
  getCounts(): { density: number; tension: number; flicker: number; recorders: number; stateProviders: number };
  getSignalSnapshot(): Readonly<SignalSnapshot>;
}

interface SignalReaderAPI {
  density(): number;
  tension(): number;
  flicker(): number;
  state(field: string): any;
  snapshot(): Readonly<SignalSnapshot>;
  densityAttribution(): BiasAttribution;
  tensionAttribution(): BiasAttribution;
  flickerAttribution(): BiasAttribution;
  recentEvents(type: string, limit?: number): Array<{ type: string; layer: string; payload: unknown; absTimeMs: number }>;
}

interface CrossLayerRegistryAPI {
  register(name: string, module: { reset: Function }, scopes: Array<'all' | 'section' | 'phrase'>): void;
  resetAll(): void;
  resetSection(): void;
  resetPhrase(): void;
  getRegisteredNames(): string[];
  getCount(): number;
}

interface EventBusAPI {
  on(name: string, handler: (data: any) => void): void;
  off(name: string, handler: (data: any) => void): void;
  emit(name: string, data: any): void;
  listeners(name: string): number;
  clear(name: string): void;
  clearAll(): void;
}

interface ValidatorInstance {
  requireFinite(value: unknown, label: string): number;
  optionalFinite(value: unknown, fallback: number): number;
  requireDefined(value: unknown, label: string): unknown;
  requireType(value: unknown, type: string, label: string): unknown;
  requireEnum(value: unknown, allowed: unknown[], label: string): unknown;
  assertRange(value: unknown, lo: number, hi: number, label: string): number;
  assertObject(value: unknown, label: string): object;
  assertPlainObject(value: unknown, label: string): Record<string, unknown>;
  assertArray(value: unknown, label: string): any[];
  assertNonEmptyString(value: unknown, label: string): string;
  assertKeysPresent(obj: object, keys: string[], label: string): void;
  assertAllowedKeys(obj: object, keys: string[], label: string): void;
  assertBoolean(value: unknown, label: string): boolean;
  assertFinite(value: unknown, label: string): number;
  assertIntegerRange(value: unknown, lo: number, hi: number, label: string): number;
  assertString(value: unknown, label: string): string;
  assertInSet(value: unknown, allowedSet: Set<any>, label: string): any;
  assertArrayLength(value: unknown, length: number, label: string): any[];
  getEventsOrThrow(): Record<string, string>;
}

interface ValidatorFactory {
  create(moduleName: string): ValidatorInstance;
}

interface ConductorStateSnapshot {
  key: string; mode: string; quality: string;
  scale: any[]; chords: any[];
  tension: number; harmonicRhythm: number; harmonicMutationCount: number;
  excursion: number; sectionPhase: string;
  phrasePosition: number; phrasePhase: string; phraseDynamism: number;
  registerBias: number; densityMultiplier: number; voiceIndependence: number;
  compositeIntensity: number; playProb: number; stutterProb: number;
  textureMode: string; textureFatigue: number; densityBias: number;
  crossModBias: number; emissionRatio: number; activeProfile: string;
  journeyMove: string; journeyDistance: number; journeyKey: string; journeyMode: string;
  binauralFreqOffset: number; binauralFlip: boolean;
  tick: number; updatedAt: number;
}

interface ConductorStateAPI {
  initialize(): boolean;
  updateFromConductor(data: Record<string, unknown>): void;
  getSnapshot(): ConductorStateSnapshot;
  getField<K extends keyof ConductorStateSnapshot>(field: K): ConductorStateSnapshot[K];
  get<K extends keyof ConductorStateSnapshot>(field: K): ConductorStateSnapshot[K];
  reset(): void;
}

interface ConductorConfigAPI {
  applyPhaseProfile(): void;
  tickCrossfade(): void;
  regulationTick(): void;
  getPhaseMultiplier(phase: string): number;
  getGlobalIntensityBlend(): { arc: number; tension: number };
  getHarmonicRhythmParams(): { blendWeight: number; feedbackWeight: number };
  getTargetDensity(compositeIntensity: number): number;
  getDensitySmoothing(): number;
  getDensityBounds(): { floor: number; ceiling: number };
  getStutterParams(compositeIntensity: number): { rate: number; rateCurve: string; coherenceMode: string };
  getClimaxBoost(): { playScale: number; stutterScale: number };
  getRegulationDensityBias(): number;
  getRegulationCrossModBias(): number;
  getActiveProfileName(): string;
  getFamilyWeights(): Record<string, number>;
  getMotifMutationParams(): Record<string, any>;
  getMotifTextureClampParams(): Record<string, any>;
  getNoiseProfileForSection(sectionPhaseOverride?: string): string;
  getVoiceSpreadScaling(): Record<string, any>;
  getFeedbackMixWeights(): { fx: number; stutter: number; journey: number };
  getHintBlendedEnergyWeights(): { phrase: number; journey: number; feedback: number; pulse: number };
  getEmissionGateParams(): Record<string, any>;
  getFlickerParams(): { depthScale: number; crossModWeight: number };
  getJourneyBoldness(): number;
  getArcMapping(sectionPhase?: string): any;
  getPhraseBreathParams(): Record<string, any>;
  getTextureScaling(): Record<string, any>;
  getNoiseCanvasParams(): Record<string, any>;
  getSpatialCanvasParams(): Record<string, any>;
  getJourneyFxModulation(stopOverride?: { distance?: number; move?: string }): { reverbScale: number; filterScale: number; portamentoScale: number };
  getFxMixScaling(): Record<string, any>;
  getStutterGrainParams(): Record<string, any>;
  getEmissionScaling(): Record<string, any>;
  getAttenuationScaling(): Record<string, any>;
  getCrossModScaling(): Record<string, any>;
  getRhythmDriftParams(): Record<string, any>;
  getEnergyWeights(): Record<string, number>;
}

interface ATGEntry {
  timeMs: number;
  layer: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;
}

interface AbsoluteTimeGridAPI {
  post(channel: string, layer: string, timeMs: number, data?: Record<string, unknown>): void;
  query(channel: string, aroundMs: number, toleranceMs: number, opts?: { excludeLayer?: string; onlyLayer?: string }): ATGEntry[];
  findClosest(channel: string, aroundMs: number, toleranceMs: number, excludeLayer?: string): ATGEntry | null;
  getChannels(): string[];
  reset(channel?: string): void;
}

// ── Explainability / Trust / Coherence ──

interface ExplainabilityEntry {
  type: string;
  layer: string;
  payload: any;
  absTimeMs: number;
}

interface ExplainabilityBusAPI {
  emit(type: string, layer: string, payload: any, absTimeMs?: number): ExplainabilityEntry;
  getRecent(limit?: number): ExplainabilityEntry[];
  querySince(sinceMs: number): ExplainabilityEntry[];
  queryByType(type: string, limit?: number): ExplainabilityEntry[];
  reset(): void;
}

interface AdaptiveTrustScoresAPI {
  registerOutcome(systemName: string, payoff: number): number;
  getWeight(systemName: string): number;
  decayAll(rate?: number): void;
  getSnapshot(): Record<string, any>;
  reset(): void;
}

interface CoherenceMonitorAPI {
  initialize(): void;
  getDensityBias(): number;
  getEntropySignal(): number;
  getMetrics(): { bias: number; entropy: number; windowSize: number; cumActual: number; cumIntended: number };
  reset(): void;
}

// ── Conductor subsystem objects ──

interface ConductorSignalBridgeAPI {
  refresh(ctx: RecorderContext): void;
  getSignals(): Readonly<{ density: number; tension: number; flicker: number; compositeIntensity: number; sectionPhase: string; coherenceEntropy: number }>;
  reset(): void;
}

interface ProfileAdaptationAPI {
  update(): void;
  getHints(): { restrainedHint: number; explosiveHint: number; atmosphericHint: number };
  reset(): void;
}

interface SignalTelemetryAPI {
  record(ctx: RecorderContext): void;
  getHistory(n?: number): Array<{ tick: number; density: number; tension: number; flicker: number; compositeIntensity: number }>;
  isAnomalyDetected(): boolean;
  getTrend(): string;
  reset(): void;
}

interface JourneyStop {
  key: string;
  mode: string;
  move: string;
  distance: number;
}

interface HarmonicContextAPI {
  set(updates: { key?: string; mode?: string; quality?: string; scale?: any[]; chords?: any[]; tension?: number; excursion?: number; sectionPhase?: string }): void;
  get(): { key: string; mode: string; quality: string; scale: any[]; chords: any[]; tension: number; excursion: number; sectionPhase: string; mutationCount: number; modifiedAt: number };
  getField(field: string): any;
  updateScaleFromMode(key: string, mode: string): void;
  isNoteInScale(noteInput: string | number): boolean;
  reset(): void;
  toJSON(): object;
}

interface HarmonicJourneyAPI {
  planJourney(totalSections: number, opts?: { startKey?: string; startMode?: string }): JourneyStop[];
  getStop(sectionIndex: number): JourneyStop;
  applyToContext(sectionIndex: number): void;
  getL2Complement(sectionIndex: number): { key: string; mode: string; relationship: string };
  applyL2ToContext(sectionIndex: number): void;
  getPlan(): JourneyStop[];
  getCurrentIndex(): number;
  getOrigin(): { key: string; mode: string };
  reset(): void;
}

// ── Time subsystem ──

type TimeStreamLevel = 'section' | 'phrase' | 'measure' | 'beat' | 'div' | 'subdiv' | 'subsubdiv';

interface TimeStreamAPI {
  setPosition(level: TimeStreamLevel, index: number): void;
  setBounds(level: TimeStreamLevel, count: number): void;
  getPosition(level: TimeStreamLevel): number;
  getBounds(level: TimeStreamLevel): number;
  progress(level: TimeStreamLevel): number;
  normalizedProgress(level: TimeStreamLevel): number;
  globalProgress(): number;
  remaining(level: TimeStreamLevel): number;
  isFirst(level: TimeStreamLevel): boolean;
  isLast(level: TimeStreamLevel): boolean;
  lookAhead(level: TimeStreamLevel, n: number): number;
  lookBehind(level: TimeStreamLevel, n: number): number;
  depth(level: TimeStreamLevel): number;
  snapshot(): Readonly<{ pos: Record<TimeStreamLevel, number>; bounds: Record<TimeStreamLevel, number>; globalProgress: number }>;
  range(start: number, end: number): Generator<number>;
  getLevels(): readonly string[];
  resetPositions(): void;
  compoundProgress(level: TimeStreamLevel): number;
  resetSubLevels(level: TimeStreamLevel): void;
  positionString(): string;
}

interface LayerManagerAPI {
  layers: Record<string, any>;
  layerComposers: Record<string, any>;
  phraseFamily: any;
  activeLayer: any;
  register(name: string, buffer: any[] | string, initialState?: object, setupFn?: Function): { layer: any; buffer: any[] };
  activate(name: string, isPoly?: boolean): any;
  advance(name: string, advancementType?: 'phrase' | 'section'): void;
  setSectionStartFor(name: string): void;
  setSectionStartAll(): void;
  setPhraseFamily(familyName: string): string;
  getPhraseFamily(): any;
  setComposerFor(name: string, nextComposer: object): any;
  setComposerForAll(nextComposer: object): any;
  getComposerFor(name: string): any;
}

// ── Lifecycle / caching utilities ──

interface ModuleLifecycleInstance {
  register(name: string, mod: { reset: Function }, scopes: Array<'all' | 'section' | 'phrase'>): void;
  resetByScope(scope: string): void;
  resetAll(): void;
  resetSection(): void;
  resetPhrase(): void;
  getNames(): string[];
  getCount(): number;
}

interface ModuleLifecycleFactory {
  create(ownerName: string): ModuleLifecycleInstance;
}

interface BeatCacheInstance {
  get(): any;
}

interface BeatCacheFactory {
  create(fn: () => any): BeatCacheInstance;
}

// ── EventCatalog ──

interface EventCatalogAPI {
  names: Readonly<{
    SECTION_BOUNDARY: 'section-boundary';
    JOURNEY_MOVE: 'journey-move';
    TEXTURE_CONTRAST: 'texture-contrast';
    BEAT_FX_APPLIED: 'beat-fx-applied';
    STUTTER_APPLIED: 'stutter-applied';
    CONDUCTOR_REGULATION: 'conductor-regulation';
    BEAT_BINAURAL_APPLIED: 'beat-binaural-applied';
    HARMONIC_CHANGE: 'harmonic-change';
    NOTES_EMITTED: 'notes-emitted';
    MOTIF_CHAIN_APPLIED: 'motif-chain-applied';
    CROSS_LAYER_EXPLAIN: 'cross-layer-explain';
    CONVERGENCE_HARMONIC_TRIGGER: 'convergence-harmonic-trigger';
    CROSS_LAYER_CONVERGENCE: 'cross-layer-convergence';
    CROSS_LAYER_CADENCE_ALIGN: 'cross-layer-cadence-align';
    PHRASE_BOUNDARY: 'phrase-boundary';
    MEASURE_BOUNDARY: 'measure-boundary';
  }>;
  assertEventPayload(name: string, data: object): boolean;
  validateEmit(name: string, data: object): boolean;
}

// ── Remaining interfaces above, declare var sections below ──

// ── utils ──
declare var m: typeof Math;
declare var rf: (min1?: number, max1?: number, min2?: number, max2?: number) => number;
declare var ri: (min1?: number, max1?: number, min2?: number, max2?: number) => number;
declare var rw: (min: number, max: number, weights: number[]) => number;
declare var ra: (v: number | any[] | (() => any)) => any;
declare var rv: (value: number, boostRange?: number[], frequency?: number, deboostRange?: number[]) => number;
declare var rl: (currentValue: number, minChange: number, maxChange: number, minValue: number, maxValue: number, type?: string) => number;
declare var clamp: (value: number, min: number, max: number) => number;
declare var modClamp: (value: number, min: number, max: number) => number;
declare var lowModClamp: (value: number, min: number, max: number) => number;
declare var highModClamp: (value: number, min: number, max: number) => number;
declare var scaleClamp: (value: number, min: number, max: number, factor: number, maxFactor?: number, base?: number) => number;
declare var scaleBoundClamp: (value: number, base: number, lowerScale: number, upperScale: number, minBound?: number, maxBound?: number) => number;
declare var softClamp: (value: number, min: number, max: number, softness?: number) => number;
declare var stepClamp: (value: number, min: number, max: number, step: number) => number;
declare var logClamp: (value: number, min: number, max: number, base?: number) => number;
declare var expClamp: (value: number, min: number, max: number, base?: number) => number;
declare var randomWeightedInArray: (weights: number[]) => number;
declare var randomWeightedSelection: (options: Record<string, { weights: number[] }>) => string;
declare var normalizeWeights: (weights: number[], min: number, max: number, variationLow?: number, variationHigh?: number) => number[];
declare var MIDI_MAX_VALUE: number;
declare var midiData: any;
declare var getMidiValue: any;
declare var allCHs: number[];
declare var allNotes: string[];
declare var allScales: string[];
declare var allChords: string[];
declare var allModes: string[];
declare var cCH1: number;
declare var source: any;
declare var source2: any;
declare var reflection: any;
declare var bass: any;
declare var rlFX: any;
declare var setTuningAndInstruments: any;
declare var stutterFadeCHs: any;
declare var stutterPanCHs: any;
declare var chFX: any;
declare var flipBinT: any;
declare var flipBinF: any;
declare var flipBinT3: any;
declare var flipBinF3: any;
declare var flipBinF2: any;
declare var flipBinT2: any;
declare var reflectionBinaural: any;
declare var reflect: any;
declare var reflect2: any;
declare var binauralL: any;
declare var binauralR: any;
declare var binauralOffset: any;
declare var bassBinaural: any;
declare var crossModulation: any;
declare var lastMeter: any;
declare var lastUsedCHs: any;
declare var lastUsedCHs2: any;
declare var lastUsedCHs3: any;
declare var remainingVoiceSlotsByLayer: any;
declare var lastVoiceBudgetKeyByLayer: any;
declare var neutralPitchBend: any;
declare var semitone: any;
declare var tuningPitchBend: any;
declare var FX: any;
declare var COMPOSER_TYPE_PROFILE_SOURCES: any;
declare var allNotesOff: any;
declare var muteAll: any;
declare var setOtherInstruments: any;
declare var Validator: ValidatorFactory;
declare var SystemSnapshot: any;
declare var modeQualityMap: any;
declare var priorsHelpers: any;

// ── conductor ──
declare var BPM: number;
declare var PPQ: number;
declare var currentDensity: number;
declare var update: any;
declare var TUNING_FREQ: number;
declare var LOG: any;
declare var BINAURAL: any;
declare var SILENT_OUTRO_SECONDS: number;
declare var SECTIONS: any;
declare var PHRASES_PER_SECTION: any;
declare var NUMERATOR: any;
declare var DENOMINATOR: any;
declare var DIVISIONS: any;
declare var SUBDIVS: any;
declare var VOICES: any;
declare var BEAT_VOICES: any;
declare var DIV_VOICES: any;
declare var SUBDIV_VOICES: any;
declare var SUBSUBDIV_VOICES: any;
declare var BEAT_SIBLING_VOICES: any;
declare var DIV_SIBLING_VOICES: any;
declare var SUBDIV_SIBLING_VOICES: any;
declare var SUBSUBDIV_SIBLING_VOICES: any;
declare var OCTAVE: any;
declare var primaryInstrument: any;
declare var secondaryInstrument: any;
declare var otherInstruments: any;
declare var bassInstrument: any;
declare var bassInstrument2: any;
declare var otherBassInstruments: any;
declare var drumSets: any;
declare var PhraseArcManager: any;
declare var phraseArcProfiler: any;
declare var HarmonicContext: HarmonicContextAPI;
declare var HarmonicJourney: HarmonicJourneyAPI;
declare var HarmonicRhythmTracker: any;
declare var harmonicJourneyHelpers: any;
declare var harmonicJourneyPlanner: any;
declare var DynamismEngine: any;
declare var dynamismPulse: any;
declare var TextureBlender: any;
declare var ConductorState: ConductorStateAPI;
declare var VOICE_PROFILES: any;
declare var CHORD_PROFILES: any;
declare var MOTIF_PROFILES: any;
declare var RHYTHM_PROFILES: any;
declare var RHYTHM_PATTERNS: any;
declare var RHYTHM_PATTERN_POOLS: any;
declare var DRUM_MAP: any;
declare var FX_CC_DEFAULTS: any;
declare var NOISE_GENERATOR_REGISTRY: any;
declare var PHRASES_ARC_CURVES: any;
declare var MODAL_BORROWING: any;
declare var NOISE_PROFILES: any;
declare var COMPOSER_FAMILIES: any;
declare var VOICE_Manager: any;
declare var SECTION_TYPES: any;
declare var SUBSUBDIVS: any;
declare var DYNAMISM: any;
declare var STUTTER_PROFILES: any;
declare var STUTTER_VELOCITY_RANGES: any;
declare var STUTTER_CROSSMOD_RULES: any;
declare var STUTTER_CROSSMOD_RULES_FALLBACK: any;
declare var STUTTER_PRESETS: any;
declare var STUTTER_DIRECTIVE_DEFAULTS: any;
declare var MOTIF_UNIT_PROFILES: any;
declare var CONDUCTOR_DYNAMICS_CONTROLS: any;
declare var MAIN_LOOP_CONTROLS: any;
declare var CONDUCTOR_NOISE_PROFILE_BY_PHASE: any;
declare var CONDUCTOR_PROFILE_SOURCES: any;
declare var conductorProfileDefault: any;
declare var conductorProfileRestrained: any;
declare var conductorProfileExplosive: any;
declare var conductorProfileAtmospheric: any;
declare var conductorProfileRhythmicDrive: any;
declare var conductorProfileMinimal: any;
declare var conductorConfigTuningDefaults: any;
declare var conductorConfigTuningOverrides: any;
declare var conductorConfigMergeProfileTuning: any;
declare var conductorConfigValidateProfile: any;
declare var conductorConfigDynamics: any;
declare var conductorConfigResolvers: any;
declare var conductorConfigAccessors: any;
declare var ConductorConfig: ConductorConfigAPI;
declare var GlobalConductor: any;
declare var MelodicContourTracker: any;
declare var RegisterPressureMonitor: any;
declare var LayerCoherenceScorer: any;
declare var CadenceAdvisor: any;
declare var SectionLengthAdvisor: any;
declare var DynamicRangeTracker: any;
declare var RestDensityTracker: any;
declare var IntervalBalanceTracker: any;
declare var InterLayerRhythmAnalyzer: any;
declare var HarmonicVelocityMonitor: any;
declare var TexturalMemoryAdvisor: any;
declare var PitchGravityCenter: any;
declare var OnsetDensityProfiler: any;
declare var SyncopationDensityTracker: any;
declare var GrooveTemplateAdvisor: any;
declare var StructuralFormTracker: any;
declare var VoiceDensityBalancer: any;
declare var AccentPatternTracker: any;
declare var ModalColorTracker: any;
declare var RepetitionFatigueMonitor: any;
declare var EnergyMomentumTracker: any;
declare var ArticulationProfiler: any;
declare var RegisterMigrationTracker: any;
declare var RhythmicComplexityGradient: any;
declare var ClimaxProximityPredictor: any;
declare var OnsetRegularityMonitor: any;
declare var DurationalContourTracker: any;
declare var HarmonicSurpriseIndex: any;
declare var CounterpointMotionTracker: any;
declare var ConsonanceDissonanceTracker: any;
declare var VelocityShapeAnalyzer: any;
declare var pitchClassHelpers: any;
declare var OctaveSpreadMonitor: any;
declare var MotivicDensityTracker: any;
declare var PedalPointDetector: any;
declare var PhraseLengthMomentumTracker: any;
declare var TensionResolutionTracker: any;
declare var octaveHelpers: any;
declare var DensityWaveAnalyzer: any;
declare var TimbreBalanceTracker: any;
declare var HarmonicRhythmDensityRatio: any;
declare var ThematicRecallDetector: any;
declare var beatGridHelpers: any;
declare var interLayerRhythmHelpers: any;
declare var LayerIndependenceScorer: any;
declare var TemporalProportionTracker: any;
declare var ChromaticSaturationMonitor: any;
declare var fragmentHelpers: any;
declare var analysisHelpers: any;
declare var RhythmicSymmetryDetector: any;
declare var TexturalGradientTracker: any;
declare var CadentialPreparationAdvisor: any;
declare var AmbitusMigrationTracker: any;
declare var SilenceDistributionTracker: any;
declare var VoiceLeadingEfficiencyTracker: any;
declare var RhythmicGroupingAnalyzer: any;
declare var DynamicArchitectPlanner: any;
declare var TessituraPressureMonitor: any;
declare var HarmonicFieldDensityTracker: any;
declare var OrchestrationWeightTracker: any;
declare var RhythmicInertiaTracker: any;
declare var PitchClassGravityMap: any;
declare var IntervalDirectionMemory: any;
declare var CrossLayerDensityBalancer: any;
declare var HarmonicPedalFieldTracker: any;
declare var RegistralVelocityCorrelator: any;
declare var PhraseContourArchetypeDetector: any;
declare var HarmonicDensityOscillator: any;
declare var AttackDensityProfiler: any;
declare var LayerEntryExitTracker: any;
declare var IntervalExpansionContractor: any;
declare var DynamicPeakMemory: any;
declare var RhythmicDensityContrastTracker: any;
declare var TonalAnchorDistanceTracker: any;
declare var ConductorIntelligence: ConductorIntelligenceAPI;
declare var CoherenceMonitor: CoherenceMonitorAPI;
declare var signalReader: SignalReaderAPI;
declare var profileAdaptation: ProfileAdaptationAPI;
declare var signalTelemetry: SignalTelemetryAPI;
declare var ModuleLifecycle: ModuleLifecycleFactory;
declare var beatCache: BeatCacheFactory;

// ── rhythm ──
declare var RhythmRegistry: any;
declare var RhythmManager: any;
declare var RhythmValues: any;
declare var rhythmConfig: any;
declare var rhythmModulator: any;
declare var RHYTHM_PRIOR_TABLES: any;
declare var rhythmPriors: any;
declare var PhaseLockedRhythmGenerator: any;
declare var FXFeedbackListener: any;
declare var StutterFeedbackListener: any;
declare var JourneyRhythmCoupler: any;
declare var EmissionFeedbackListener: any;
declare var FeedbackAccumulator: any;
declare var DrumTextureCoupler: any;
declare var ConductorRegulationListener: any;
declare var setRhythm: any;
declare var _rp: any;
declare var _binary: any;
declare var _random: any;
declare var rotate: any;
declare var lastCrossMod: number;
declare var playDrums: any;
declare var playDrums2: any;
declare var binary: any;
declare var hex: any;
declare var onsets: any;
declare var random: any;
declare var prob: any;
declare var euclid: any;
declare var morph: any;
declare var closestDivisor: any;
declare var rhythmMethods: any;
declare var makeOnsets: any;
declare var patternLength: any;
declare var drumMap: any;
declare var drummer: any;
declare var getRhythm: any;
declare var rhythms: any;
declare var trackRhythm: any;
declare var crossModulateRhythms: any;
declare var RhythmHistoryTracker: any;

// ── time ──
declare var bpmRatio: number;
declare var bpmRatio2: any;
declare var bpmRatio3: any;
declare var tpSec: number;
declare var tpMeasure: number;
declare var tpBeat: number;
declare var tpDiv: number;
declare var tpSubdiv: number;
declare var tpSubsubdiv: number;
declare var numerator: number;
declare var denominator: number;
declare var meterRatio: number;
declare var divRhythm: number;
declare var subdivRhythm: number;
declare var subsubdivRhythm: number;
declare var measuresPerPhrase1: number;
declare var measuresPerPhrase2: number;
declare var measureStart: number;
declare var measureStartTime: number;
declare var beatStart: number;
declare var beatStartTime: number;
declare var divStart: number;
declare var divStartTime: number;
declare var subdivStart: number;
declare var subdivStartTime: number;
declare var subsubdivStart: number;
declare var subsubdivStartTime: number;
declare var c: any;
declare var LM: LayerManagerAPI;
declare var getMidiTiming: any;
declare var setMidiTiming: any;
declare var POLYRHYTHM_PAIRS: any;
declare var getMeterPair: { pick: () => void; reset: () => void };
declare var getPolyrhythm: any;
declare var setUnitTiming: any;
declare var bestMatch: number;
declare var subsubsPerSub: number;
declare var tpUnit: number;
declare var unitIndex: number;
declare var unitStart: number;
declare var parentStart: number;
declare var tpParent: number;
declare var unitsPerParent: number;
declare var tpPhrase: any;
declare var spPhrase: number;
declare var phraseStart: number;
declare var phraseStartTime: number;
declare var tpSection: number;
declare var spSection: number;
declare var sectionStart: number;
declare var sectionStartTime: number;
declare var spMeasure: number;
declare var spBeat: any;
declare var subdivsPerMinute: number;
declare var subsubsPerMinute: number;
declare var subdivFreq: any;
declare var divsPerBeat: number;
declare var subdivsPerDiv: number;
declare var spDiv: any;
declare var spSubdiv: any;
declare var spSubsubdiv: any;
declare var trueBPM: any;
declare var trueBPM2: any;
declare var polyMeterRatio: number;
declare var isPowerOf2: any;
declare var midiMeter: any;
declare var midiMeterRatio: any;
declare var midiBPM: any;
declare var syncFactor: any;
declare var timeGridPrune: any;
declare var timeGridSearchStart: any;
declare var AbsoluteTimeWindow: any;
declare var AbsoluteTimeGrid: AbsoluteTimeGridAPI;
declare var TempoFeelEngine: any;
declare var TimeStream: TimeStreamAPI;

// ── composers ──
declare var normalizeChordSymbol: any;
declare var MeasureComposer: any;
declare var ScaleComposer: any;
declare var RandomScaleComposer: any;
declare var ChordComposer: any;
declare var RandomChordComposer: any;
declare var ModeComposer: any;
declare var RandomModeComposer: any;
declare var TensionReleaseComposer: any;
declare var ModalInterchangeComposer: any;
declare var HarmonicRhythmComposer: any;
declare var melodicDevelopmentVoicingIntent: (candidateNotes: any[], lastBaseNotes: any[], lastDevelopedNotes: any[], developmentBias: number, intensity: number, currentPhase: number) => { candidateWeights: { [note: number]: number } } | null;
declare var MelodicDevelopmentComposer: any;
declare var VoiceLeadingComposer: any;
declare var MotifComposer: any;
declare var Motif: any;
declare var MotifTransforms: any;
declare var MeasureNotePool: any;
declare var MotifValidators: any;
declare var RegisterBiasing: any;
declare var CandidateExpansion: any;
declare var playMotifs: any;
declare var playMotifsResolveBucket: any;
declare var playMotifsBuildCandidateNotes: any;
declare var playMotifsApplyCycleTransforms: any;
declare var PentatonicComposer: any;
declare var RandomPentatonicComposer: any;
declare var BluesComposer: any;
declare var RandomBluesComposer: any;
declare var ChromaticComposer: any;
declare var RandomChromaticComposer: any;
declare var QuartalComposer: any;
declare var RandomQuartalComposer: any;
declare var IntervalComposer: any;
declare var FactoryManager: any;
declare var factoryProfiles: any;
declare var factoryProgression: any;
declare var factoryPoolResolver: any;
declare var factoryFamilies: any;
declare var factoryConstructors: any;
declare var ComposerFactory: any;
declare var MotifChain: any;
declare var ProgressionGenerator: any;
declare var PivotChordBridge: any;
declare var HARMONIC_PRIOR_TABLES: any;
declare var harmonicPriors: any;
declare var ChordRegistry: any;
declare var ChordManager: any;
declare var ChordValues: any;
declare var chordConfig: any;
declare var chordModulator: any;
declare var MotifRegistry: any;
declare var MotifManager: any;
declare var MotifValues: any;
declare var motifConfig: any;
declare var motifModulator: any;
declare var VoiceRegistry: any;
declare var VoiceValues: any;
declare var voiceConfig: any;
declare var voiceModulator: any;
declare var VoiceLeadingScore: any;
declare var VoiceLeadingScorers: any;
declare var VoiceLeadingCore: any;
declare var VOICE_LEADING_PRIOR_TABLES: any;
declare var voiceLeadingPriors: any;
declare var MELODIC_PRIOR_TABLES: any;
declare var melodicPriors: any;
declare var voiceLeadingSelectNextNote: any;
declare var voiceLeadingAnalyzeQuality: any;
declare var VoiceManager: any;
declare var getScheduledNotes: any;
declare var p: any;
declare var note: any;
declare var applyComposerPitchNoise: any;
declare var applyMelodicTranspositionNoise: any;
declare var assertComposerCapabilities: any;
declare var resolveScalePC: any;
declare var midiToDegree: any;
declare var degreeToMidi: any;
declare var transposeByDegree: any;
declare var scaleNormalization: any;
declare var scaleDegreeTranspose: any;
declare var applyMelodicPivotNoise: any;
declare var applyMelodicDurationNoise: any;
declare var applyVoiceLeadingWeightNoise: any;
declare var activeMotif: any;
declare var main: any;
declare var ComposerProfileUtils: any;
declare var ComposerProfileValidation: any;
declare var COMPOSER_TYPES: any;
declare var ComposerRuntimeProfileAdapter: any;
declare var COMPOSER_PROFILE_POOLS: any;
declare var COMPOSER_POOL_SELECTION_STRATEGY: any;
declare var COMPOSER_TYPE_PROFILES: any;
declare var selectComposerPoolOrFail: any;
declare var getComposerPoolOrFail: any;
declare var getDefaultComposerPoolOrFail: any;
declare var getComposerTypeProfilesOrFail: any;
declare var getComposerTypeProfileOrFail: any;
declare var MotifSpreader: any;
declare var applyMotifToNotes: any;
declare var MotifTransformAdvisor: any;

// ── fx ──
declare var StutterConfig: any;
declare var lBal: number;
declare var rBal: number;
declare var cBal: number;
declare var refVar: any;
declare var bassVar: any;
declare var balOffset: number;
declare var stutterFade: any;
declare var stutterPan: any;
declare var stutterFX: any;
declare var stutterExecutePlan: any;
declare var stutterNotes: any;
declare var pickStutterChannels: any;
declare var StutterRegistry: any;
declare var StutterMetrics: any;
declare var StutterConfigStore: any;
declare var StutterPlanScheduler: any;
declare var Stutter: any;
declare var setBalanceAndFX: any;
declare var setBinaural: any;
declare var SimplexNoise: any;
declare var fbm: any;
declare var turbulence: any;
declare var ridged: any;
declare var worley: any;
declare var easeInOut: any;
declare var easingFunctions: any;
declare var noiseFunctions: any;
declare var metaRecursiveEaseNoise: any;
declare var metaRecursiveNoise: any;
declare var metaRecursiveSimplex2D: any;
declare var metaRecursiveFBM: any;
declare var permutation: any;
declare var fade: any;
declare var lerp: any;
declare var grad: any;
declare var perlinNoise: any;
declare var defaultSimplex: any;
declare var noiseGenerators: any;
declare var generatorKeys: any;
declare var getNoiseValue: any;
declare var layeredNoise: any;
declare var createNoiseOffset: any;
declare var randomNoiseGenerator: any;
declare var noiseInfluenceMap: any;
declare var createDualAxisNoiseConfig: any;
declare var applyDualAxisNoise: any;
declare var safeApplyNoise: any;
declare var clampNoiseValue: any;
declare var getParameterModulation: any;
declare var smoothNoiseValue: any;
declare var getNoiseProfile: any;
declare var registerNoiseGenerator: any;
declare var applyNoiseToVelocity: any;
declare var applyNoiseToPan: any;
declare var applyNoiseToSustain: any;
declare var applyNoiseToParameter: any;
declare var getNoiseProfileOrFail: any;
declare var flipBin: any;
declare var binauralFreqOffset: any;
declare var beatsUntilBinauralShift: number;
declare var beatCount: number;
declare var sideBias: number;
declare var StutterFailFast: any;

// ── crossLayer ──
declare var t: any;
declare var StutterContagion: any;
declare var ConvergenceDetector: any;
declare var TemporalGravity: any;
declare var VelocityInterference: any;
declare var FeedbackOscillator: any;
declare var CadenceAlignment: any;
declare var RhythmicPhaseLock: any;
declare var SpectralComplementarity: any;
declare var DynamicRoleSwap: any;
declare var MotifEcho: any;
declare var InteractionHeatMap: any;
declare var entropyMetrics: any;
declare var EntropyRegulator: any;
declare var EmergentDownbeat: any;
declare var ExplainabilityBus: ExplainabilityBusAPI;
declare var AdaptiveTrustScores: AdaptiveTrustScoresAPI;
declare var SectionIntentCurves: any;
declare var PhaseAwareCadenceWindow: any;
declare var NegotiationEngine: any;
declare var GrooveTransfer: any;
declare var RegisterCollisionAvoider: any;
declare var MotifIdentityMemory: any;
declare var CrossLayerRegistry: CrossLayerRegistryAPI;
declare var CrossLayerLifecycleManager: any;
declare var HarmonicIntervalGuard: any;
declare var RestSynchronizer: any;
declare var CrossLayerClimaxEngine: any;
declare var RhythmicComplementEngine: any;
declare var PitchMemoryRecall: any;
declare var ArticulationComplement: any;
declare var CrossLayerDynamicEnvelope: any;
declare var ConvergenceHarmonicTrigger: any;
declare var TexturalMirror: any;
declare var CrossLayerSilhouette: any;
declare var conductorSignalBridge: ConductorSignalBridgeAPI;

// ── writer ──
declare var formatTime: any;
declare var logUnit: any;
declare var pushMultiple: any;
declare var grandFinale: any;
declare var fs: any;
declare var finalTick: number;
declare var path: any;
declare var endTime: number;

// ── play ──
declare var EventBus: EventBusAPI;
declare var EventCatalog: EventCatalogAPI;
declare var totalSections: number;
declare var phrasesPerSection: number;
declare var measuresPerPhrase: number;
declare var getChannelCoherence: any;
declare var playNotes: any;
declare var microUnitAttenuator: any;
declare var composer: any;
declare var remainingVoiceSlots: any;
declare var lastVoiceBudgetKey: any;
declare var velocity: any;
declare var FullBootstrap: any;
declare var MainBootstrap: any;
declare var processBeat: any;
declare var layerPass: any;
declare var playNotesEmitPick: any;
declare var setFeedbackPitchBias: (bias: number) => void;
declare var setClimaxMods: (mods: { playProbScale: number, velocityScale: number, registerBias: number, entropyTarget: number }) => void;
declare var emitPickCrossLayerRecord: any;
declare var emitPickSourceTextures: any;
declare var emitPickReflectionTextures: any;

// ── other ──
declare var randomFloat: (min1?: number, max1?: number, min2?: number, max2?: number) => number;
declare var randomInt: (min1?: number, max1?: number, min2?: number, max2?: number) => number;
declare var randomWeightedInRange: (min: number, max: number, weights: number[]) => number;
declare var randomInRangeOrArray: (v: number | any[] | (() => any)) => any;
declare var randomLimitedChange: (currentValue: number, minChange: number, maxChange: number, minValue: number, maxValue: number, type?: string) => number;
declare var randomVariation: (value: number, boostRange?: number[], frequency?: number, deboostRange?: number[]) => number;
declare var beatRhythm: any;
declare var divRhythm: any;
declare var subdivRhythm: any;
declare var subsubdivRhythm: any;
declare var sectionIndex: number;
declare var phraseIndex: number;
declare var measureIndex: number;
declare var beatIndex: number;
declare var divIndex: number;
declare var subdivIndex: number;
declare var subsubdivIndex: number;
declare var measureCount: number;
declare var c1: any;
declare var c2: any;
declare var layerManager: LayerManagerAPI;
declare var cCH2: number;
declare var cCH3: number;
declare var lCH1: number;
declare var lCH2: number;
declare var lCH3: number;
declare var lCH4: number;
declare var lCH5: number;
declare var lCH6: number;
declare var rCH1: number;
declare var rCH2: number;
declare var rCH3: number;
declare var rCH4: number;
declare var rCH5: number;
declare var rCH6: number;
declare var drumCH: number;
declare var cBal2: number;
declare var cBal3: number;
declare var _hex: any;
declare var _onsets: any;
declare var _probability: any;
declare var _euclid: any;
declare var _rotate: any;
declare var binauralPlus: any;
declare var binauralMinus: any;
declare var beatsOn: number;
declare var beatsOff: number;
declare var divsOn: number;
declare var divsOff: number;
declare var subdivsOn: number;
declare var subdivsOff: number;
declare var subsubdivsOn: number;
declare var subsubdivsOff: number;
declare var finalTime: number;
declare var tpPhrase1: number;
declare var tpPhrase2: number;
declare var subdivsPerBeat: any;
declare var noteCount: number;
declare var firstLoop: number;
declare var currentSectionType: any;
declare var currentSectionDynamics: any;
declare var fxEventTemplate: any;
declare var sectionEnd: number;
declare var polyNumerator: number;
declare var polyDenominator: number;
