from .patterns import (
    TS_PATTERNS, JS_IIFE_PATTERNS, RUST_PATTERNS, PY_PATTERNS,
    JAVA_PATTERNS, KOTLIN_PATTERNS, GO_PATTERNS, C_PATTERNS, CPP_PATTERNS,
    CSHARP_PATTERNS, PHP_PATTERNS, RUBY_PATTERNS, SCALA_PATTERNS,
    SWIFT_PATTERNS, DART_PATTERNS, ELIXIR_PATTERNS, LUA_PATTERNS,
    BASH_PATTERNS, PERL_PATTERNS, HASKELL_PATTERNS, R_PATTERNS,
    JULIA_PATTERNS, ZIG_PATTERNS, NIM_PATTERNS, OCAML_PATTERNS,
    ERLANG_PATTERNS, OBJC_PATTERNS, PROTO_PATTERNS, SQL_PATTERNS,
    find_iife_globals,
)
from .extractor import extract_symbols, collect_all_symbols
from .analysis import find_callers, get_type_hierarchy, find_dead_code, preview_rename
