# Resolve project root, three-tier fallback:
#   1. $CLAUDE_PROJECT_DIR — standard Claude Code env var pointing at the
#      working-tree root. Available inside all hook invocations.
#   2. Walk up from $BASH_SOURCE[0] looking for a .git/.env-bearing root
#      (works from any in-repo invocation).
#   3. Hardcoded fallback to /home/jah/Polychron. Last resort — same
#      pattern _proxy_bridge.sh uses for its own _PB_ROOT.
_HME_PROJECT_ROOT=""
if [ -n "${CLAUDE_PROJECT_DIR:-}" ] && [ -f "$CLAUDE_PROJECT_DIR/.env" ]; then
  _HME_PROJECT_ROOT="$CLAUDE_PROJECT_DIR"
fi
if [ -z "$_HME_PROJECT_ROOT" ]; then
  _HME_TRY="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"
  while [ -n "$_HME_TRY" ] && [ "$_HME_TRY" != "/" ]; do
    if [ -f "$_HME_TRY/.env" ] && [ -d "$_HME_TRY/.git" ] && [ -d "$_HME_TRY/src" ]; then
      _HME_PROJECT_ROOT="$_HME_TRY"
      break
    fi
    _HME_TRY="$(dirname "$_HME_TRY")"
  done
fi
# No host-specific hardcoded fallback. If both $CLAUDE_PROJECT_DIR
# and the walk-up strategy failed, the invocation environment is
# fundamentally broken; fail loud rather than guess a path.
_HME_ENV_FILE="$_HME_PROJECT_ROOT/.env"
if [ -n "$_HME_PROJECT_ROOT" ] && [ -f "$_HME_ENV_FILE" ]; then
  set -a; source "$_HME_ENV_FILE"; set +a
else
  echo "WARNING: _safety.sh cannot resolve project root (tried CLAUDE_PROJECT_DIR, walk-up, hardcoded fallback) — hooks will run without PROJECT_ROOT/HME_* env vars" >&2
fi

# Activity-driven adaptation: tmp/hme-adaptive-config.sh is regenerated by
# tools/HME/scripts/adapt-from-activity.py from recent activity events.
# Sourced AFTER .env so adaptive values override static defaults. Every
# hook session picks up the latest adaptation without restart.
_HME_ADAPT_FILE="${PROJECT_ROOT:-}/tmp/hme-adaptive-config.sh"
if [ -n "${PROJECT_ROOT:-}" ] && [ -f "$_HME_ADAPT_FILE" ]; then
  # shellcheck disable=SC1090
  source "$_HME_ADAPT_FILE"
fi
