#!/usr/bin/env python3
"""Activity-driven adaptation engine.

Reads tools/HME/config/adaptation-rules.json and output/metrics/hme-activity.jsonl,
evaluates each rule's trigger against the rule's recent-event window, and writes
the rule's export into tmp/hme-adaptive-config.sh. Hooks source this file so
behavior tightens or relaxes based on observed patterns instead of fixed defaults.

Safe predicates (no arbitrary eval):
  count_event(event=<str>)
  count_event_reason(event=<str>, reason_contains=<str>)
  top_k_concentration(event=<str>, key=<str>, k=<int>)  # fraction of events
                                                        # concentrated in top-k keys

Intended cadence: run from posttooluse_bash.sh after round_complete, or on-demand.
"""
from __future__ import annotations
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path

PROJECT_ROOT = Path(os.environ.get("PROJECT_ROOT", Path(__file__).resolve().parent.parent.parent.parent))
RULES = PROJECT_ROOT / "tools" / "HME" / "config" / "adaptation-rules.json"
ACTIVITY = PROJECT_ROOT / "output" / "metrics" / "hme-activity.jsonl"
OUT = PROJECT_ROOT / "tmp" / "hme-adaptive-config.sh"
DECISIONS = PROJECT_ROOT / "output" / "metrics" / "hme-adaptation-decisions.jsonl"

_PREDICATE_RE = re.compile(r"^\s*(count_event|count_event_reason|top_k_concentration)\((.*)\)\s*(>=|>|<=|<|==)\s*([\d.]+)\s*$")


def _load_events(max_events: int) -> list[dict]:
    if not ACTIVITY.is_file():
        return []
    try:
        lines = ACTIVITY.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []
    out: list[dict] = []
    for line in lines[-max_events:]:
        try:
            out.append(json.loads(line))
        except (ValueError, TypeError):
            continue
    return out


def _parse_kwargs(s: str) -> dict:
    kw: dict[str, str | int] = {}
    for part in s.split(","):
        if "=" not in part:
            continue
        k, v = part.split("=", 1)
        k = k.strip()
        v = v.strip().strip("'\"")
        if v.isdigit():
            kw[k] = int(v)
        else:
            kw[k] = v
    return kw


def _predicate(events: list[dict], expr: str) -> bool:
    m = _PREDICATE_RE.match(expr)
    if not m:
        return False
    fn, args_s, op, thr_s = m.groups()
    threshold = float(thr_s)
    kw = _parse_kwargs(args_s)
    if fn == "count_event":
        n = sum(1 for e in events if e.get("event") == kw.get("event"))
        val = float(n)
    elif fn == "count_event_reason":
        target = kw.get("reason_contains", "")
        n = sum(1 for e in events
                if e.get("event") == kw.get("event")
                and target in str(e.get("reason", "")))
        val = float(n)
    elif fn == "top_k_concentration":
        key = str(kw.get("key", ""))
        k = int(kw.get("k", 3))
        ev = kw.get("event")
        keys = Counter(
            e.get(key, "")
            for e in events
            if (not ev or e.get("event") == ev) and e.get(key)
        )
        if not keys:
            return False
        top_sum = sum(n for _, n in keys.most_common(k))
        total = sum(keys.values())
        val = top_sum / total if total else 0.0
    else:
        return False
    return _compare(val, op, threshold)


def _compare(lhs: float, op: str, rhs: float) -> bool:
    if op == ">=": return lhs >= rhs
    if op == ">":  return lhs > rhs
    if op == "<=": return lhs <= rhs
    if op == "<":  return lhs < rhs
    if op == "==": return lhs == rhs
    return False


def main() -> int:
    if not RULES.is_file():
        return 0
    with open(RULES) as f:
        cfg = json.load(f)
    rules = cfg.get("rules", [])
    if not rules:
        return 0

    max_window = max((r.get("window", 50) for r in rules), default=50)
    events = _load_events(max_window)

    lines = [
        "#!/usr/bin/env bash",
        "# AUTO-GENERATED by tools/HME/scripts/adapt-from-activity.py.",
        "# Sourced by _safety.sh at hook-fire time. Do not edit by hand.",
        "",
    ]
    decisions = []
    for rule in rules:
        scoped = events[-rule.get("window", 50):]
        fired = _predicate(scoped, rule.get("trigger", ""))
        value = rule.get("value_when_fired") if fired else rule.get("value_when_dormant")
        if value is not None:
            lines.append(f'export {rule["export"]}="{value}"')
        decisions.append({
            "rule": rule.get("id"),
            "fired": fired,
            "export": rule.get("export"),
            "value": value,
            "window": rule.get("window"),
        })
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")

    if decisions:
        DECISIONS.parent.mkdir(parents=True, exist_ok=True)
        with open(DECISIONS, "a") as f:
            for d in decisions:
                f.write(json.dumps(d) + "\n")

    fired_count = sum(1 for d in decisions if d["fired"])
    print(f"adapt-from-activity: {fired_count}/{len(decisions)} rules fired")
    return 0


if __name__ == "__main__":
    sys.exit(main())
