#!/usr/bin/env python3
"""Generate a mermaid graph of the repo structure + dir_intent summaries.

Walks tracked + non-ignored directories (via git ls-files), reads the
first non-empty content line of each dir's README.md as the dir_intent
summary, and emits a `graph TD` mermaid block. The script replaces
content between the marker comments below in the main README.md.

  <!-- BEGIN_REPO_MERMAID -->
  ...auto-generated block...
  <!-- END_REPO_MERMAID -->

Depth defaults to 3 levels so the diagram stays readable. Raise with
--max-depth.

Run: python3 tools/HME/scripts/generate-repo-mermaid.py
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
README = REPO_ROOT / "README.md"
BEGIN = "<!-- BEGIN_REPO_MERMAID -->"
END = "<!-- END_REPO_MERMAID -->"


def tracked_files(root: Path) -> list[Path]:
    rc = subprocess.run(
        ["git", "-C", str(root), "ls-files"],
        capture_output=True, text=True, check=True,
    )
    return [Path(line) for line in rc.stdout.splitlines() if line.strip()]


def dir_intent(abs_path: Path) -> str:
    readme = abs_path / "README.md"
    if not readme.is_file():
        return ""
    try:
        text = readme.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""
    # Stop before the auto-generated block so the root README's dir_intent
    # is stable even after this script writes to it.
    if BEGIN in text:
        text = text.split(BEGIN, 1)[0]
    for line in text.splitlines():
        stripped = line.strip()
        if (not stripped
                or stripped.startswith("#")
                or stripped.startswith("<!--")
                or stripped.startswith("```")):
            continue
        if len(stripped) > 80:
            stripped = stripped[:77] + "..."
        return stripped
    return ""


def safe_id(rel: str) -> str:
    """Mermaid-safe node identifier."""
    if rel == ".":
        return "root"
    return re.sub(r"[^A-Za-z0-9_]", "_", rel.replace("/", "__"))


def safe_label(text: str) -> str:
    """Quote-friendly mermaid label content."""
    return text.replace('"', "'").replace("\n", " ")


def build_graph(root: Path, max_depth: int) -> str:
    files = tracked_files(root)
    dirs: set[Path] = {Path(".")}
    for f in files:
        for parent in f.parents:
            if str(parent) == ".":
                continue
            depth = len(parent.parts)
            if depth > max_depth:
                continue
            dirs.add(parent)

    parents: dict[Path, Path | None] = {Path("."): None}
    for d in dirs:
        if d == Path("."):
            continue
        parents[d] = Path(*d.parts[:-1]) if len(d.parts) > 1 else Path(".")

    lines = ["graph TD"]
    # Stable ordering for diff-friendliness.
    for d in sorted(dirs, key=lambda p: (len(p.parts), str(p))):
        node_id = safe_id(str(d))
        if d == Path("."):
            label_main = "Polychron"
        else:
            label_main = d.name + "/"
        intent = dir_intent(root / d)
        label = f"{label_main}<br/><i>{safe_label(intent)}</i>" if intent else label_main
        lines.append(f'    {node_id}["{safe_label(label)}"]')
    for d in sorted(dirs, key=lambda p: (len(p.parts), str(p))):
        parent = parents[d]
        if parent is None:
            continue
        lines.append(f"    {safe_id(str(parent))} --> {safe_id(str(d))}")
    return "\n".join(lines)


def render_block(graph: str, max_depth: int) -> str:
    return (
        f"{BEGIN}\n"
        f"<!-- auto-generated by tools/HME/scripts/generate-repo-mermaid.py "
        f"(max_depth={max_depth}); do not edit by hand -->\n"
        f"```mermaid\n"
        f"{graph}\n"
        f"```\n"
        f"{END}\n"
    )


def update_readme(block: str) -> bool:
    text = README.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)
        new = pattern.sub(block, text)
    else:
        # Append before the last section if no markers yet.
        new = text.rstrip() + "\n\n## Repo Map\n\n" + block
    if new == text:
        return False
    README.write_text(new, encoding="utf-8")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-depth", type=int, default=3,
                    help="maximum directory depth to include (default 3)")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the mermaid block to stdout instead of writing")
    args = ap.parse_args()

    graph = build_graph(REPO_ROOT, args.max_depth)
    block = render_block(graph, args.max_depth)
    if args.dry_run:
        sys.stdout.write(block)
        return 0
    changed = update_readme(block)
    print("README.md updated" if changed else "README.md already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
