#!/usr/bin/env python3
"""i/why mode=architecture-snapshot -- composite full-system report.

Single command that runs every diagnostic panel and concatenates the
output. Useful for debug-trace-grade reports -- sharing the full state
of HME with another agent, archiving for post-mortem, or just "show
me everything" moments without invoking 8 commands.

Pure composition: no new computation. Each panel is invoked via its
current public command surface; output is collected and labeled with section headers.
"""
from __future__ import annotations
import os
import subprocess
import sys

from _common import PROJECT_ROOT


PANELS = [
    # (label, wrapper, args)
    ("State machine snapshot", "i/status", ["state"]),
    ("Holograph (all 10 horizons)", "i/status", ["holograph"]),
    ("Multi-axis bands", "i/status", ["mode=multi-axis-band"]),
    ("Conjugate channel quadrants", "i/status", ["mode=conjugate"]),
    ("Agent-loop quality", "i/status", ["mode=agent-loop"]),
    ("Tool-cost preflighting", "i/status", ["mode=tool-latency"]),
    ("HCI by subtag", "i/status", ["mode=hci-by-subtag"]),
    ("Band tuning proposal", "i/status", ["mode=band-tuning"]),
    ("Verifier utility", "i/why", ["mode=verifier-utility"]),
    ("Verifier coverage", "i/why", ["mode=verifier-coverage"]),
    ("Verifier drift", "i/why", ["mode=verifier-drift"]),
    ("KB graph", "i/why", ["mode=kb-graph"]),
    ("Fractal-shape signature", "i/why", ["mode=fractal-shape"]),
    ("Architectural conscience", "i/why", ["mode=conscience"]),
]


def _run_panel(wrapper: str, args: list[str]) -> str:
    """Invoke one panel via its wrapper. Bounded timeout to keep the
    composite report from hanging on a slow panel."""
    path = os.path.join(PROJECT_ROOT, wrapper)
    if not os.path.isfile(path):
        return f"  (wrapper {wrapper} missing)"
    try:
        r = subprocess.run([path] + args, capture_output=True,
                           text=True, timeout=30,
                           cwd=PROJECT_ROOT,
                           env={**os.environ, "PROJECT_ROOT": PROJECT_ROOT})
    except subprocess.TimeoutExpired:
        return "  (panel timed out at 30s)"
    except OSError as e:
        return f"  (panel invocation failed: {e})"
    if r.stdout:
        return r.stdout.rstrip()
    if r.stderr:
        return f"  (stderr: {r.stderr.strip()[:200]})"
    return "  (no output)"


def main(argv):
    print("# HME Architecture Snapshot")
    print(f"  Composite report -- every diagnostic panel concatenated.")
    print(f"  Generated by `i/why mode=architecture-snapshot`.")
    print()
    for label, wrapper, args in PANELS:
        # Use 3-dash dividers (4+ identical chars trigger the spam
        print(f"--- {label} ---")
        print(_run_panel(wrapper, args))
        print()
    print("# Composite report complete.")
    print(f"  {len(PANELS)} panels rendered. For drill-in, invoke any panel directly.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv) or 0)
