// scripts/generatePolyrhythmTable.js
// Enumerate all valid polyrhythm meter pairs within config ranges and write
// them as a naked-global JS file: src/time/polyrhythmPairs.js
//
// Two meters form a valid polyrhythm when whole-number multiples align exactly
// in duration, with both layer measure counts >= 2 and total measures > 3
// (matching getPolyrhythm.js acceptance criteria).
//
// length = pm1 × (n1/d1) — total phrase duration in whole-note units
// Example: 3 measures of 4/4 → 3 × (4/4) = 3.0
//
// Usage:  node scripts/generatePolyrhythmTable.js
//         node scripts/generatePolyrhythmTable.js --max-measures 8

'use strict';

const fs   = require('fs');
const path = require('path');

// ── Read limits from config.js ────────────────────────────────────────────────
const CONFIG_PATH = path.join(__dirname, '..', 'src', 'conductor', 'config.js');
const configSrc   = fs.readFileSync(CONFIG_PATH, 'utf8');

function readConfigBlock(name) {
  const re = new RegExp(name + '\\s*=\\s*\\{[^}]*\\bmin\\s*:\\s*(\\d+)[^}]*\\bmax\\s*:\\s*(\\d+)', 's');
  const hit = configSrc.match(re);
  if (!hit) throw new Error(`generatePolyrhythmTable: could not parse ${name} from config.js`);
  return { min: parseInt(hit[1], 10), max: parseInt(hit[2], 10) };
}

const { min: N_MIN, max: N_MAX } = readConfigBlock('NUMERATOR');
const { min: D_MIN, max: D_MAX } = readConfigBlock('DENOMINATOR');

// ── CLI args ──────────────────────────────────────────────────────────────────
const LENGTH_MIN = 1.5;   // shortest allowed phrase length (whole-note units)
const LENGTH_MAX = 5;  // longest allowed phrase length (whole-note units)

const args = process.argv.slice(2);
const mmArg  = args.indexOf('--max-measures');
const outArg = args.indexOf('--out');
const MAX_MEASURES = mmArg !== -1 ? parseInt(args[mmArg + 1], 10) : 10;
const OUT_PATH = outArg !== -1
  ? args[outArg + 1]
  : path.join(__dirname, '..', 'src', 'time', 'polyrhythmPairs.js');

// ── Helpers ───────────────────────────────────────────────────────────────────
function gcd(a, b) { while (b) { [a, b] = [b, a % b]; } return a; }

// ── Generate ──────────────────────────────────────────────────────────────────
/** @type {Array<{n1:number, d1:number, pm1:number, n2:number, d2:number, pm2:number, length:number}>} */
const pairs = [];
const seen = new Set();

for (let n1 = N_MIN; n1 <= N_MAX; n1++) {
  for (let d1 = D_MIN; d1 <= D_MAX; d1++) {
    for (let n2 = N_MIN; n2 <= N_MAX; n2++) {
      for (let d2 = D_MIN; d2 <= D_MAX; d2++) {
        if (n1 === n2 && d1 === d2) continue; // same meter — no polyrhythm
        if (n1 / d1 === n2 / d2) continue; // same ratio — no polyrhythm
        // Find smallest pm1, pm2 >= 2 with pm1*(n1/d1) == pm2*(n2/d2)
        // Equivalent: pm1 * A == pm2 * B  where A = n1*d2, B = n2*d1
        const A = n1 * d2;
        const B = n2 * d1;
        const g = gcd(A, B);
        const a = A / g; // pm2 = a * k
        const b = B / g; // pm1 = b * k

        // Smallest k such that both b*k >= 2 and a*k >= 2
        const kMin = Math.max(Math.ceil(2 / b), Math.ceil(2 / a));
        const pm1 = b * kMin;
        const pm2 = a * kMin;

        if (pm1 > MAX_MEASURES || pm2 > MAX_MEASURES) continue;

        // Mirror of getPolyrhythm.js: totalMeasures > 3
        const totalMeasures = pm1 + pm2;
        if (totalMeasures <= 3) continue;

        // Deduplicate: canonical form = smaller ratio first, then smaller numerator
        const r1 = n1 / d1, r2 = n2 / d2;
        const ordered = r1 < r2 || (r1 === r2 && n1 <= n2)
          ? [n1, d1, pm1, n2, d2, pm2]
          : [n2, d2, pm2, n1, d1, pm1];
        const key = ordered.join(':');
        if (seen.has(key)) continue;
        seen.add(key);

        const length = pm1 * n1 / d1; // = pm2 * n2 / d2
        if (length < LENGTH_MIN || length > LENGTH_MAX) continue;
        pairs.push({ n1, d1, pm1, n2, d2, pm2, length });
      }
    }
  }
}

pairs.sort((a, b) => a.length - b.length);

// ── Output — JS global file ───────────────────────────────────────────────────
const pad = (s, n) => String(s).padStart(n);
const fmt = p => {
  const len = p.length % 1 === 0
    ? String(p.length)
    : p.length.toFixed(6).replace(/\.?0+$/, '');
  return (
    `  { n1: ${pad(p.n1,2)}, d1: ${pad(p.d1,2)}, pm1: ${pad(p.pm1,2)},` +
    `  n2: ${pad(p.n2,2)}, d2: ${pad(p.d2,2)}, pm2: ${pad(p.pm2,2)},  length: ${len} }`
  );
};

const lines = [
  `// Auto-generated by scripts/generatePolyrhythmTable.js — do not edit by hand.`,
  `// Run: node scripts/generatePolyrhythmTable.js to regenerate.`,
  `// ${pairs.length} pairs | numerator ${N_MIN}–${N_MAX}, denominator ${D_MIN}–${D_MAX}, max ${MAX_MEASURES} measures/layer, length ${LENGTH_MIN}–${LENGTH_MAX}`,
  `// length = pm1 × (n1/d1) = pm2 × (n2/d2) — total phrase duration in whole-note units`,
  `// sorted: shortest → longest`,
  ``,
  `POLYRHYTHM_PAIRS = [`,
  pairs.map(fmt).join(',\n'),
  `];`,
];
const output = lines.join('\n') + '\n';

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, output, 'utf8');
console.log(`Written ${pairs.length} pairs → ${OUT_PATH}`);
