#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const root = process.env.PROJECT_ROOT || path.resolve(__dirname, '..');
const registry = JSON.parse(fs.readFileSync(path.join(root, 'tools/HME/i_registry.json'), 'utf8'));
const iDir = path.join(root, 'i');

for (const name of Object.keys(registry.commands || {}).sort()) {
  const target = path.join(iDir, name);
  const body = `#!/usr/bin/env bash
# generated by scripts/generate-i-shims.js; edit tools/HME/i_registry.json or scripts/hme-i-dispatch.js
exec "$(cd "$(dirname "$0")/.." && pwd)/scripts/hme-i-dispatch.js" "${name}" "$@"
`;
  fs.writeFileSync(target, body);
  fs.chmodSync(target, 0o755);
}
