#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const root = process.env.PROJECT_ROOT || path.resolve(__dirname, '..');
const registry = JSON.parse(fs.readFileSync(path.join(root, 'tools/HME/i_registry.json'), 'utf8'));
const iDir = path.join(root, 'i');
const check = process.argv.includes('--check');

function bodyFor(name) {
  return `#!/usr/bin/env bash
# generated by scripts/generate-i-shims.js; edit tools/HME/i_registry.json or scripts/hme-i-dispatch.js
exec "$(cd "$(dirname "$0")/.." && pwd)/scripts/hme-i-dispatch.js" "${name}" "$@"
`;
}

const commands = Object.keys(registry.commands || {}).sort();
const expected = new Map(commands.map((name) => [name, bodyFor(name)]));
const actualFiles = fs.readdirSync(iDir).filter((name) => {
  if (name.startsWith('.')) return false;
  return fs.statSync(path.join(iDir, name)).isFile();
}).sort();

if (check) {
  const issues = [];
  for (const file of actualFiles) {
    if (!expected.has(file)) issues.push(`extra i/${file}`);
  }
  for (const [name, body] of expected) {
    const target = path.join(iDir, name);
    if (!fs.existsSync(target)) {
      issues.push(`missing i/${name}`);
      continue;
    }
    const current = fs.readFileSync(target, 'utf8');
    if (current !== body) issues.push(`stale i/${name}`);
    if ((fs.statSync(target).mode & 0o111) === 0) issues.push(`not executable i/${name}`);
  }
  if (issues.length) {
    console.error(issues.join('\n'));
    process.exit(1);
  }
  console.log(`i/ shims match ${path.relative(root, path.join(root, 'tools/HME/i_registry.json'))}`);
  process.exit(0);
}

for (const [name, body] of expected) {
  const target = path.join(iDir, name);
  fs.writeFileSync(target, body);
  fs.chmodSync(target, 0o755);
}
