module.exports = {
  rules: {
    'no-silent-early-return': require('./no-silent-early-return'),
    'no-requires-outside-index': require('./no-requires-outside-index'),
    'no-console-acceptable-warning': require('./no-console-acceptable-warning'),
    'no-math-random': require('./no-math-random'),
    'no-useless-expose-dependencies-comments': require('./no-useless-expose-dependencies-comments'),
    'only-error-throws': require('./only-error-throws'),
    'no-typeof-validated-global': require('./no-typeof-validated-global'),
    'no-unstamped-validator': require('./no-unstamped-validator'),
    'no-conductor-registration-from-crosslayer': require('./no-conductor-registration-from-crosslayer'),
    'no-direct-signal-read': require('./no-direct-signal-read'),
    'validator-name-matches-filename': require('./validator-name-matches-filename'),
    'case-conventions': require('./case-conventions'),
    'no-non-ascii': require('./no-non-ascii'),
    'no-unregistered-feedback-loop': require('./no-unregistered-feedback-loop'),
    'no-direct-conductor-state-from-crosslayer': require('./no-direct-conductor-state-from-crosslayer'),
    'no-direct-crosslayer-write-from-conductor': require('./no-direct-crosslayer-write-from-conductor'),
    'no-direct-buffer-push-from-crosslayer': require('./no-direct-buffer-push-from-crosslayer'),
    'prefer-validator': require('./prefer-validator'),
    'no-bare-math': require('./no-bare-math'),
    'no-direct-coupling-matrix-read': require('./no-direct-coupling-matrix-read'),
    'no-empty-catch': require('./no-empty-catch'),
    'no-bare-l0-channel': require('./no-bare-l0-channel'),
    'no-doubled-fallback': require('./no-doubled-fallback'),
    'no-or-fallback-on-config-read': require('./no-or-fallback-on-config-read'),
    'no-or-fallback-on-map-get': require('./no-or-fallback-on-map-get'),
    'no-bare-declared-global-in-init': require('./no-bare-declared-global-in-init')
  }
};
